C     This File is Automatically generated by ALOHA 
C     The process calculated in this file is: 
C     P(1,2) - P(1,3)
C     
      SUBROUTINE VSS1_0(V1, S2, S3, COUP,VERTEX)
      IMPLICIT NONE
      COMPLEX*16 CI
      PARAMETER (CI=(0D0,1D0))
      COMPLEX*16 TMP2
      COMPLEX*16 S3(*)
      COMPLEX*16 S2(*)
      REAL*8 P2(0:3)
      REAL*8 P3(0:3)
      COMPLEX*16 VERTEX
      COMPLEX*16 COUP
      COMPLEX*16 V1(*)
      COMPLEX*16 TMP3
      P2(0) = DBLE(S2(1))
      P2(1) = DBLE(S2(2))
      P2(2) = DIMAG(S2(2))
      P2(3) = DIMAG(S2(1))
      P3(0) = DBLE(S3(1))
      P3(1) = DBLE(S3(2))
      P3(2) = DIMAG(S3(2))
      P3(3) = DIMAG(S3(1))
      TMP3 = (V1(3)*P3(0)-V1(4)*P3(1)-V1(5)*P3(2)-V1(6)*P3(3))
      TMP2 = (P2(0)*V1(3)-P2(1)*V1(4)-P2(2)*V1(5)-P2(3)*V1(6))
      VERTEX = COUP*S2(3)*S3(3)*(-CI*(TMP2)+CI*(TMP3))
      END


