ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
c      written by the UFO converter
ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc

      WRITE(*,*)  ' Couplings of mssm'
      WRITE(*,*)  ' ---------------------------------'
      WRITE(*,*)  ' '
      WRITE(*,2) 'GC_7 = ', GC_7
      WRITE(*,2) 'GC_53 = ', GC_53
      WRITE(*,2) 'GC_518 = ', GC_518
      WRITE(*,2) 'GC_587 = ', GC_587
      WRITE(*,2) 'GC_237 = ', GC_237
      WRITE(*,2) 'GC_414 = ', GC_414
