// Class: ReadDistro24Increase
// Automatically generated by MethodBase::MakeClass
//

/* configuration options =====================================================

#GEN -*-*-*-*-*-*-*-*-*-*-*- general info -*-*-*-*-*-*-*-*-*-*-*-

Method         : MLP::Distro24Increase
TMVA Release   : 4.2.0         [262656]
ROOT Release   : 5.34/18       [336402]
Creator        : zxb0111
Date           : Thu Dec  4 11:57:33 2014
Host           : Linux localhost.localdomain 2.6.32-431.17.1.el6.x86_64 #1 SMP Wed May 7 14:14:17 CDT 2014 x86_64 x86_64 x86_64 GNU/Linux
Dir            : /home/zxb0111/seminar
Training events: 34086
Analysis type  : [Classification]


#OPT -*-*-*-*-*-*-*-*-*-*-*-*- options -*-*-*-*-*-*-*-*-*-*-*-*-

# Set by User:
NCycles: "600" [Number of training cycles]
HiddenLayers: "11,7,6" [Specification of hidden layer architecture]
NeuronType: "sigmoid" [Neuron activation function type]
VarTransform: "N" [List of variable transformations performed before training, e.g., "D_Background,P_Signal,G,N_AllClasses" for: "Decorrelation, PCA-transformation, Gaussianisation, Normalisation, each for the given class of events ('AllClasses' denotes all events of all classes, if no class indication is given, 'All' is assumed)"]
TestRate: "5" [Test for overtraining performed at each #th epochs]
UseRegulator: "False" [Use regulator to avoid over-training]
# Default:
RandomSeed: "1" [Random seed for initial synapse weights (0 means unique seed for each run; default value '1')]
EstimatorType: "MSE" [MSE (Mean Square Estimator) for Gaussian Likelihood or CE(Cross-Entropy) for Bernoulli Likelihood]
NeuronInputType: "sum" [Neuron input function type]
V: "False" [Verbose output (short form of "VerbosityLevel" below - overrides the latter one)]
VerbosityLevel: "Default" [Verbosity level]
H: "False" [Print method-specific help message]
CreateMVAPdfs: "False" [Create PDFs for classifier outputs (signal and background)]
IgnoreNegWeightsInTraining: "False" [Events with negative weights are ignored in the training (but are included for testing and performance evaluation)]
TrainingMethod: "BP" [Train with Back-Propagation (BP), BFGS Algorithm (BFGS), or Genetic Algorithm (GA - slower and worse)]
LearningRate: "2.000000e-02" [ANN learning rate parameter]
DecayRate: "1.000000e-02" [Decay rate for learning parameter]
EpochMonitoring: "False" [Provide epoch-wise monitoring plots according to TestRate (caution: causes big ROOT output file!)]
Sampling: "1.000000e+00" [Only 'Sampling' (randomly selected) events are trained each epoch]
SamplingEpoch: "1.000000e+00" [Sampling is used for the first 'SamplingEpoch' epochs, afterwards, all events are taken for training]
SamplingImportance: "1.000000e+00" [ The sampling weights of events in epochs which successful (worse estimator than before) are multiplied with SamplingImportance, else they are divided.]
SamplingTraining: "True" [The training sample is sampled]
SamplingTesting: "False" [The testing sample is sampled]
ResetStep: "50" [How often BFGS should reset history]
Tau: "3.000000e+00" [LineSearch "size step"]
BPMode: "sequential" [Back-propagation learning mode: sequential or batch]
BatchSize: "-1" [Batch size: number of events/batch, only set if in Batch Mode, -1 for BatchSize=number_of_events]
ConvergenceImprove: "1.000000e-30" [Minimum improvement which counts as improvement (<0 means automatic convergence check is turned off)]
ConvergenceTests: "-1" [Number of steps (without improvement) required for convergence (<0 means automatic convergence check is turned off)]
UpdateLimit: "10000" [Maximum times of regulator update]
CalculateErrors: "False" [Calculates inverse Hessian matrix at the end of the training to be able to calculate the uncertainties of an MVA value]
WeightRange: "1.000000e+00" [Take the events for the estimator calculations from small deviations from the desired value to large deviations only over the weight range]
##


#VAR -*-*-*-*-*-*-*-*-*-*-*-* variables *-*-*-*-*-*-*-*-*-*-*-*-

NVar 8
Jet.PT                        Jet.PT                        Jet.PT                        Jet.PT                                                          'F'    [4.73000001907,2543.40991211]
Jet.Eta                       Jet.Eta                       Jet.Eta                       Jet.Eta                                                         'F'    [-3.99300003052,3.99099993706]
Jet.Phi                       Jet.Phi                       Jet.Phi                       Jet.Phi                                                         'F'    [0,6.28299999237]
Jet.Mass                      Jet.Mass                      Jet.Mass                      Jet.Mass                                                        'F'    [0,258.730010986]
Jet.Ntrk                      Jet.Ntrk                      Jet.Ntrk                      Jet.Ntrk                                                        'F'    [0,61]
Jet.EhadOverEem               Jet.EhadOverEem               Jet.EhadOverEem               Jet.EhadOverEem                                                 'F'    [0,999]
MissingET.Phi                 MissingET.Phi                 MissingET.Phi                 MissingET.Phi                                                   'F'    [0,6.28299999237]
MissingET.MET                 MissingET.MET                 MissingET.MET                 MissingET.MET                                                   'F'    [100.010002136,1585.47998047]
NSpec 0


============================================================================ */

#include <vector>
#include <cmath>
#include <string>
#include <iostream>

#ifndef IClassifierReader__def
#define IClassifierReader__def

class IClassifierReader {

 public:

   // constructor
   IClassifierReader() : fStatusIsClean( true ) {}
   virtual ~IClassifierReader() {}

   // return classifier response
   virtual double GetMvaValue( const std::vector<double>& inputValues ) const = 0;

   // returns classifier status
   bool IsStatusClean() const { return fStatusIsClean; }

 protected:

   bool fStatusIsClean;
};

#endif

class ReadDistro24Increase : public IClassifierReader {

 public:

   // constructor
   ReadDistro24Increase( std::vector<std::string>& theInputVars ) 
      : IClassifierReader(),
        fClassName( "ReadDistro24Increase" ),
        fNvars( 8 ),
        fIsNormalised( false )
   {      
      // the training input variables
      const char* inputVars[] = { "Jet.PT", "Jet.Eta", "Jet.Phi", "Jet.Mass", "Jet.Ntrk", "Jet.EhadOverEem", "MissingET.Phi", "MissingET.MET" };

      // sanity checks
      if (theInputVars.size() <= 0) {
         std::cout << "Problem in class \"" << fClassName << "\": empty input vector" << std::endl;
         fStatusIsClean = false;
      }

      if (theInputVars.size() != fNvars) {
         std::cout << "Problem in class \"" << fClassName << "\": mismatch in number of input values: "
                   << theInputVars.size() << " != " << fNvars << std::endl;
         fStatusIsClean = false;
      }

      // validate input variables
      for (size_t ivar = 0; ivar < theInputVars.size(); ivar++) {
         if (theInputVars[ivar] != inputVars[ivar]) {
            std::cout << "Problem in class \"" << fClassName << "\": mismatch in input variable names" << std::endl
                      << " for variable [" << ivar << "]: " << theInputVars[ivar].c_str() << " != " << inputVars[ivar] << std::endl;
            fStatusIsClean = false;
         }
      }

      // initialize min and max vectors (for normalisation)
      fVmin[0] = -1;
      fVmax[0] = 1;
      fVmin[1] = -1;
      fVmax[1] = 1;
      fVmin[2] = -1;
      fVmax[2] = 0.99999988079071;
      fVmin[3] = -1;
      fVmax[3] = 1;
      fVmin[4] = -1;
      fVmax[4] = 0.99999988079071;
      fVmin[5] = -1;
      fVmax[5] = 1;
      fVmin[6] = -1;
      fVmax[6] = 0.99999988079071;
      fVmin[7] = -1;
      fVmax[7] = 1;

      // initialize input variable types
      fType[0] = 'F';
      fType[1] = 'F';
      fType[2] = 'F';
      fType[3] = 'F';
      fType[4] = 'F';
      fType[5] = 'F';
      fType[6] = 'F';
      fType[7] = 'F';

      // initialize constants
      Initialize();

      // initialize transformation
      InitTransform();
   }

   // destructor
   virtual ~ReadDistro24Increase() {
      Clear(); // method-specific
   }

   // the classifier response
   // "inputValues" is a vector of input values in the same order as the 
   // variables given to the constructor
   double GetMvaValue( const std::vector<double>& inputValues ) const;

 private:

   // method-specific destructor
   void Clear();

   // input variable transformation

   double fMin_1[3][8];
   double fMax_1[3][8];
   void InitTransform_1();
   void Transform_1( std::vector<double> & iv, int sigOrBgd ) const;
   void InitTransform();
   void Transform( std::vector<double> & iv, int sigOrBgd ) const;

   // common member variables
   const char* fClassName;

   const size_t fNvars;
   size_t GetNvar()           const { return fNvars; }
   char   GetType( int ivar ) const { return fType[ivar]; }

   // normalisation of input variables
   const bool fIsNormalised;
   bool IsNormalised() const { return fIsNormalised; }
   double fVmin[8];
   double fVmax[8];
   double NormVariable( double x, double xmin, double xmax ) const {
      // normalise to output range: [-1, 1]
      return 2*(x - xmin)/(xmax - xmin) - 1.0;
   }

   // type of input variable: 'F' or 'I'
   char   fType[8];

   // initialize internal variables
   void Initialize();
   double GetMvaValue__( const std::vector<double>& inputValues ) const;

   // private members (method specific)

   double ActivationFnc(double x) const;
   double OutputActivationFnc(double x) const;

   int fLayers;
   int fLayerSize[5];
   double fWeightMatrix0to1[12][9];   // weight matrix from layer 0 to 1
   double fWeightMatrix1to2[8][12];   // weight matrix from layer 1 to 2
   double fWeightMatrix2to3[7][8];   // weight matrix from layer 2 to 3
   double fWeightMatrix3to4[1][7];   // weight matrix from layer 3 to 4

   double * fWeights[5];
};

inline void ReadDistro24Increase::Initialize()
{
   // build network structure
   fLayers = 5;
   fLayerSize[0] = 9; fWeights[0] = new double[9]; 
   fLayerSize[1] = 12; fWeights[1] = new double[12]; 
   fLayerSize[2] = 8; fWeights[2] = new double[8]; 
   fLayerSize[3] = 7; fWeights[3] = new double[7]; 
   fLayerSize[4] = 1; fWeights[4] = new double[1]; 
   // weight matrix from layer 0 to 1
   fWeightMatrix0to1[0][0] = -2.00496433997839;
   fWeightMatrix0to1[1][0] = 2.37770018888217;
   fWeightMatrix0to1[2][0] = 1.78062299957282;
   fWeightMatrix0to1[3][0] = 0.887465601136059;
   fWeightMatrix0to1[4][0] = -4.51365440195077;
   fWeightMatrix0to1[5][0] = -1.86273479828952;
   fWeightMatrix0to1[6][0] = -1.64380415591267;
   fWeightMatrix0to1[7][0] = 5.6212043739059;
   fWeightMatrix0to1[8][0] = -1.42965323672396;
   fWeightMatrix0to1[9][0] = -1.30910707681374;
   fWeightMatrix0to1[10][0] = -2.24657034559688;
   fWeightMatrix0to1[0][1] = -0.344150393655682;
   fWeightMatrix0to1[1][1] = 0.341730496431186;
   fWeightMatrix0to1[2][1] = 0.845392747556794;
   fWeightMatrix0to1[3][1] = 0.251252973170541;
   fWeightMatrix0to1[4][1] = 0.11777584159712;
   fWeightMatrix0to1[5][1] = -0.437643745504516;
   fWeightMatrix0to1[6][1] = 0.303522629271234;
   fWeightMatrix0to1[7][1] = 0.307740831185424;
   fWeightMatrix0to1[8][1] = 3.25972218126765;
   fWeightMatrix0to1[9][1] = -0.219300411233159;
   fWeightMatrix0to1[10][1] = -1.47658690344949;
   fWeightMatrix0to1[0][2] = 2.37998546369712;
   fWeightMatrix0to1[1][2] = 3.10678515881085;
   fWeightMatrix0to1[2][2] = -0.00958978570035041;
   fWeightMatrix0to1[3][2] = -1.73724473690832;
   fWeightMatrix0to1[4][2] = 0.0661691909302053;
   fWeightMatrix0to1[5][2] = 0.627184623237921;
   fWeightMatrix0to1[6][2] = -4.05507485729829;
   fWeightMatrix0to1[7][2] = -0.17538616024893;
   fWeightMatrix0to1[8][2] = 0.152693698057036;
   fWeightMatrix0to1[9][2] = 1.88095077232044;
   fWeightMatrix0to1[10][2] = 0.194996981156043;
   fWeightMatrix0to1[0][3] = 0.318549795352779;
   fWeightMatrix0to1[1][3] = 0.384162319386315;
   fWeightMatrix0to1[2][3] = -1.0271253373174;
   fWeightMatrix0to1[3][3] = -2.13204028601239;
   fWeightMatrix0to1[4][3] = -0.620816400532896;
   fWeightMatrix0to1[5][3] = -1.08060592931093;
   fWeightMatrix0to1[6][3] = 0.254600640678466;
   fWeightMatrix0to1[7][3] = 1.93432951609199;
   fWeightMatrix0to1[8][3] = 1.41939608552013;
   fWeightMatrix0to1[9][3] = 1.59447291560469;
   fWeightMatrix0to1[10][3] = 0.308203420766962;
   fWeightMatrix0to1[0][4] = -0.627101855852937;
   fWeightMatrix0to1[1][4] = -0.723923333506385;
   fWeightMatrix0to1[2][4] = 1.10621181949907;
   fWeightMatrix0to1[3][4] = -0.112912496898106;
   fWeightMatrix0to1[4][4] = 0.31452707769026;
   fWeightMatrix0to1[5][4] = 1.75514630945559;
   fWeightMatrix0to1[6][4] = -0.323512885285735;
   fWeightMatrix0to1[7][4] = 0.342796206154882;
   fWeightMatrix0to1[8][4] = -0.783411387678217;
   fWeightMatrix0to1[9][4] = 1.31134470705121;
   fWeightMatrix0to1[10][4] = -2.1739976664175;
   fWeightMatrix0to1[0][5] = 0.294154788663437;
   fWeightMatrix0to1[1][5] = -0.773827992792968;
   fWeightMatrix0to1[2][5] = -3.63395487027962;
   fWeightMatrix0to1[3][5] = 1.42085795162826;
   fWeightMatrix0to1[4][5] = 1.41922249829965;
   fWeightMatrix0to1[5][5] = -1.12506381890903;
   fWeightMatrix0to1[6][5] = 1.38172283361233;
   fWeightMatrix0to1[7][5] = -0.55962051038429;
   fWeightMatrix0to1[8][5] = 1.50692436147007;
   fWeightMatrix0to1[9][5] = 1.70434829054602;
   fWeightMatrix0to1[10][5] = -0.898339325963198;
   fWeightMatrix0to1[0][6] = -2.10022500626216;
   fWeightMatrix0to1[1][6] = -3.37533919191215;
   fWeightMatrix0to1[2][6] = -0.562993540450248;
   fWeightMatrix0to1[3][6] = 1.55968104380399;
   fWeightMatrix0to1[4][6] = 0.273161152717788;
   fWeightMatrix0to1[5][6] = -1.88288263419812;
   fWeightMatrix0to1[6][6] = 4.04108260849494;
   fWeightMatrix0to1[7][6] = 0.126750435721057;
   fWeightMatrix0to1[8][6] = 0.0559623334514622;
   fWeightMatrix0to1[9][6] = -0.638712844107198;
   fWeightMatrix0to1[10][6] = -1.42005382212381;
   fWeightMatrix0to1[0][7] = -3.71542933337988;
   fWeightMatrix0to1[1][7] = 2.52843962614642;
   fWeightMatrix0to1[2][7] = 3.42389302213429;
   fWeightMatrix0to1[3][7] = 3.47086841234507;
   fWeightMatrix0to1[4][7] = 6.65137725787674;
   fWeightMatrix0to1[5][7] = -0.00790265545444813;
   fWeightMatrix0to1[6][7] = 0.105799734005954;
   fWeightMatrix0to1[7][7] = -3.1215632189508;
   fWeightMatrix0to1[8][7] = -0.99755428839628;
   fWeightMatrix0to1[9][7] = 0.991778942567902;
   fWeightMatrix0to1[10][7] = -1.43206563039273;
   fWeightMatrix0to1[0][8] = -5.02213863340028;
   fWeightMatrix0to1[1][8] = -1.81061865627367;
   fWeightMatrix0to1[2][8] = 2.39480041999079;
   fWeightMatrix0to1[3][8] = 0.530395959106704;
   fWeightMatrix0to1[4][8] = 1.69094500330683;
   fWeightMatrix0to1[5][8] = -2.22160867636652;
   fWeightMatrix0to1[6][8] = -1.85747621702247;
   fWeightMatrix0to1[7][8] = 2.09691736944094;
   fWeightMatrix0to1[8][8] = -1.66219928273157;
   fWeightMatrix0to1[9][8] = -1.27603382052458;
   fWeightMatrix0to1[10][8] = -0.467712123178397;
   // weight matrix from layer 1 to 2
   fWeightMatrix1to2[0][0] = 1.08335361303555;
   fWeightMatrix1to2[1][0] = -1.31403345766287;
   fWeightMatrix1to2[2][0] = -2.36687341348031;
   fWeightMatrix1to2[3][0] = 0.975181680211989;
   fWeightMatrix1to2[4][0] = 2.42595070600954;
   fWeightMatrix1to2[5][0] = -1.14529369116793;
   fWeightMatrix1to2[6][0] = 3.73272953205617;
   fWeightMatrix1to2[0][1] = -1.74500227139971;
   fWeightMatrix1to2[1][1] = -1.49309417919869;
   fWeightMatrix1to2[2][1] = 0.563441789450095;
   fWeightMatrix1to2[3][1] = -0.110213358659322;
   fWeightMatrix1to2[4][1] = -2.23528538264783;
   fWeightMatrix1to2[5][1] = 0.234201437358242;
   fWeightMatrix1to2[6][1] = -2.01479533750484;
   fWeightMatrix1to2[0][2] = -0.0189454497849904;
   fWeightMatrix1to2[1][2] = -2.03943850808147;
   fWeightMatrix1to2[2][2] = 2.30490664934571;
   fWeightMatrix1to2[3][2] = -0.0823476817762833;
   fWeightMatrix1to2[4][2] = -1.16281603625572;
   fWeightMatrix1to2[5][2] = 0.818202771535041;
   fWeightMatrix1to2[6][2] = -2.75461242552888;
   fWeightMatrix1to2[0][3] = -2.61668204503134;
   fWeightMatrix1to2[1][3] = -0.403641357896863;
   fWeightMatrix1to2[2][3] = 0.0228114201848566;
   fWeightMatrix1to2[3][3] = 1.36402143831507;
   fWeightMatrix1to2[4][3] = 0.154934072402608;
   fWeightMatrix1to2[5][3] = -0.0533362463176567;
   fWeightMatrix1to2[6][3] = -2.58586878578837;
   fWeightMatrix1to2[0][4] = -1.02059417072329;
   fWeightMatrix1to2[1][4] = -2.59156553973997;
   fWeightMatrix1to2[2][4] = 1.63292940490537;
   fWeightMatrix1to2[3][4] = -0.283169767717086;
   fWeightMatrix1to2[4][4] = -3.07478935339788;
   fWeightMatrix1to2[5][4] = 0.616725364426163;
   fWeightMatrix1to2[6][4] = -4.27087322508476;
   fWeightMatrix1to2[0][5] = 0.209369971152958;
   fWeightMatrix1to2[1][5] = 1.29031034519102;
   fWeightMatrix1to2[2][5] = 0.361089195942728;
   fWeightMatrix1to2[3][5] = -1.94205211961091;
   fWeightMatrix1to2[4][5] = -0.153356964744954;
   fWeightMatrix1to2[5][5] = 1.542165024258;
   fWeightMatrix1to2[6][5] = 1.93162572636555;
   fWeightMatrix1to2[0][6] = 1.96157200319055;
   fWeightMatrix1to2[1][6] = -0.689957024155737;
   fWeightMatrix1to2[2][6] = -1.63070142714977;
   fWeightMatrix1to2[3][6] = -1.49143249178873;
   fWeightMatrix1to2[4][6] = 1.46537252178187;
   fWeightMatrix1to2[5][6] = 1.23088679914397;
   fWeightMatrix1to2[6][6] = 4.89765664555414;
   fWeightMatrix1to2[0][7] = -1.88163220002008;
   fWeightMatrix1to2[1][7] = -0.242025046398578;
   fWeightMatrix1to2[2][7] = -0.0606007717267097;
   fWeightMatrix1to2[3][7] = 0.448893908370053;
   fWeightMatrix1to2[4][7] = 1.50553298570388;
   fWeightMatrix1to2[5][7] = -0.467329828784798;
   fWeightMatrix1to2[6][7] = -4.21703206996709;
   fWeightMatrix1to2[0][8] = 1.0269367035314;
   fWeightMatrix1to2[1][8] = 0.791409562060128;
   fWeightMatrix1to2[2][8] = 0.197095429714957;
   fWeightMatrix1to2[3][8] = 0.87117384800574;
   fWeightMatrix1to2[4][8] = -0.580093651798642;
   fWeightMatrix1to2[5][8] = 1.50943251929757;
   fWeightMatrix1to2[6][8] = 2.35857438502966;
   fWeightMatrix1to2[0][9] = 0.40238851841747;
   fWeightMatrix1to2[1][9] = 0.512235923842845;
   fWeightMatrix1to2[2][9] = 1.14174137133591;
   fWeightMatrix1to2[3][9] = -0.596873578019096;
   fWeightMatrix1to2[4][9] = -0.626939661181437;
   fWeightMatrix1to2[5][9] = 1.0490238964071;
   fWeightMatrix1to2[6][9] = -1.14686469965447;
   fWeightMatrix1to2[0][10] = -0.460624814361717;
   fWeightMatrix1to2[1][10] = 1.53888195133482;
   fWeightMatrix1to2[2][10] = 0.472851097479513;
   fWeightMatrix1to2[3][10] = -0.537051993374067;
   fWeightMatrix1to2[4][10] = 1.5914823433465;
   fWeightMatrix1to2[5][10] = 1.85785317803319;
   fWeightMatrix1to2[6][10] = -1.95973355913014;
   fWeightMatrix1to2[0][11] = 0.249035935921225;
   fWeightMatrix1to2[1][11] = -0.267136781187824;
   fWeightMatrix1to2[2][11] = 0.201463278389031;
   fWeightMatrix1to2[3][11] = -1.99547337327029;
   fWeightMatrix1to2[4][11] = -1.58708953430006;
   fWeightMatrix1to2[5][11] = 1.16417832842467;
   fWeightMatrix1to2[6][11] = 0.818229699219411;
   // weight matrix from layer 2 to 3
   fWeightMatrix2to3[0][0] = -1.73834511191916;
   fWeightMatrix2to3[1][0] = -0.556716452041658;
   fWeightMatrix2to3[2][0] = -1.43844606245157;
   fWeightMatrix2to3[3][0] = 0.539869927655246;
   fWeightMatrix2to3[4][0] = 3.4216153628326;
   fWeightMatrix2to3[5][0] = -0.416492341399251;
   fWeightMatrix2to3[0][1] = -0.475927431513708;
   fWeightMatrix2to3[1][1] = -0.741331312457791;
   fWeightMatrix2to3[2][1] = 0.395849355802107;
   fWeightMatrix2to3[3][1] = 2.51403484121564;
   fWeightMatrix2to3[4][1] = 0.745448836012393;
   fWeightMatrix2to3[5][1] = 0.0414645774666033;
   fWeightMatrix2to3[0][2] = -0.793349216484259;
   fWeightMatrix2to3[1][2] = -3.31748935519688;
   fWeightMatrix2to3[2][2] = 0.255460116763515;
   fWeightMatrix2to3[3][2] = -0.619659826855811;
   fWeightMatrix2to3[4][2] = -2.73627747512911;
   fWeightMatrix2to3[5][2] = -1.59115093446146;
   fWeightMatrix2to3[0][3] = 0.321189159083858;
   fWeightMatrix2to3[1][3] = -0.0994771680309905;
   fWeightMatrix2to3[2][3] = -1.95334048381122;
   fWeightMatrix2to3[3][3] = 1.22029254817722;
   fWeightMatrix2to3[4][3] = 0.363472243726534;
   fWeightMatrix2to3[5][3] = -0.979577287948862;
   fWeightMatrix2to3[0][4] = -0.117048029205733;
   fWeightMatrix2to3[1][4] = 1.55349931180453;
   fWeightMatrix2to3[2][4] = 0.417341796617693;
   fWeightMatrix2to3[3][4] = 1.20607789348224;
   fWeightMatrix2to3[4][4] = 1.68487053525053;
   fWeightMatrix2to3[5][4] = -2.1735044748298;
   fWeightMatrix2to3[0][5] = -0.920711695295094;
   fWeightMatrix2to3[1][5] = 0.517841544550932;
   fWeightMatrix2to3[2][5] = 0.0765889100813397;
   fWeightMatrix2to3[3][5] = 0.0331102466698563;
   fWeightMatrix2to3[4][5] = -1.02299391547648;
   fWeightMatrix2to3[5][5] = 0.760355191856361;
   fWeightMatrix2to3[0][6] = -1.72179586175349;
   fWeightMatrix2to3[1][6] = -1.74054929170431;
   fWeightMatrix2to3[2][6] = -0.859099643135254;
   fWeightMatrix2to3[3][6] = -1.99741190930394;
   fWeightMatrix2to3[4][6] = 6.22961005007386;
   fWeightMatrix2to3[5][6] = 2.14759184316416;
   fWeightMatrix2to3[0][7] = -1.22838319024888;
   fWeightMatrix2to3[1][7] = -0.395161623631188;
   fWeightMatrix2to3[2][7] = -1.41182927351044;
   fWeightMatrix2to3[3][7] = -2.43489806320793;
   fWeightMatrix2to3[4][7] = -2.42293338924131;
   fWeightMatrix2to3[5][7] = -0.238369215358827;
   // weight matrix from layer 3 to 4
   fWeightMatrix3to4[0][0] = -0.136108874422693;
   fWeightMatrix3to4[0][1] = 0.541048521769377;
   fWeightMatrix3to4[0][2] = 0.0996848247879679;
   fWeightMatrix3to4[0][3] = 1.14067749287237;
   fWeightMatrix3to4[0][4] = -1.18372458153635;
   fWeightMatrix3to4[0][5] = 1.03102706174394;
   fWeightMatrix3to4[0][6] = 0.65867287534377;
}

inline double ReadDistro24Increase::GetMvaValue__( const std::vector<double>& inputValues ) const
{
   if (inputValues.size() != (unsigned int)fLayerSize[0]-1) {
      std::cout << "Input vector needs to be of size " << fLayerSize[0]-1 << std::endl;
      return 0;
   }

   for (int l=0; l<fLayers; l++)
      for (int i=0; i<fLayerSize[l]; i++) fWeights[l][i]=0;

   for (int l=0; l<fLayers-1; l++)
      fWeights[l][fLayerSize[l]-1]=1;

   for (int i=0; i<fLayerSize[0]-1; i++)
      fWeights[0][i]=inputValues[i];

   // layer 0 to 1
   for (int o=0; o<fLayerSize[1]-1; o++) {
      for (int i=0; i<fLayerSize[0]; i++) {
         double inputVal = fWeightMatrix0to1[o][i] * fWeights[0][i];
         fWeights[1][o] += inputVal;
      }
      fWeights[1][o] = ActivationFnc(fWeights[1][o]);
   }
   // layer 1 to 2
   for (int o=0; o<fLayerSize[2]-1; o++) {
      for (int i=0; i<fLayerSize[1]; i++) {
         double inputVal = fWeightMatrix1to2[o][i] * fWeights[1][i];
         fWeights[2][o] += inputVal;
      }
      fWeights[2][o] = ActivationFnc(fWeights[2][o]);
   }
   // layer 2 to 3
   for (int o=0; o<fLayerSize[3]-1; o++) {
      for (int i=0; i<fLayerSize[2]; i++) {
         double inputVal = fWeightMatrix2to3[o][i] * fWeights[2][i];
         fWeights[3][o] += inputVal;
      }
      fWeights[3][o] = ActivationFnc(fWeights[3][o]);
   }
   // layer 3 to 4
   for (int o=0; o<fLayerSize[4]; o++) {
      for (int i=0; i<fLayerSize[3]; i++) {
         double inputVal = fWeightMatrix3to4[o][i] * fWeights[3][i];
         fWeights[4][o] += inputVal;
      }
      fWeights[4][o] = OutputActivationFnc(fWeights[4][o]);
   }

   return fWeights[4][0];
}

double ReadDistro24Increase::ActivationFnc(double x) const {
   // sigmoid
   return 1.0/(1.0+exp(-x));
}
double ReadDistro24Increase::OutputActivationFnc(double x) const {
   // identity
   return x;
}
   
// Clean up
inline void ReadDistro24Increase::Clear() 
{
   // clean up the arrays
   for (int lIdx = 0; lIdx < 5; lIdx++) {
      delete[] fWeights[lIdx];
   }
}
   inline double ReadDistro24Increase::GetMvaValue( const std::vector<double>& inputValues ) const
   {
      // classifier response value
      double retval = 0;

      // classifier response, sanity check first
      if (!IsStatusClean()) {
         std::cout << "Problem in class \"" << fClassName << "\": cannot return classifier response"
                   << " because status is dirty" << std::endl;
         retval = 0;
      }
      else {
         if (IsNormalised()) {
            // normalise variables
            std::vector<double> iV;
            iV.resize(inputValues.size());
            int ivar = 0;
            for (std::vector<double>::const_iterator varIt = inputValues.begin();
                 varIt != inputValues.end(); varIt++, ivar++) {
               iV.push_back(NormVariable( *varIt, fVmin[ivar], fVmax[ivar] ));
            }
            Transform( iV, -1 );
            retval = GetMvaValue__( iV );
         }
         else {
            std::vector<double> iV;
            int ivar = 0;
            for (std::vector<double>::const_iterator varIt = inputValues.begin();
                 varIt != inputValues.end(); varIt++, ivar++) {
               iV.push_back(*varIt);
            }
            Transform( iV, -1 );
            retval = GetMvaValue__( iV );
         }
      }

      return retval;
   }

//_______________________________________________________________________
inline void ReadDistro24Increase::InitTransform_1()
{
   // Normalization transformation, initialisation
   fMin_1[0][0] = 5;
   fMax_1[0][0] = 2543.40991211;
   fMin_1[1][0] = 4.73000001907;
   fMax_1[1][0] = 817.520019531;
   fMin_1[2][0] = 4.73000001907;
   fMax_1[2][0] = 2543.40991211;
   fMin_1[0][1] = -3.99099993706;
   fMax_1[0][1] = 3.99099993706;
   fMin_1[1][1] = -3.99300003052;
   fMax_1[1][1] = 3.99000000954;
   fMin_1[2][1] = -3.99300003052;
   fMax_1[2][1] = 3.99099993706;
   fMin_1[0][2] = 0;
   fMax_1[0][2] = 6.28299999237;
   fMin_1[1][2] = 0;
   fMax_1[1][2] = 6.28299999237;
   fMin_1[2][2] = 0;
   fMax_1[2][2] = 6.28299999237;
   fMin_1[0][3] = 0;
   fMax_1[0][3] = 258.730010986;
   fMin_1[1][3] = 0;
   fMax_1[1][3] = 159.369995117;
   fMin_1[2][3] = 0;
   fMax_1[2][3] = 258.730010986;
   fMin_1[0][4] = 0;
   fMax_1[0][4] = 61;
   fMin_1[1][4] = 0;
   fMax_1[1][4] = 59;
   fMin_1[2][4] = 0;
   fMax_1[2][4] = 61;
   fMin_1[0][5] = 0;
   fMax_1[0][5] = 999;
   fMin_1[1][5] = 0;
   fMax_1[1][5] = 999;
   fMin_1[2][5] = 0;
   fMax_1[2][5] = 999;
   fMin_1[0][6] = 0;
   fMax_1[0][6] = 6.28299999237;
   fMin_1[1][6] = 0.0010000000475;
   fMax_1[1][6] = 6.28200006485;
   fMin_1[2][6] = 0;
   fMax_1[2][6] = 6.28299999237;
   fMin_1[0][7] = 100.019996643;
   fMax_1[0][7] = 1585.47998047;
   fMin_1[1][7] = 100.010002136;
   fMax_1[1][7] = 662.650024414;
   fMin_1[2][7] = 100.010002136;
   fMax_1[2][7] = 1585.47998047;
}

//_______________________________________________________________________
inline void ReadDistro24Increase::Transform_1( std::vector<double>& iv, int cls) const
{
   // Normalization transformation
   if (cls < 0 || cls > 2) {
   if (2 > 1 ) cls = 2;
      else cls = 2;
   }
   const int nVar = 8;

   // get indices of used variables

   // define the indices of the variables which are transformed by this transformation
   static std::vector<int> indicesGet;
   static std::vector<int> indicesPut;

   if ( indicesGet.empty() ) { 
      indicesGet.reserve(nVar);
      indicesGet.push_back( 0);
      indicesGet.push_back( 1);
      indicesGet.push_back( 2);
      indicesGet.push_back( 3);
      indicesGet.push_back( 4);
      indicesGet.push_back( 5);
      indicesGet.push_back( 6);
      indicesGet.push_back( 7);
   } 
   if ( indicesPut.empty() ) { 
      indicesPut.reserve(nVar);
      indicesPut.push_back( 0);
      indicesPut.push_back( 1);
      indicesPut.push_back( 2);
      indicesPut.push_back( 3);
      indicesPut.push_back( 4);
      indicesPut.push_back( 5);
      indicesPut.push_back( 6);
      indicesPut.push_back( 7);
   } 

   static std::vector<double> dv;
   dv.resize(nVar);
   for (int ivar=0; ivar<nVar; ivar++) dv[ivar] = iv[indicesGet.at(ivar)];
   for (int ivar=0;ivar<8;ivar++) {
      double offset = fMin_1[cls][ivar];
      double scale  = 1.0/(fMax_1[cls][ivar]-fMin_1[cls][ivar]);
      iv[indicesPut.at(ivar)] = (dv[ivar]-offset)*scale * 2 - 1;
   }
}

//_______________________________________________________________________
inline void ReadDistro24Increase::InitTransform()
{
   InitTransform_1();
}

//_______________________________________________________________________
inline void ReadDistro24Increase::Transform( std::vector<double>& iv, int sigOrBgd ) const
{
   Transform_1( iv, sigOrBgd );
}
