// Class: Read3Layers15Increase
// Automatically generated by MethodBase::MakeClass
//

/* configuration options =====================================================

#GEN -*-*-*-*-*-*-*-*-*-*-*- general info -*-*-*-*-*-*-*-*-*-*-*-

Method         : MLP::3Layers15Increase
TMVA Release   : 4.2.0         [262656]
ROOT Release   : 5.34/18       [336402]
Creator        : zxb0111
Date           : Sat Dec  6 22:53:42 2014
Host           : Linux localhost.localdomain 2.6.32-431.17.1.el6.x86_64 #1 SMP Wed May 7 14:14:17 CDT 2014 x86_64 x86_64 x86_64 GNU/Linux
Dir            : /home/zxb0111/seminar
Training events: 34086
Analysis type  : [Classification]


#OPT -*-*-*-*-*-*-*-*-*-*-*-*- options -*-*-*-*-*-*-*-*-*-*-*-*-

# Set by User:
NCycles: "600" [Number of training cycles]
HiddenLayers: "3,5,7" [Specification of hidden layer architecture]
NeuronType: "sigmoid" [Neuron activation function type]
VarTransform: "N" [List of variable transformations performed before training, e.g., "D_Background,P_Signal,G,N_AllClasses" for: "Decorrelation, PCA-transformation, Gaussianisation, Normalisation, each for the given class of events ('AllClasses' denotes all events of all classes, if no class indication is given, 'All' is assumed)"]
TestRate: "5" [Test for overtraining performed at each #th epochs]
UseRegulator: "False" [Use regulator to avoid over-training]
# Default:
RandomSeed: "1" [Random seed for initial synapse weights (0 means unique seed for each run; default value '1')]
EstimatorType: "MSE" [MSE (Mean Square Estimator) for Gaussian Likelihood or CE(Cross-Entropy) for Bernoulli Likelihood]
NeuronInputType: "sum" [Neuron input function type]
V: "False" [Verbose output (short form of "VerbosityLevel" below - overrides the latter one)]
VerbosityLevel: "Default" [Verbosity level]
H: "False" [Print method-specific help message]
CreateMVAPdfs: "False" [Create PDFs for classifier outputs (signal and background)]
IgnoreNegWeightsInTraining: "False" [Events with negative weights are ignored in the training (but are included for testing and performance evaluation)]
TrainingMethod: "BP" [Train with Back-Propagation (BP), BFGS Algorithm (BFGS), or Genetic Algorithm (GA - slower and worse)]
LearningRate: "2.000000e-02" [ANN learning rate parameter]
DecayRate: "1.000000e-02" [Decay rate for learning parameter]
EpochMonitoring: "False" [Provide epoch-wise monitoring plots according to TestRate (caution: causes big ROOT output file!)]
Sampling: "1.000000e+00" [Only 'Sampling' (randomly selected) events are trained each epoch]
SamplingEpoch: "1.000000e+00" [Sampling is used for the first 'SamplingEpoch' epochs, afterwards, all events are taken for training]
SamplingImportance: "1.000000e+00" [ The sampling weights of events in epochs which successful (worse estimator than before) are multiplied with SamplingImportance, else they are divided.]
SamplingTraining: "True" [The training sample is sampled]
SamplingTesting: "False" [The testing sample is sampled]
ResetStep: "50" [How often BFGS should reset history]
Tau: "3.000000e+00" [LineSearch "size step"]
BPMode: "sequential" [Back-propagation learning mode: sequential or batch]
BatchSize: "-1" [Batch size: number of events/batch, only set if in Batch Mode, -1 for BatchSize=number_of_events]
ConvergenceImprove: "1.000000e-30" [Minimum improvement which counts as improvement (<0 means automatic convergence check is turned off)]
ConvergenceTests: "-1" [Number of steps (without improvement) required for convergence (<0 means automatic convergence check is turned off)]
UpdateLimit: "10000" [Maximum times of regulator update]
CalculateErrors: "False" [Calculates inverse Hessian matrix at the end of the training to be able to calculate the uncertainties of an MVA value]
WeightRange: "1.000000e+00" [Take the events for the estimator calculations from small deviations from the desired value to large deviations only over the weight range]
##


#VAR -*-*-*-*-*-*-*-*-*-*-*-* variables *-*-*-*-*-*-*-*-*-*-*-*-

NVar 8
Jet.PT                        Jet.PT                        Jet.PT                        Jet.PT                                                          'F'    [4.73000001907,2543.40991211]
Jet.Eta                       Jet.Eta                       Jet.Eta                       Jet.Eta                                                         'F'    [-3.99300003052,3.99099993706]
Jet.Phi                       Jet.Phi                       Jet.Phi                       Jet.Phi                                                         'F'    [0,6.28299999237]
Jet.Mass                      Jet.Mass                      Jet.Mass                      Jet.Mass                                                        'F'    [0,258.730010986]
Jet.Ntrk                      Jet.Ntrk                      Jet.Ntrk                      Jet.Ntrk                                                        'F'    [0,61]
Jet.EhadOverEem               Jet.EhadOverEem               Jet.EhadOverEem               Jet.EhadOverEem                                                 'F'    [0,999]
MissingET.Phi                 MissingET.Phi                 MissingET.Phi                 MissingET.Phi                                                   'F'    [0,6.28299999237]
MissingET.MET                 MissingET.MET                 MissingET.MET                 MissingET.MET                                                   'F'    [100.010002136,1585.47998047]
NSpec 0


============================================================================ */

#include <vector>
#include <cmath>
#include <string>
#include <iostream>

#ifndef IClassifierReader__def
#define IClassifierReader__def

class IClassifierReader {

 public:

   // constructor
   IClassifierReader() : fStatusIsClean( true ) {}
   virtual ~IClassifierReader() {}

   // return classifier response
   virtual double GetMvaValue( const std::vector<double>& inputValues ) const = 0;

   // returns classifier status
   bool IsStatusClean() const { return fStatusIsClean; }

 protected:

   bool fStatusIsClean;
};

#endif

class Read3Layers15Increase : public IClassifierReader {

 public:

   // constructor
   Read3Layers15Increase( std::vector<std::string>& theInputVars ) 
      : IClassifierReader(),
        fClassName( "Read3Layers15Increase" ),
        fNvars( 8 ),
        fIsNormalised( false )
   {      
      // the training input variables
      const char* inputVars[] = { "Jet.PT", "Jet.Eta", "Jet.Phi", "Jet.Mass", "Jet.Ntrk", "Jet.EhadOverEem", "MissingET.Phi", "MissingET.MET" };

      // sanity checks
      if (theInputVars.size() <= 0) {
         std::cout << "Problem in class \"" << fClassName << "\": empty input vector" << std::endl;
         fStatusIsClean = false;
      }

      if (theInputVars.size() != fNvars) {
         std::cout << "Problem in class \"" << fClassName << "\": mismatch in number of input values: "
                   << theInputVars.size() << " != " << fNvars << std::endl;
         fStatusIsClean = false;
      }

      // validate input variables
      for (size_t ivar = 0; ivar < theInputVars.size(); ivar++) {
         if (theInputVars[ivar] != inputVars[ivar]) {
            std::cout << "Problem in class \"" << fClassName << "\": mismatch in input variable names" << std::endl
                      << " for variable [" << ivar << "]: " << theInputVars[ivar].c_str() << " != " << inputVars[ivar] << std::endl;
            fStatusIsClean = false;
         }
      }

      // initialize min and max vectors (for normalisation)
      fVmin[0] = -1;
      fVmax[0] = 1;
      fVmin[1] = -1;
      fVmax[1] = 1;
      fVmin[2] = -1;
      fVmax[2] = 0.99999988079071;
      fVmin[3] = -1;
      fVmax[3] = 1;
      fVmin[4] = -1;
      fVmax[4] = 0.99999988079071;
      fVmin[5] = -1;
      fVmax[5] = 1;
      fVmin[6] = -1;
      fVmax[6] = 0.99999988079071;
      fVmin[7] = -1;
      fVmax[7] = 1;

      // initialize input variable types
      fType[0] = 'F';
      fType[1] = 'F';
      fType[2] = 'F';
      fType[3] = 'F';
      fType[4] = 'F';
      fType[5] = 'F';
      fType[6] = 'F';
      fType[7] = 'F';

      // initialize constants
      Initialize();

      // initialize transformation
      InitTransform();
   }

   // destructor
   virtual ~Read3Layers15Increase() {
      Clear(); // method-specific
   }

   // the classifier response
   // "inputValues" is a vector of input values in the same order as the 
   // variables given to the constructor
   double GetMvaValue( const std::vector<double>& inputValues ) const;

 private:

   // method-specific destructor
   void Clear();

   // input variable transformation

   double fMin_1[3][8];
   double fMax_1[3][8];
   void InitTransform_1();
   void Transform_1( std::vector<double> & iv, int sigOrBgd ) const;
   void InitTransform();
   void Transform( std::vector<double> & iv, int sigOrBgd ) const;

   // common member variables
   const char* fClassName;

   const size_t fNvars;
   size_t GetNvar()           const { return fNvars; }
   char   GetType( int ivar ) const { return fType[ivar]; }

   // normalisation of input variables
   const bool fIsNormalised;
   bool IsNormalised() const { return fIsNormalised; }
   double fVmin[8];
   double fVmax[8];
   double NormVariable( double x, double xmin, double xmax ) const {
      // normalise to output range: [-1, 1]
      return 2*(x - xmin)/(xmax - xmin) - 1.0;
   }

   // type of input variable: 'F' or 'I'
   char   fType[8];

   // initialize internal variables
   void Initialize();
   double GetMvaValue__( const std::vector<double>& inputValues ) const;

   // private members (method specific)

   double ActivationFnc(double x) const;
   double OutputActivationFnc(double x) const;

   int fLayers;
   int fLayerSize[5];
   double fWeightMatrix0to1[4][9];   // weight matrix from layer 0 to 1
   double fWeightMatrix1to2[6][4];   // weight matrix from layer 1 to 2
   double fWeightMatrix2to3[8][6];   // weight matrix from layer 2 to 3
   double fWeightMatrix3to4[1][8];   // weight matrix from layer 3 to 4

   double * fWeights[5];
};

inline void Read3Layers15Increase::Initialize()
{
   // build network structure
   fLayers = 5;
   fLayerSize[0] = 9; fWeights[0] = new double[9]; 
   fLayerSize[1] = 4; fWeights[1] = new double[4]; 
   fLayerSize[2] = 6; fWeights[2] = new double[6]; 
   fLayerSize[3] = 8; fWeights[3] = new double[8]; 
   fLayerSize[4] = 1; fWeights[4] = new double[1]; 
   // weight matrix from layer 0 to 1
   fWeightMatrix0to1[0][0] = -2.45713042674399;
   fWeightMatrix0to1[1][0] = 2.73585515964771;
   fWeightMatrix0to1[2][0] = 3.17697672611474;
   fWeightMatrix0to1[0][1] = -0.0297712385749316;
   fWeightMatrix0to1[1][1] = -0.352015220964864;
   fWeightMatrix0to1[2][1] = -0.0401199189212125;
   fWeightMatrix0to1[0][2] = -0.141957314347861;
   fWeightMatrix0to1[1][2] = 2.49724930339917;
   fWeightMatrix0to1[2][2] = -1.31193270037619;
   fWeightMatrix0to1[0][3] = 0.25009588877654;
   fWeightMatrix0to1[1][3] = -0.970725015592246;
   fWeightMatrix0to1[2][3] = 0.302921279467704;
   fWeightMatrix0to1[0][4] = -0.541118815511106;
   fWeightMatrix0to1[1][4] = 0.750101059253802;
   fWeightMatrix0to1[2][4] = 0.124808995677416;
   fWeightMatrix0to1[0][5] = 2.20204437469969;
   fWeightMatrix0to1[1][5] = 0.772557931961961;
   fWeightMatrix0to1[2][5] = 2.62530343862171;
   fWeightMatrix0to1[0][6] = -0.203229157205951;
   fWeightMatrix0to1[1][6] = 2.4370368650784;
   fWeightMatrix0to1[2][6] = -1.35083988983894;
   fWeightMatrix0to1[0][7] = -8.43393636570264;
   fWeightMatrix0to1[1][7] = 1.22825320310489;
   fWeightMatrix0to1[2][7] = 0.0341429567275697;
   fWeightMatrix0to1[0][8] = -7.78438066862732;
   fWeightMatrix0to1[1][8] = -0.594836477733281;
   fWeightMatrix0to1[2][8] = 3.26865468188415;
   // weight matrix from layer 1 to 2
   fWeightMatrix1to2[0][0] = -7.42108974341842;
   fWeightMatrix1to2[1][0] = -2.89527695340954;
   fWeightMatrix1to2[2][0] = -0.278652720376699;
   fWeightMatrix1to2[3][0] = 1.26937539123418;
   fWeightMatrix1to2[4][0] = 2.20316294600013;
   fWeightMatrix1to2[0][1] = 1.80188082905738;
   fWeightMatrix1to2[1][1] = -0.408675919985589;
   fWeightMatrix1to2[2][1] = 0.200467650182083;
   fWeightMatrix1to2[3][1] = 0.0836650577524341;
   fWeightMatrix1to2[4][1] = -1.39002929065565;
   fWeightMatrix1to2[0][2] = 4.34040957654302;
   fWeightMatrix1to2[1][2] = -0.111188104889418;
   fWeightMatrix1to2[2][2] = 1.13954874049597;
   fWeightMatrix1to2[3][2] = 0.675518205355277;
   fWeightMatrix1to2[4][2] = 0.440180808168706;
   fWeightMatrix1to2[0][3] = 2.58622820169294;
   fWeightMatrix1to2[1][3] = 2.37348547517311;
   fWeightMatrix1to2[2][3] = -0.995503260445901;
   fWeightMatrix1to2[3][3] = -1.81395135519659;
   fWeightMatrix1to2[4][3] = 0.587893886179221;
   // weight matrix from layer 2 to 3
   fWeightMatrix2to3[0][0] = -2.04878119726404;
   fWeightMatrix2to3[1][0] = 1.45767354762765;
   fWeightMatrix2to3[2][0] = 1.35260460288439;
   fWeightMatrix2to3[3][0] = 2.47564199560374;
   fWeightMatrix2to3[4][0] = 0.389266586217079;
   fWeightMatrix2to3[5][0] = -4.85126283267147;
   fWeightMatrix2to3[6][0] = 0.802614562217617;
   fWeightMatrix2to3[0][1] = -3.3369947403858;
   fWeightMatrix2to3[1][1] = -0.939649267772341;
   fWeightMatrix2to3[2][1] = -1.39906742874509;
   fWeightMatrix2to3[3][1] = -1.86579496719625;
   fWeightMatrix2to3[4][1] = 0.599458398329689;
   fWeightMatrix2to3[5][1] = -0.0243883943798182;
   fWeightMatrix2to3[6][1] = -2.15230319989889;
   fWeightMatrix2to3[0][2] = -0.220273138614835;
   fWeightMatrix2to3[1][2] = -0.380017308922257;
   fWeightMatrix2to3[2][2] = 0.614582510762372;
   fWeightMatrix2to3[3][2] = 1.27361976611408;
   fWeightMatrix2to3[4][2] = -1.06346950440498;
   fWeightMatrix2to3[5][2] = 0.0719081159250234;
   fWeightMatrix2to3[6][2] = -1.73686626199199;
   fWeightMatrix2to3[0][3] = 0.24110495834225;
   fWeightMatrix2to3[1][3] = -0.881864341450011;
   fWeightMatrix2to3[2][3] = -0.772951800625184;
   fWeightMatrix2to3[3][3] = -1.50965599431236;
   fWeightMatrix2to3[4][3] = 0.169782924492654;
   fWeightMatrix2to3[5][3] = 0.996784152441398;
   fWeightMatrix2to3[6][3] = 1.47481648303386;
   fWeightMatrix2to3[0][4] = -1.32288944677872;
   fWeightMatrix2to3[1][4] = -1.98057587079884;
   fWeightMatrix2to3[2][4] = -1.9759377907068;
   fWeightMatrix2to3[3][4] = 0.0105010558952181;
   fWeightMatrix2to3[4][4] = -0.982145015184139;
   fWeightMatrix2to3[5][4] = 2.6669990509259;
   fWeightMatrix2to3[6][4] = 0.438050529316064;
   fWeightMatrix2to3[0][5] = -0.905840016865902;
   fWeightMatrix2to3[1][5] = -0.940833846790357;
   fWeightMatrix2to3[2][5] = -1.03363490142007;
   fWeightMatrix2to3[3][5] = -0.863553274338863;
   fWeightMatrix2to3[4][5] = -0.877536710484023;
   fWeightMatrix2to3[5][5] = -0.919843047422257;
   fWeightMatrix2to3[6][5] = -1.75489094616875;
   // weight matrix from layer 3 to 4
   fWeightMatrix3to4[0][0] = -0.992176248384052;
   fWeightMatrix3to4[0][1] = 0.111982751022622;
   fWeightMatrix3to4[0][2] = -0.122366338199009;
   fWeightMatrix3to4[0][3] = 0.657859731174281;
   fWeightMatrix3to4[0][4] = 0.244325386858108;
   fWeightMatrix3to4[0][5] = -0.934294828367631;
   fWeightMatrix3to4[0][6] = 1.55498777151401;
   fWeightMatrix3to4[0][7] = 0.537050590660123;
}

inline double Read3Layers15Increase::GetMvaValue__( const std::vector<double>& inputValues ) const
{
   if (inputValues.size() != (unsigned int)fLayerSize[0]-1) {
      std::cout << "Input vector needs to be of size " << fLayerSize[0]-1 << std::endl;
      return 0;
   }

   for (int l=0; l<fLayers; l++)
      for (int i=0; i<fLayerSize[l]; i++) fWeights[l][i]=0;

   for (int l=0; l<fLayers-1; l++)
      fWeights[l][fLayerSize[l]-1]=1;

   for (int i=0; i<fLayerSize[0]-1; i++)
      fWeights[0][i]=inputValues[i];

   // layer 0 to 1
   for (int o=0; o<fLayerSize[1]-1; o++) {
      for (int i=0; i<fLayerSize[0]; i++) {
         double inputVal = fWeightMatrix0to1[o][i] * fWeights[0][i];
         fWeights[1][o] += inputVal;
      }
      fWeights[1][o] = ActivationFnc(fWeights[1][o]);
   }
   // layer 1 to 2
   for (int o=0; o<fLayerSize[2]-1; o++) {
      for (int i=0; i<fLayerSize[1]; i++) {
         double inputVal = fWeightMatrix1to2[o][i] * fWeights[1][i];
         fWeights[2][o] += inputVal;
      }
      fWeights[2][o] = ActivationFnc(fWeights[2][o]);
   }
   // layer 2 to 3
   for (int o=0; o<fLayerSize[3]-1; o++) {
      for (int i=0; i<fLayerSize[2]; i++) {
         double inputVal = fWeightMatrix2to3[o][i] * fWeights[2][i];
         fWeights[3][o] += inputVal;
      }
      fWeights[3][o] = ActivationFnc(fWeights[3][o]);
   }
   // layer 3 to 4
   for (int o=0; o<fLayerSize[4]; o++) {
      for (int i=0; i<fLayerSize[3]; i++) {
         double inputVal = fWeightMatrix3to4[o][i] * fWeights[3][i];
         fWeights[4][o] += inputVal;
      }
      fWeights[4][o] = OutputActivationFnc(fWeights[4][o]);
   }

   return fWeights[4][0];
}

double Read3Layers15Increase::ActivationFnc(double x) const {
   // sigmoid
   return 1.0/(1.0+exp(-x));
}
double Read3Layers15Increase::OutputActivationFnc(double x) const {
   // identity
   return x;
}
   
// Clean up
inline void Read3Layers15Increase::Clear() 
{
   // clean up the arrays
   for (int lIdx = 0; lIdx < 5; lIdx++) {
      delete[] fWeights[lIdx];
   }
}
   inline double Read3Layers15Increase::GetMvaValue( const std::vector<double>& inputValues ) const
   {
      // classifier response value
      double retval = 0;

      // classifier response, sanity check first
      if (!IsStatusClean()) {
         std::cout << "Problem in class \"" << fClassName << "\": cannot return classifier response"
                   << " because status is dirty" << std::endl;
         retval = 0;
      }
      else {
         if (IsNormalised()) {
            // normalise variables
            std::vector<double> iV;
            iV.resize(inputValues.size());
            int ivar = 0;
            for (std::vector<double>::const_iterator varIt = inputValues.begin();
                 varIt != inputValues.end(); varIt++, ivar++) {
               iV.push_back(NormVariable( *varIt, fVmin[ivar], fVmax[ivar] ));
            }
            Transform( iV, -1 );
            retval = GetMvaValue__( iV );
         }
         else {
            std::vector<double> iV;
            int ivar = 0;
            for (std::vector<double>::const_iterator varIt = inputValues.begin();
                 varIt != inputValues.end(); varIt++, ivar++) {
               iV.push_back(*varIt);
            }
            Transform( iV, -1 );
            retval = GetMvaValue__( iV );
         }
      }

      return retval;
   }

//_______________________________________________________________________
inline void Read3Layers15Increase::InitTransform_1()
{
   // Normalization transformation, initialisation
   fMin_1[0][0] = 5;
   fMax_1[0][0] = 2543.40991211;
   fMin_1[1][0] = 4.73000001907;
   fMax_1[1][0] = 817.520019531;
   fMin_1[2][0] = 4.73000001907;
   fMax_1[2][0] = 2543.40991211;
   fMin_1[0][1] = -3.99099993706;
   fMax_1[0][1] = 3.99099993706;
   fMin_1[1][1] = -3.99300003052;
   fMax_1[1][1] = 3.99000000954;
   fMin_1[2][1] = -3.99300003052;
   fMax_1[2][1] = 3.99099993706;
   fMin_1[0][2] = 0;
   fMax_1[0][2] = 6.28299999237;
   fMin_1[1][2] = 0;
   fMax_1[1][2] = 6.28299999237;
   fMin_1[2][2] = 0;
   fMax_1[2][2] = 6.28299999237;
   fMin_1[0][3] = 0;
   fMax_1[0][3] = 258.730010986;
   fMin_1[1][3] = 0;
   fMax_1[1][3] = 159.369995117;
   fMin_1[2][3] = 0;
   fMax_1[2][3] = 258.730010986;
   fMin_1[0][4] = 0;
   fMax_1[0][4] = 61;
   fMin_1[1][4] = 0;
   fMax_1[1][4] = 59;
   fMin_1[2][4] = 0;
   fMax_1[2][4] = 61;
   fMin_1[0][5] = 0;
   fMax_1[0][5] = 999;
   fMin_1[1][5] = 0;
   fMax_1[1][5] = 999;
   fMin_1[2][5] = 0;
   fMax_1[2][5] = 999;
   fMin_1[0][6] = 0;
   fMax_1[0][6] = 6.28299999237;
   fMin_1[1][6] = 0.0010000000475;
   fMax_1[1][6] = 6.28200006485;
   fMin_1[2][6] = 0;
   fMax_1[2][6] = 6.28299999237;
   fMin_1[0][7] = 100.019996643;
   fMax_1[0][7] = 1585.47998047;
   fMin_1[1][7] = 100.010002136;
   fMax_1[1][7] = 662.650024414;
   fMin_1[2][7] = 100.010002136;
   fMax_1[2][7] = 1585.47998047;
}

//_______________________________________________________________________
inline void Read3Layers15Increase::Transform_1( std::vector<double>& iv, int cls) const
{
   // Normalization transformation
   if (cls < 0 || cls > 2) {
   if (2 > 1 ) cls = 2;
      else cls = 2;
   }
   const int nVar = 8;

   // get indices of used variables

   // define the indices of the variables which are transformed by this transformation
   static std::vector<int> indicesGet;
   static std::vector<int> indicesPut;

   if ( indicesGet.empty() ) { 
      indicesGet.reserve(nVar);
      indicesGet.push_back( 0);
      indicesGet.push_back( 1);
      indicesGet.push_back( 2);
      indicesGet.push_back( 3);
      indicesGet.push_back( 4);
      indicesGet.push_back( 5);
      indicesGet.push_back( 6);
      indicesGet.push_back( 7);
   } 
   if ( indicesPut.empty() ) { 
      indicesPut.reserve(nVar);
      indicesPut.push_back( 0);
      indicesPut.push_back( 1);
      indicesPut.push_back( 2);
      indicesPut.push_back( 3);
      indicesPut.push_back( 4);
      indicesPut.push_back( 5);
      indicesPut.push_back( 6);
      indicesPut.push_back( 7);
   } 

   static std::vector<double> dv;
   dv.resize(nVar);
   for (int ivar=0; ivar<nVar; ivar++) dv[ivar] = iv[indicesGet.at(ivar)];
   for (int ivar=0;ivar<8;ivar++) {
      double offset = fMin_1[cls][ivar];
      double scale  = 1.0/(fMax_1[cls][ivar]-fMin_1[cls][ivar]);
      iv[indicesPut.at(ivar)] = (dv[ivar]-offset)*scale * 2 - 1;
   }
}

//_______________________________________________________________________
inline void Read3Layers15Increase::InitTransform()
{
   InitTransform_1();
}

//_______________________________________________________________________
inline void Read3Layers15Increase::Transform( std::vector<double>& iv, int sigOrBgd ) const
{
   Transform_1( iv, sigOrBgd );
}
