// Class: ReadMLP2-BP
// Automatically generated by MethodBase::MakeClass
//

/* configuration options =====================================================

#GEN -*-*-*-*-*-*-*-*-*-*-*- general info -*-*-*-*-*-*-*-*-*-*-*-

Method         : MLP::MLP2-BP
TMVA Release   : 4.2.0         [262656]
ROOT Release   : 5.34/18       [336402]
Creator        : zxb0111
Date           : Tue Dec  2 17:02:15 2014
Host           : Linux localhost.localdomain 2.6.32-431.17.1.el6.x86_64 #1 SMP Wed May 7 14:14:17 CDT 2014 x86_64 x86_64 x86_64 GNU/Linux
Dir            : /home/zxb0111/seminar
Training events: 35264
Analysis type  : [Classification]


#OPT -*-*-*-*-*-*-*-*-*-*-*-*- options -*-*-*-*-*-*-*-*-*-*-*-*-

# Set by User:
NCycles: "600" [Number of training cycles]
HiddenLayers: "N+7,N+7" [Specification of hidden layer architecture]
NeuronType: "sigmoid" [Neuron activation function type]
VarTransform: "N" [List of variable transformations performed before training, e.g., "D_Background,P_Signal,G,N_AllClasses" for: "Decorrelation, PCA-transformation, Gaussianisation, Normalisation, each for the given class of events ('AllClasses' denotes all events of all classes, if no class indication is given, 'All' is assumed)"]
TrainingMethod: "BP" [Train with Back-Propagation (BP), BFGS Algorithm (BFGS), or Genetic Algorithm (GA - slower and worse)]
TestRate: "5" [Test for overtraining performed at each #th epochs]
UseRegulator: "False" [Use regulator to avoid over-training]
# Default:
RandomSeed: "1" [Random seed for initial synapse weights (0 means unique seed for each run; default value '1')]
EstimatorType: "MSE" [MSE (Mean Square Estimator) for Gaussian Likelihood or CE(Cross-Entropy) for Bernoulli Likelihood]
NeuronInputType: "sum" [Neuron input function type]
V: "False" [Verbose output (short form of "VerbosityLevel" below - overrides the latter one)]
VerbosityLevel: "Default" [Verbosity level]
H: "False" [Print method-specific help message]
CreateMVAPdfs: "False" [Create PDFs for classifier outputs (signal and background)]
IgnoreNegWeightsInTraining: "False" [Events with negative weights are ignored in the training (but are included for testing and performance evaluation)]
LearningRate: "2.000000e-02" [ANN learning rate parameter]
DecayRate: "1.000000e-02" [Decay rate for learning parameter]
EpochMonitoring: "False" [Provide epoch-wise monitoring plots according to TestRate (caution: causes big ROOT output file!)]
Sampling: "1.000000e+00" [Only 'Sampling' (randomly selected) events are trained each epoch]
SamplingEpoch: "1.000000e+00" [Sampling is used for the first 'SamplingEpoch' epochs, afterwards, all events are taken for training]
SamplingImportance: "1.000000e+00" [ The sampling weights of events in epochs which successful (worse estimator than before) are multiplied with SamplingImportance, else they are divided.]
SamplingTraining: "True" [The training sample is sampled]
SamplingTesting: "False" [The testing sample is sampled]
ResetStep: "50" [How often BFGS should reset history]
Tau: "3.000000e+00" [LineSearch "size step"]
BPMode: "sequential" [Back-propagation learning mode: sequential or batch]
BatchSize: "-1" [Batch size: number of events/batch, only set if in Batch Mode, -1 for BatchSize=number_of_events]
ConvergenceImprove: "1.000000e-30" [Minimum improvement which counts as improvement (<0 means automatic convergence check is turned off)]
ConvergenceTests: "-1" [Number of steps (without improvement) required for convergence (<0 means automatic convergence check is turned off)]
UpdateLimit: "10000" [Maximum times of regulator update]
CalculateErrors: "False" [Calculates inverse Hessian matrix at the end of the training to be able to calculate the uncertainties of an MVA value]
WeightRange: "1.000000e+00" [Take the events for the estimator calculations from small deviations from the desired value to large deviations only over the weight range]
##


#VAR -*-*-*-*-*-*-*-*-*-*-*-* variables *-*-*-*-*-*-*-*-*-*-*-*-

NVar 8
Jet.PT                        Jet.PT                        Jet.PT                        Jet.PT                                                          'F'    [4.73000001907,2147.32006836]
Jet.Eta                       Jet.Eta                       Jet.Eta                       Jet.Eta                                                         'F'    [-3.99399995804,3.99799990654]
Jet.Phi                       Jet.Phi                       Jet.Phi                       Jet.Phi                                                         'F'    [0,6.28299999237]
Jet.Mass                      Jet.Mass                      Jet.Mass                      Jet.Mass                                                        'F'    [0,251.460006714]
Jet.Ntrk                      Jet.Ntrk                      Jet.Ntrk                      Jet.Ntrk                                                        'F'    [0,77]
Jet.EhadOverEem               Jet.EhadOverEem               Jet.EhadOverEem               Jet.EhadOverEem                                                 'F'    [0,999]
MissingET.Phi                 MissingET.Phi                 MissingET.Phi                 MissingET.Phi                                                   'F'    [0,6.28299999237]
MissingET.MET                 MissingET.MET                 MissingET.MET                 MissingET.MET                                                   'F'    [3.57999992371,1585.47998047]
NSpec 0


============================================================================ */

#include <vector>
#include <cmath>
#include <string>
#include <iostream>

#ifndef IClassifierReader__def
#define IClassifierReader__def

class IClassifierReader {

 public:

   // constructor
   IClassifierReader() : fStatusIsClean( true ) {}
   virtual ~IClassifierReader() {}

   // return classifier response
   virtual double GetMvaValue( const std::vector<double>& inputValues ) const = 0;

   // returns classifier status
   bool IsStatusClean() const { return fStatusIsClean; }

 protected:

   bool fStatusIsClean;
};

#endif

class ReadMLP2-BP : public IClassifierReader {

 public:

   // constructor
   ReadMLP2-BP( std::vector<std::string>& theInputVars ) 
      : IClassifierReader(),
        fClassName( "ReadMLP2-BP" ),
        fNvars( 8 ),
        fIsNormalised( false )
   {      
      // the training input variables
      const char* inputVars[] = { "Jet.PT", "Jet.Eta", "Jet.Phi", "Jet.Mass", "Jet.Ntrk", "Jet.EhadOverEem", "MissingET.Phi", "MissingET.MET" };

      // sanity checks
      if (theInputVars.size() <= 0) {
         std::cout << "Problem in class \"" << fClassName << "\": empty input vector" << std::endl;
         fStatusIsClean = false;
      }

      if (theInputVars.size() != fNvars) {
         std::cout << "Problem in class \"" << fClassName << "\": mismatch in number of input values: "
                   << theInputVars.size() << " != " << fNvars << std::endl;
         fStatusIsClean = false;
      }

      // validate input variables
      for (size_t ivar = 0; ivar < theInputVars.size(); ivar++) {
         if (theInputVars[ivar] != inputVars[ivar]) {
            std::cout << "Problem in class \"" << fClassName << "\": mismatch in input variable names" << std::endl
                      << " for variable [" << ivar << "]: " << theInputVars[ivar].c_str() << " != " << inputVars[ivar] << std::endl;
            fStatusIsClean = false;
         }
      }

      // initialize min and max vectors (for normalisation)
      fVmin[0] = -1;
      fVmax[0] = 1;
      fVmin[1] = -1;
      fVmax[1] = 0.99999988079071;
      fVmin[2] = -1;
      fVmax[2] = 0.99999988079071;
      fVmin[3] = -1;
      fVmax[3] = 0.99999988079071;
      fVmin[4] = -1;
      fVmax[4] = 1;
      fVmin[5] = -1;
      fVmax[5] = 1;
      fVmin[6] = -1;
      fVmax[6] = 0.99999988079071;
      fVmin[7] = -1;
      fVmax[7] = 1;

      // initialize input variable types
      fType[0] = 'F';
      fType[1] = 'F';
      fType[2] = 'F';
      fType[3] = 'F';
      fType[4] = 'F';
      fType[5] = 'F';
      fType[6] = 'F';
      fType[7] = 'F';

      // initialize constants
      Initialize();

      // initialize transformation
      InitTransform();
   }

   // destructor
   virtual ~ReadMLP2-BP() {
      Clear(); // method-specific
   }

   // the classifier response
   // "inputValues" is a vector of input values in the same order as the 
   // variables given to the constructor
   double GetMvaValue( const std::vector<double>& inputValues ) const;

 private:

   // method-specific destructor
   void Clear();

   // input variable transformation

   double fMin_1[3][8];
   double fMax_1[3][8];
   void InitTransform_1();
   void Transform_1( std::vector<double> & iv, int sigOrBgd ) const;
   void InitTransform();
   void Transform( std::vector<double> & iv, int sigOrBgd ) const;

   // common member variables
   const char* fClassName;

   const size_t fNvars;
   size_t GetNvar()           const { return fNvars; }
   char   GetType( int ivar ) const { return fType[ivar]; }

   // normalisation of input variables
   const bool fIsNormalised;
   bool IsNormalised() const { return fIsNormalised; }
   double fVmin[8];
   double fVmax[8];
   double NormVariable( double x, double xmin, double xmax ) const {
      // normalise to output range: [-1, 1]
      return 2*(x - xmin)/(xmax - xmin) - 1.0;
   }

   // type of input variable: 'F' or 'I'
   char   fType[8];

   // initialize internal variables
   void Initialize();
   double GetMvaValue__( const std::vector<double>& inputValues ) const;

   // private members (method specific)

   double ActivationFnc(double x) const;
   double OutputActivationFnc(double x) const;

   int fLayers;
   int fLayerSize[4];
   double fWeightMatrix0to1[16][9];   // weight matrix from layer 0 to 1
   double fWeightMatrix1to2[16][16];   // weight matrix from layer 1 to 2
   double fWeightMatrix2to3[1][16];   // weight matrix from layer 2 to 3

   double * fWeights[4];
};

inline void ReadMLP2-BP::Initialize()
{
   // build network structure
   fLayers = 4;
   fLayerSize[0] = 9; fWeights[0] = new double[9]; 
   fLayerSize[1] = 16; fWeights[1] = new double[16]; 
   fLayerSize[2] = 16; fWeights[2] = new double[16]; 
   fLayerSize[3] = 1; fWeights[3] = new double[1]; 
   // weight matrix from layer 0 to 1
   fWeightMatrix0to1[0][0] = -4.0404594108477;
   fWeightMatrix0to1[1][0] = 6.26507292700901;
   fWeightMatrix0to1[2][0] = 1.20864370795451;
   fWeightMatrix0to1[3][0] = 2.85319963616028;
   fWeightMatrix0to1[4][0] = -1.20106376124765;
   fWeightMatrix0to1[5][0] = -0.475566769605921;
   fWeightMatrix0to1[6][0] = 0.0937334144315791;
   fWeightMatrix0to1[7][0] = 2.25503345712842;
   fWeightMatrix0to1[8][0] = -1.22547029211618;
   fWeightMatrix0to1[9][0] = -0.820947279306149;
   fWeightMatrix0to1[10][0] = -0.38100944086236;
   fWeightMatrix0to1[11][0] = -0.750338089953271;
   fWeightMatrix0to1[12][0] = -1.09077288974236;
   fWeightMatrix0to1[13][0] = -0.254342737345528;
   fWeightMatrix0to1[14][0] = 1.47423506695697;
   fWeightMatrix0to1[0][1] = 0.251450404555493;
   fWeightMatrix0to1[1][1] = 0.126562487627021;
   fWeightMatrix0to1[2][1] = 2.46394732486753;
   fWeightMatrix0to1[3][1] = 0.0168655266092325;
   fWeightMatrix0to1[4][1] = 0.588345361019651;
   fWeightMatrix0to1[5][1] = 0.0287158644125287;
   fWeightMatrix0to1[6][1] = -0.727880688631612;
   fWeightMatrix0to1[7][1] = 0.858637904578857;
   fWeightMatrix0to1[8][1] = 1.25518407218749;
   fWeightMatrix0to1[9][1] = -0.993003313241272;
   fWeightMatrix0to1[10][1] = 0.464797417761837;
   fWeightMatrix0to1[11][1] = 0.196375337293286;
   fWeightMatrix0to1[12][1] = -0.645198290240043;
   fWeightMatrix0to1[13][1] = -0.211797630876687;
   fWeightMatrix0to1[14][1] = 0.00417330016831873;
   fWeightMatrix0to1[0][2] = 0.177825001382268;
   fWeightMatrix0to1[1][2] = -0.0786565152740983;
   fWeightMatrix0to1[2][2] = -2.66644721848737;
   fWeightMatrix0to1[3][2] = 0.605686153448911;
   fWeightMatrix0to1[4][2] = -0.179922927715567;
   fWeightMatrix0to1[5][2] = 0.0856840075332043;
   fWeightMatrix0to1[6][2] = -0.358013997381497;
   fWeightMatrix0to1[7][2] = 5.58597102374235;
   fWeightMatrix0to1[8][2] = -0.563808970937233;
   fWeightMatrix0to1[9][2] = 1.2794883094539;
   fWeightMatrix0to1[10][2] = 4.98305648201231;
   fWeightMatrix0to1[11][2] = 1.57884789197963;
   fWeightMatrix0to1[12][2] = 1.50943440650046;
   fWeightMatrix0to1[13][2] = -0.224783952552407;
   fWeightMatrix0to1[14][2] = -0.639738120472998;
   fWeightMatrix0to1[0][3] = -1.45242702345631;
   fWeightMatrix0to1[1][3] = 0.843797357913432;
   fWeightMatrix0to1[2][3] = -0.194736446908138;
   fWeightMatrix0to1[3][3] = 1.18713582545873;
   fWeightMatrix0to1[4][3] = 2.17080698556322;
   fWeightMatrix0to1[5][3] = 1.4375546596881;
   fWeightMatrix0to1[6][3] = 1.72038934893269;
   fWeightMatrix0to1[7][3] = -0.434725843669913;
   fWeightMatrix0to1[8][3] = 1.35889128140092;
   fWeightMatrix0to1[9][3] = -1.7839974681987;
   fWeightMatrix0to1[10][3] = -0.393853587040117;
   fWeightMatrix0to1[11][3] = -0.839881055507003;
   fWeightMatrix0to1[12][3] = -1.82552352407213;
   fWeightMatrix0to1[13][3] = 1.56763998880729;
   fWeightMatrix0to1[14][3] = 1.47009104353259;
   fWeightMatrix0to1[0][4] = -1.19785534678268;
   fWeightMatrix0to1[1][4] = 1.3833083626095;
   fWeightMatrix0to1[2][4] = -0.516197658433558;
   fWeightMatrix0to1[3][4] = 0.405108257000364;
   fWeightMatrix0to1[4][4] = 0.352631659465;
   fWeightMatrix0to1[5][4] = -0.371204459397378;
   fWeightMatrix0to1[6][4] = -0.518569538382013;
   fWeightMatrix0to1[7][4] = 1.18830470840642;
   fWeightMatrix0to1[8][4] = 1.14765430846518;
   fWeightMatrix0to1[9][4] = -0.689992823837395;
   fWeightMatrix0to1[10][4] = -0.63967581622414;
   fWeightMatrix0to1[11][4] = -0.361957687711377;
   fWeightMatrix0to1[12][4] = 0.40782077191476;
   fWeightMatrix0to1[13][4] = 1.31687089067519;
   fWeightMatrix0to1[14][4] = 1.06350243707734;
   fWeightMatrix0to1[0][5] = 1.23229933910982;
   fWeightMatrix0to1[1][5] = -2.80675245608383;
   fWeightMatrix0to1[2][5] = -2.65163758547379;
   fWeightMatrix0to1[3][5] = 1.52778786474424;
   fWeightMatrix0to1[4][5] = 1.39796477552067;
   fWeightMatrix0to1[5][5] = 4.23064123294114;
   fWeightMatrix0to1[6][5] = 1.25573606084603;
   fWeightMatrix0to1[7][5] = 1.22160318418208;
   fWeightMatrix0to1[8][5] = -0.647742865294814;
   fWeightMatrix0to1[9][5] = -1.06031580504688;
   fWeightMatrix0to1[10][5] = -2.61911206228898;
   fWeightMatrix0to1[11][5] = 2.84259713207751;
   fWeightMatrix0to1[12][5] = -1.78096317942887;
   fWeightMatrix0to1[13][5] = -1.22517641329319;
   fWeightMatrix0to1[14][5] = -1.66122814097709;
   fWeightMatrix0to1[0][6] = -0.178074124050975;
   fWeightMatrix0to1[1][6] = -0.0295617285186113;
   fWeightMatrix0to1[2][6] = 2.43348791872238;
   fWeightMatrix0to1[3][6] = -0.559745330882709;
   fWeightMatrix0to1[4][6] = 0.364137910414944;
   fWeightMatrix0to1[5][6] = -0.114160423898105;
   fWeightMatrix0to1[6][6] = -0.818452783005864;
   fWeightMatrix0to1[7][6] = -5.61505781166224;
   fWeightMatrix0to1[8][6] = -0.455595109197164;
   fWeightMatrix0to1[9][6] = -0.0339759748263798;
   fWeightMatrix0to1[10][6] = -5.18345243756828;
   fWeightMatrix0to1[11][6] = -1.53612969050665;
   fWeightMatrix0to1[12][6] = 0.34369121768667;
   fWeightMatrix0to1[13][6] = 1.42188541327957;
   fWeightMatrix0to1[14][6] = 0.688196694630529;
   fWeightMatrix0to1[0][7] = 2.57356698212755;
   fWeightMatrix0to1[1][7] = -5.53756968812981;
   fWeightMatrix0to1[2][7] = -0.817476551745568;
   fWeightMatrix0to1[3][7] = -1.64082207674092;
   fWeightMatrix0to1[4][7] = 0.518700310357418;
   fWeightMatrix0to1[5][7] = -13.3948542816844;
   fWeightMatrix0to1[6][7] = -0.676807890683576;
   fWeightMatrix0to1[7][7] = 1.92091201312066;
   fWeightMatrix0to1[8][7] = 0.952792745503583;
   fWeightMatrix0to1[9][7] = -1.25032132384543;
   fWeightMatrix0to1[10][7] = 1.41372117107384;
   fWeightMatrix0to1[11][7] = 0.583142712377491;
   fWeightMatrix0to1[12][7] = -1.72658484003187;
   fWeightMatrix0to1[13][7] = 0.578308197711455;
   fWeightMatrix0to1[14][7] = 0.136533213218553;
   fWeightMatrix0to1[0][8] = -2.4529368624901;
   fWeightMatrix0to1[1][8] = 0.0775424955263402;
   fWeightMatrix0to1[2][8] = 0.329977475532597;
   fWeightMatrix0to1[3][8] = 3.3949276099162;
   fWeightMatrix0to1[4][8] = 1.41049445096604;
   fWeightMatrix0to1[5][8] = -7.0442771197204;
   fWeightMatrix0to1[6][8] = -0.151079912107879;
   fWeightMatrix0to1[7][8] = -0.397297068175439;
   fWeightMatrix0to1[8][8] = -1.96620697527357;
   fWeightMatrix0to1[9][8] = 1.05014032942835;
   fWeightMatrix0to1[10][8] = 2.08228157478479;
   fWeightMatrix0to1[11][8] = -2.29809141294312;
   fWeightMatrix0to1[12][8] = 1.01815063541711;
   fWeightMatrix0to1[13][8] = -1.8536454375035;
   fWeightMatrix0to1[14][8] = -0.00415859017158984;
   // weight matrix from layer 1 to 2
   fWeightMatrix1to2[0][0] = 1.32004217216661;
   fWeightMatrix1to2[1][0] = 1.38772429483945;
   fWeightMatrix1to2[2][0] = -3.20428005771806;
   fWeightMatrix1to2[3][0] = -0.928832913903443;
   fWeightMatrix1to2[4][0] = 1.81523634589921;
   fWeightMatrix1to2[5][0] = 1.64094058937887;
   fWeightMatrix1to2[6][0] = -0.673108458372003;
   fWeightMatrix1to2[7][0] = -2.25440828668703;
   fWeightMatrix1to2[8][0] = -1.17580171152955;
   fWeightMatrix1to2[9][0] = -1.94490981040139;
   fWeightMatrix1to2[10][0] = 1.16310118278727;
   fWeightMatrix1to2[11][0] = 0.472033523730792;
   fWeightMatrix1to2[12][0] = -0.910300093817582;
   fWeightMatrix1to2[13][0] = -1.16546890739179;
   fWeightMatrix1to2[14][0] = 0.569899220141046;
   fWeightMatrix1to2[0][1] = -1.55356886509454;
   fWeightMatrix1to2[1][1] = 0.257096605982403;
   fWeightMatrix1to2[2][1] = 2.96578797259095;
   fWeightMatrix1to2[3][1] = -0.261087009323601;
   fWeightMatrix1to2[4][1] = -1.42575740193984;
   fWeightMatrix1to2[5][1] = -0.169597100293689;
   fWeightMatrix1to2[6][1] = 1.74807600353677;
   fWeightMatrix1to2[7][1] = 1.29223309485243;
   fWeightMatrix1to2[8][1] = 4.38165233556173;
   fWeightMatrix1to2[9][1] = -1.60157274852451;
   fWeightMatrix1to2[10][1] = 1.21999507028508;
   fWeightMatrix1to2[11][1] = 0.78928708772915;
   fWeightMatrix1to2[12][1] = 0.764747459720294;
   fWeightMatrix1to2[13][1] = 2.0297335714223;
   fWeightMatrix1to2[14][1] = 1.46570384723126;
   fWeightMatrix1to2[0][2] = -0.537405284532795;
   fWeightMatrix1to2[1][2] = -1.26995777502326;
   fWeightMatrix1to2[2][2] = 1.68848639021816;
   fWeightMatrix1to2[3][2] = -0.34196532890354;
   fWeightMatrix1to2[4][2] = -0.0163552007485057;
   fWeightMatrix1to2[5][2] = 1.50618657942807;
   fWeightMatrix1to2[6][2] = 0.810465349632897;
   fWeightMatrix1to2[7][2] = -0.117935515087819;
   fWeightMatrix1to2[8][2] = -0.179033360743732;
   fWeightMatrix1to2[9][2] = 1.79152276596156;
   fWeightMatrix1to2[10][2] = -2.42251366000738;
   fWeightMatrix1to2[11][2] = -0.0276405097830532;
   fWeightMatrix1to2[12][2] = 0.202248556345256;
   fWeightMatrix1to2[13][2] = -0.83965776131165;
   fWeightMatrix1to2[14][2] = -2.48302029083927;
   fWeightMatrix1to2[0][3] = -1.55079525426923;
   fWeightMatrix1to2[1][3] = 1.07589093090688;
   fWeightMatrix1to2[2][3] = 2.56905191709263;
   fWeightMatrix1to2[3][3] = -2.32616910556862;
   fWeightMatrix1to2[4][3] = -1.00521083919246;
   fWeightMatrix1to2[5][3] = -0.34942348364154;
   fWeightMatrix1to2[6][3] = 0.610610565661041;
   fWeightMatrix1to2[7][3] = 2.08503883521253;
   fWeightMatrix1to2[8][3] = -2.4338435244043;
   fWeightMatrix1to2[9][3] = -0.519123509247293;
   fWeightMatrix1to2[10][3] = -1.23285882146476;
   fWeightMatrix1to2[11][3] = 0.756024145350918;
   fWeightMatrix1to2[12][3] = 1.58816827632862;
   fWeightMatrix1to2[13][3] = -0.291261147860463;
   fWeightMatrix1to2[14][3] = 1.16827232531033;
   fWeightMatrix1to2[0][4] = -0.792574366893613;
   fWeightMatrix1to2[1][4] = -2.09545437351565;
   fWeightMatrix1to2[2][4] = 0.138564507319034;
   fWeightMatrix1to2[3][4] = -0.287985805850816;
   fWeightMatrix1to2[4][4] = -1.49490556512244;
   fWeightMatrix1to2[5][4] = -0.676838558482953;
   fWeightMatrix1to2[6][4] = -0.461045585882053;
   fWeightMatrix1to2[7][4] = -0.337357253489916;
   fWeightMatrix1to2[8][4] = -2.55240180689631;
   fWeightMatrix1to2[9][4] = 1.14120267247688;
   fWeightMatrix1to2[10][4] = 0.636420739570322;
   fWeightMatrix1to2[11][4] = -0.682269730228813;
   fWeightMatrix1to2[12][4] = 0.149527531771983;
   fWeightMatrix1to2[13][4] = 1.54434783603316;
   fWeightMatrix1to2[14][4] = 1.22373713466868;
   fWeightMatrix1to2[0][5] = 0.449767787578007;
   fWeightMatrix1to2[1][5] = -0.122155583477245;
   fWeightMatrix1to2[2][5] = -1.56469661823741;
   fWeightMatrix1to2[3][5] = -1.66615079104809;
   fWeightMatrix1to2[4][5] = 2.59617545087281;
   fWeightMatrix1to2[5][5] = 1.2297219958797;
   fWeightMatrix1to2[6][5] = 0.256258270913103;
   fWeightMatrix1to2[7][5] = 0.496203762174231;
   fWeightMatrix1to2[8][5] = 7.83061283122747;
   fWeightMatrix1to2[9][5] = -1.71927715526562;
   fWeightMatrix1to2[10][5] = -1.53928640551146;
   fWeightMatrix1to2[11][5] = -0.305204761960957;
   fWeightMatrix1to2[12][5] = -8.01366877945543;
   fWeightMatrix1to2[13][5] = 1.32099772889101;
   fWeightMatrix1to2[14][5] = 1.15866272690921;
   fWeightMatrix1to2[0][6] = -1.20794365081683;
   fWeightMatrix1to2[1][6] = 0.731752179037771;
   fWeightMatrix1to2[2][6] = 0.305467679634317;
   fWeightMatrix1to2[3][6] = -1.39001480993445;
   fWeightMatrix1to2[4][6] = -0.945410572055386;
   fWeightMatrix1to2[5][6] = 0.709179580702349;
   fWeightMatrix1to2[6][6] = -0.541594745400098;
   fWeightMatrix1to2[7][6] = 0.314255406218186;
   fWeightMatrix1to2[8][6] = -1.26535803475857;
   fWeightMatrix1to2[9][6] = 2.0521865063797;
   fWeightMatrix1to2[10][6] = -1.92378390519145;
   fWeightMatrix1to2[11][6] = 0.753378625433582;
   fWeightMatrix1to2[12][6] = 0.989484845328916;
   fWeightMatrix1to2[13][6] = -1.74176552343627;
   fWeightMatrix1to2[14][6] = -1.65800363407663;
   fWeightMatrix1to2[0][7] = -1.97079424745352;
   fWeightMatrix1to2[1][7] = -0.733880914480456;
   fWeightMatrix1to2[2][7] = -4.73276508253525;
   fWeightMatrix1to2[3][7] = -1.59805629775385;
   fWeightMatrix1to2[4][7] = -2.96801531383805;
   fWeightMatrix1to2[5][7] = 0.344886212063468;
   fWeightMatrix1to2[6][7] = -2.79033183627822;
   fWeightMatrix1to2[7][7] = -1.79450347590451;
   fWeightMatrix1to2[8][7] = 0.180669952750339;
   fWeightMatrix1to2[9][7] = -0.885019439129901;
   fWeightMatrix1to2[10][7] = 0.195158570398135;
   fWeightMatrix1to2[11][7] = -1.51990455090808;
   fWeightMatrix1to2[12][7] = -0.560308207002469;
   fWeightMatrix1to2[13][7] = 2.59961851242883;
   fWeightMatrix1to2[14][7] = 4.41373993462543;
   fWeightMatrix1to2[0][8] = -0.895331361063424;
   fWeightMatrix1to2[1][8] = -1.56733130496632;
   fWeightMatrix1to2[2][8] = -1.65665956977694;
   fWeightMatrix1to2[3][8] = -1.10604379262685;
   fWeightMatrix1to2[4][8] = -1.49985838944624;
   fWeightMatrix1to2[5][8] = 0.564109631346805;
   fWeightMatrix1to2[6][8] = 0.546795713916655;
   fWeightMatrix1to2[7][8] = 1.67831544294772;
   fWeightMatrix1to2[8][8] = -0.537262224958447;
   fWeightMatrix1to2[9][8] = 0.12057609790876;
   fWeightMatrix1to2[10][8] = -0.628921121377054;
   fWeightMatrix1to2[11][8] = -2.0679413364749;
   fWeightMatrix1to2[12][8] = 0.675597719344153;
   fWeightMatrix1to2[13][8] = 0.503968970409801;
   fWeightMatrix1to2[14][8] = -0.302247335748073;
   fWeightMatrix1to2[0][9] = -0.902162273542625;
   fWeightMatrix1to2[1][9] = 0.399732943758122;
   fWeightMatrix1to2[2][9] = -0.0218748306311212;
   fWeightMatrix1to2[3][9] = 0.667617563692366;
   fWeightMatrix1to2[4][9] = -1.24617734561308;
   fWeightMatrix1to2[5][9] = -0.737981589831154;
   fWeightMatrix1to2[6][9] = 0.877635996750597;
   fWeightMatrix1to2[7][9] = 0.977546691006977;
   fWeightMatrix1to2[8][9] = -0.186363403264293;
   fWeightMatrix1to2[9][9] = -0.589035971623135;
   fWeightMatrix1to2[10][9] = -0.46851085830089;
   fWeightMatrix1to2[11][9] = -0.686634451342078;
   fWeightMatrix1to2[12][9] = -1.1731106053874;
   fWeightMatrix1to2[13][9] = -0.73577816073048;
   fWeightMatrix1to2[14][9] = -1.76088608902971;
   fWeightMatrix1to2[0][10] = -1.44037457465552;
   fWeightMatrix1to2[1][10] = -1.86604428933872;
   fWeightMatrix1to2[2][10] = 3.91906845787306;
   fWeightMatrix1to2[3][10] = -3.11541607248555;
   fWeightMatrix1to2[4][10] = 1.07759006947664;
   fWeightMatrix1to2[5][10] = -2.44947962111209;
   fWeightMatrix1to2[6][10] = 3.24115169881308;
   fWeightMatrix1to2[7][10] = -1.87818228756358;
   fWeightMatrix1to2[8][10] = 0.384914663270577;
   fWeightMatrix1to2[9][10] = 0.0595851742958151;
   fWeightMatrix1to2[10][10] = -2.40920707900118;
   fWeightMatrix1to2[11][10] = 0.256955612894895;
   fWeightMatrix1to2[12][10] = 1.26203516507461;
   fWeightMatrix1to2[13][10] = -4.08408765761408;
   fWeightMatrix1to2[14][10] = -2.10773044070332;
   fWeightMatrix1to2[0][11] = -1.75170932816007;
   fWeightMatrix1to2[1][11] = -0.834457490857648;
   fWeightMatrix1to2[2][11] = 0.80168041131076;
   fWeightMatrix1to2[3][11] = -0.558484735304278;
   fWeightMatrix1to2[4][11] = 0.090453229675211;
   fWeightMatrix1to2[5][11] = -0.930068459007774;
   fWeightMatrix1to2[6][11] = -2.0219543936377;
   fWeightMatrix1to2[7][11] = -1.64008161512975;
   fWeightMatrix1to2[8][11] = -1.81300756032279;
   fWeightMatrix1to2[9][11] = -1.40948394012803;
   fWeightMatrix1to2[10][11] = 0.886300786431204;
   fWeightMatrix1to2[11][11] = -1.35219221380901;
   fWeightMatrix1to2[12][11] = 0.602465177113582;
   fWeightMatrix1to2[13][11] = 1.2931932518557;
   fWeightMatrix1to2[14][11] = 1.38385321717009;
   fWeightMatrix1to2[0][12] = -0.334182363924269;
   fWeightMatrix1to2[1][12] = 1.45294510769086;
   fWeightMatrix1to2[2][12] = -3.13040913633213;
   fWeightMatrix1to2[3][12] = 1.46482751095389;
   fWeightMatrix1to2[4][12] = 0.0978756948195922;
   fWeightMatrix1to2[5][12] = -1.40836966492462;
   fWeightMatrix1to2[6][12] = -1.23702922806525;
   fWeightMatrix1to2[7][12] = -0.0135952005626534;
   fWeightMatrix1to2[8][12] = -2.34623101474906;
   fWeightMatrix1to2[9][12] = 0.149187430397828;
   fWeightMatrix1to2[10][12] = 1.21994094388609;
   fWeightMatrix1to2[11][12] = 0.92662819792647;
   fWeightMatrix1to2[12][12] = 1.70396768119587;
   fWeightMatrix1to2[13][12] = -1.64013296460736;
   fWeightMatrix1to2[14][12] = 1.09367828314778;
   fWeightMatrix1to2[0][13] = -1.84266212782343;
   fWeightMatrix1to2[1][13] = 0.520515622416247;
   fWeightMatrix1to2[2][13] = -1.06388575511135;
   fWeightMatrix1to2[3][13] = -1.85684797174515;
   fWeightMatrix1to2[4][13] = -0.826608697201242;
   fWeightMatrix1to2[5][13] = 1.13062033429413;
   fWeightMatrix1to2[6][13] = -0.123019288813523;
   fWeightMatrix1to2[7][13] = 0.455096966031742;
   fWeightMatrix1to2[8][13] = -0.318580580145613;
   fWeightMatrix1to2[9][13] = -0.216454537400996;
   fWeightMatrix1to2[10][13] = -0.867872388220212;
   fWeightMatrix1to2[11][13] = 0.284969455482985;
   fWeightMatrix1to2[12][13] = 1.59667324701723;
   fWeightMatrix1to2[13][13] = -1.24879536828626;
   fWeightMatrix1to2[14][13] = -0.359969192800877;
   fWeightMatrix1to2[0][14] = -1.37733958720283;
   fWeightMatrix1to2[1][14] = -0.903036048780466;
   fWeightMatrix1to2[2][14] = -0.00762475082551806;
   fWeightMatrix1to2[3][14] = 0.420971509923224;
   fWeightMatrix1to2[4][14] = -1.85961135758141;
   fWeightMatrix1to2[5][14] = 0.810465007381849;
   fWeightMatrix1to2[6][14] = 0.292534855167166;
   fWeightMatrix1to2[7][14] = 0.191198536957805;
   fWeightMatrix1to2[8][14] = -0.472899273540809;
   fWeightMatrix1to2[9][14] = -0.864501618694954;
   fWeightMatrix1to2[10][14] = -1.86686740684192;
   fWeightMatrix1to2[11][14] = -2.05225183257552;
   fWeightMatrix1to2[12][14] = 1.44600180415244;
   fWeightMatrix1to2[13][14] = -1.21399047034719;
   fWeightMatrix1to2[14][14] = -1.27918168318517;
   fWeightMatrix1to2[0][15] = 0.678501315038826;
   fWeightMatrix1to2[1][15] = -2.20637112439304;
   fWeightMatrix1to2[2][15] = -2.38342223895047;
   fWeightMatrix1to2[3][15] = -1.42030175286668;
   fWeightMatrix1to2[4][15] = 0.231968556475844;
   fWeightMatrix1to2[5][15] = -1.74713707548969;
   fWeightMatrix1to2[6][15] = -2.4103118287366;
   fWeightMatrix1to2[7][15] = -0.63038148198369;
   fWeightMatrix1to2[8][15] = -2.24387854180505;
   fWeightMatrix1to2[9][15] = -1.95808909520689;
   fWeightMatrix1to2[10][15] = 0.533136980648911;
   fWeightMatrix1to2[11][15] = -1.87365814195881;
   fWeightMatrix1to2[12][15] = -0.988374589164641;
   fWeightMatrix1to2[13][15] = 1.37643627231458;
   fWeightMatrix1to2[14][15] = 0.539676960451544;
   // weight matrix from layer 2 to 3
   fWeightMatrix2to3[0][0] = -0.798795952104742;
   fWeightMatrix2to3[0][1] = -0.710832168439968;
   fWeightMatrix2to3[0][2] = 0.978729273415323;
   fWeightMatrix2to3[0][3] = 1.64409166294028;
   fWeightMatrix2to3[0][4] = 0.84576105216037;
   fWeightMatrix2to3[0][5] = -0.936760051103926;
   fWeightMatrix2to3[0][6] = -1.22233726639989;
   fWeightMatrix2to3[0][7] = -0.835609577497647;
   fWeightMatrix2to3[0][8] = 1.82448708396997;
   fWeightMatrix2to3[0][9] = 0.558167154885613;
   fWeightMatrix2to3[0][10] = 0.524295235624192;
   fWeightMatrix2to3[0][11] = -0.788985737764281;
   fWeightMatrix2to3[0][12] = 1.71313477037686;
   fWeightMatrix2to3[0][13] = 1.64269096786696;
   fWeightMatrix2to3[0][14] = -0.370308721445274;
   fWeightMatrix2to3[0][15] = 0.164683902087991;
}

inline double ReadMLP2-BP::GetMvaValue__( const std::vector<double>& inputValues ) const
{
   if (inputValues.size() != (unsigned int)fLayerSize[0]-1) {
      std::cout << "Input vector needs to be of size " << fLayerSize[0]-1 << std::endl;
      return 0;
   }

   for (int l=0; l<fLayers; l++)
      for (int i=0; i<fLayerSize[l]; i++) fWeights[l][i]=0;

   for (int l=0; l<fLayers-1; l++)
      fWeights[l][fLayerSize[l]-1]=1;

   for (int i=0; i<fLayerSize[0]-1; i++)
      fWeights[0][i]=inputValues[i];

   // layer 0 to 1
   for (int o=0; o<fLayerSize[1]-1; o++) {
      for (int i=0; i<fLayerSize[0]; i++) {
         double inputVal = fWeightMatrix0to1[o][i] * fWeights[0][i];
         fWeights[1][o] += inputVal;
      }
      fWeights[1][o] = ActivationFnc(fWeights[1][o]);
   }
   // layer 1 to 2
   for (int o=0; o<fLayerSize[2]-1; o++) {
      for (int i=0; i<fLayerSize[1]; i++) {
         double inputVal = fWeightMatrix1to2[o][i] * fWeights[1][i];
         fWeights[2][o] += inputVal;
      }
      fWeights[2][o] = ActivationFnc(fWeights[2][o]);
   }
   // layer 2 to 3
   for (int o=0; o<fLayerSize[3]; o++) {
      for (int i=0; i<fLayerSize[2]; i++) {
         double inputVal = fWeightMatrix2to3[o][i] * fWeights[2][i];
         fWeights[3][o] += inputVal;
      }
      fWeights[3][o] = OutputActivationFnc(fWeights[3][o]);
   }

   return fWeights[3][0];
}

double ReadMLP2-BP::ActivationFnc(double x) const {
   // sigmoid
   return 1.0/(1.0+exp(-x));
}
double ReadMLP2-BP::OutputActivationFnc(double x) const {
   // identity
   return x;
}
   
// Clean up
inline void ReadMLP2-BP::Clear() 
{
   // clean up the arrays
   for (int lIdx = 0; lIdx < 4; lIdx++) {
      delete[] fWeights[lIdx];
   }
}
   inline double ReadMLP2-BP::GetMvaValue( const std::vector<double>& inputValues ) const
   {
      // classifier response value
      double retval = 0;

      // classifier response, sanity check first
      if (!IsStatusClean()) {
         std::cout << "Problem in class \"" << fClassName << "\": cannot return classifier response"
                   << " because status is dirty" << std::endl;
         retval = 0;
      }
      else {
         if (IsNormalised()) {
            // normalise variables
            std::vector<double> iV;
            iV.reserve(inputValues.size());
            int ivar = 0;
            for (std::vector<double>::const_iterator varIt = inputValues.begin();
                 varIt != inputValues.end(); varIt++, ivar++) {
               iV.push_back(NormVariable( *varIt, fVmin[ivar], fVmax[ivar] ));
            }
            Transform( iV, -1 );
            retval = GetMvaValue__( iV );
         }
         else {
            std::vector<double> iV;
            int ivar = 0;
            for (std::vector<double>::const_iterator varIt = inputValues.begin();
                 varIt != inputValues.end(); varIt++, ivar++) {
               iV.push_back(*varIt);
            }
            Transform( iV, -1 );
            retval = GetMvaValue__( iV );
         }
      }

      return retval;
   }

//_______________________________________________________________________
inline void ReadMLP2-BP::InitTransform_1()
{
   // Normalization transformation, initialisation
   fMin_1[0][0] = 5;
   fMax_1[0][0] = 2147.32006836;
   fMin_1[1][0] = 4.73000001907;
   fMax_1[1][0] = 817.520019531;
   fMin_1[2][0] = 4.73000001907;
   fMax_1[2][0] = 2147.32006836;
   fMin_1[0][1] = -3.98099994659;
   fMax_1[0][1] = 3.99799990654;
   fMin_1[1][1] = -3.99399995804;
   fMax_1[1][1] = 3.99699997902;
   fMin_1[2][1] = -3.99399995804;
   fMax_1[2][1] = 3.99799990654;
   fMin_1[0][2] = 0;
   fMax_1[0][2] = 6.28299999237;
   fMin_1[1][2] = 0;
   fMax_1[1][2] = 6.28299999237;
   fMin_1[2][2] = 0;
   fMax_1[2][2] = 6.28299999237;
   fMin_1[0][3] = 0;
   fMax_1[0][3] = 251.460006714;
   fMin_1[1][3] = 0;
   fMax_1[1][3] = 184.169998169;
   fMin_1[2][3] = 0;
   fMax_1[2][3] = 251.460006714;
   fMin_1[0][4] = 0;
   fMax_1[0][4] = 60;
   fMin_1[1][4] = 0;
   fMax_1[1][4] = 77;
   fMin_1[2][4] = 0;
   fMax_1[2][4] = 77;
   fMin_1[0][5] = 0;
   fMax_1[0][5] = 999;
   fMin_1[1][5] = 0;
   fMax_1[1][5] = 999;
   fMin_1[2][5] = 0;
   fMax_1[2][5] = 999;
   fMin_1[0][6] = 0;
   fMax_1[0][6] = 6.28299999237;
   fMin_1[1][6] = 0.0010000000475;
   fMax_1[1][6] = 6.28200006485;
   fMin_1[2][6] = 0;
   fMax_1[2][6] = 6.28299999237;
   fMin_1[0][7] = 3.57999992371;
   fMax_1[0][7] = 1585.47998047;
   fMin_1[1][7] = 100.010002136;
   fMax_1[1][7] = 662.650024414;
   fMin_1[2][7] = 3.57999992371;
   fMax_1[2][7] = 1585.47998047;
}

//_______________________________________________________________________
inline void ReadMLP2-BP::Transform_1( std::vector<double>& iv, int cls) const
{
   // Normalization transformation
   if (cls < 0 || cls > 2) {
   if (2 > 1 ) cls = 2;
      else cls = 2;
   }
   const int nVar = 8;

   // get indices of used variables

   // define the indices of the variables which are transformed by this transformation
   static std::vector<int> indicesGet;
   static std::vector<int> indicesPut;

   if ( indicesGet.empty() ) { 
      indicesGet.reserve(fNvars);
      indicesGet.push_back( 0);
      indicesGet.push_back( 1);
      indicesGet.push_back( 2);
      indicesGet.push_back( 3);
      indicesGet.push_back( 4);
      indicesGet.push_back( 5);
      indicesGet.push_back( 6);
      indicesGet.push_back( 7);
   } 
   if ( indicesPut.empty() ) { 
      indicesPut.reserve(fNvars);
      indicesPut.push_back( 0);
      indicesPut.push_back( 1);
      indicesPut.push_back( 2);
      indicesPut.push_back( 3);
      indicesPut.push_back( 4);
      indicesPut.push_back( 5);
      indicesPut.push_back( 6);
      indicesPut.push_back( 7);
   } 

   static std::vector<double> dv;
   dv.resize(nVar);
   for (int ivar=0; ivar<nVar; ivar++) dv[ivar] = iv[indicesGet.at(ivar)];
   for (int ivar=0;ivar<8;ivar++) {
      double offset = fMin_1[cls][ivar];
      double scale  = 1.0/(fMax_1[cls][ivar]-fMin_1[cls][ivar]);
      iv[indicesPut.at(ivar)] = (dv[ivar]-offset)*scale * 2 - 1;
   }
}

//_______________________________________________________________________
inline void ReadMLP2-BP::InitTransform()
{
   InitTransform_1();
}

//_______________________________________________________________________
inline void ReadMLP2-BP::Transform( std::vector<double>& iv, int sigOrBgd ) const
{
   Transform_1( iv, sigOrBgd );
}
