// Class: Read3Layers24Decrease
// Automatically generated by MethodBase::MakeClass
//

/* configuration options =====================================================

#GEN -*-*-*-*-*-*-*-*-*-*-*- general info -*-*-*-*-*-*-*-*-*-*-*-

Method         : MLP::3Layers24Decrease
TMVA Release   : 4.2.0         [262656]
ROOT Release   : 5.34/18       [336402]
Creator        : zxb0111
Date           : Sat Dec  6 23:01:58 2014
Host           : Linux localhost.localdomain 2.6.32-431.17.1.el6.x86_64 #1 SMP Wed May 7 14:14:17 CDT 2014 x86_64 x86_64 x86_64 GNU/Linux
Dir            : /home/zxb0111/seminar
Training events: 34086
Analysis type  : [Classification]


#OPT -*-*-*-*-*-*-*-*-*-*-*-*- options -*-*-*-*-*-*-*-*-*-*-*-*-

# Set by User:
NCycles: "600" [Number of training cycles]
HiddenLayers: "11,8,5" [Specification of hidden layer architecture]
NeuronType: "sigmoid" [Neuron activation function type]
VarTransform: "N" [List of variable transformations performed before training, e.g., "D_Background,P_Signal,G,N_AllClasses" for: "Decorrelation, PCA-transformation, Gaussianisation, Normalisation, each for the given class of events ('AllClasses' denotes all events of all classes, if no class indication is given, 'All' is assumed)"]
TestRate: "5" [Test for overtraining performed at each #th epochs]
UseRegulator: "False" [Use regulator to avoid over-training]
# Default:
RandomSeed: "1" [Random seed for initial synapse weights (0 means unique seed for each run; default value '1')]
EstimatorType: "MSE" [MSE (Mean Square Estimator) for Gaussian Likelihood or CE(Cross-Entropy) for Bernoulli Likelihood]
NeuronInputType: "sum" [Neuron input function type]
V: "False" [Verbose output (short form of "VerbosityLevel" below - overrides the latter one)]
VerbosityLevel: "Default" [Verbosity level]
H: "False" [Print method-specific help message]
CreateMVAPdfs: "False" [Create PDFs for classifier outputs (signal and background)]
IgnoreNegWeightsInTraining: "False" [Events with negative weights are ignored in the training (but are included for testing and performance evaluation)]
TrainingMethod: "BP" [Train with Back-Propagation (BP), BFGS Algorithm (BFGS), or Genetic Algorithm (GA - slower and worse)]
LearningRate: "2.000000e-02" [ANN learning rate parameter]
DecayRate: "1.000000e-02" [Decay rate for learning parameter]
EpochMonitoring: "False" [Provide epoch-wise monitoring plots according to TestRate (caution: causes big ROOT output file!)]
Sampling: "1.000000e+00" [Only 'Sampling' (randomly selected) events are trained each epoch]
SamplingEpoch: "1.000000e+00" [Sampling is used for the first 'SamplingEpoch' epochs, afterwards, all events are taken for training]
SamplingImportance: "1.000000e+00" [ The sampling weights of events in epochs which successful (worse estimator than before) are multiplied with SamplingImportance, else they are divided.]
SamplingTraining: "True" [The training sample is sampled]
SamplingTesting: "False" [The testing sample is sampled]
ResetStep: "50" [How often BFGS should reset history]
Tau: "3.000000e+00" [LineSearch "size step"]
BPMode: "sequential" [Back-propagation learning mode: sequential or batch]
BatchSize: "-1" [Batch size: number of events/batch, only set if in Batch Mode, -1 for BatchSize=number_of_events]
ConvergenceImprove: "1.000000e-30" [Minimum improvement which counts as improvement (<0 means automatic convergence check is turned off)]
ConvergenceTests: "-1" [Number of steps (without improvement) required for convergence (<0 means automatic convergence check is turned off)]
UpdateLimit: "10000" [Maximum times of regulator update]
CalculateErrors: "False" [Calculates inverse Hessian matrix at the end of the training to be able to calculate the uncertainties of an MVA value]
WeightRange: "1.000000e+00" [Take the events for the estimator calculations from small deviations from the desired value to large deviations only over the weight range]
##


#VAR -*-*-*-*-*-*-*-*-*-*-*-* variables *-*-*-*-*-*-*-*-*-*-*-*-

NVar 8
Jet.PT                        Jet.PT                        Jet.PT                        Jet.PT                                                          'F'    [4.73000001907,2543.40991211]
Jet.Eta                       Jet.Eta                       Jet.Eta                       Jet.Eta                                                         'F'    [-3.99300003052,3.99099993706]
Jet.Phi                       Jet.Phi                       Jet.Phi                       Jet.Phi                                                         'F'    [0,6.28299999237]
Jet.Mass                      Jet.Mass                      Jet.Mass                      Jet.Mass                                                        'F'    [0,258.730010986]
Jet.Ntrk                      Jet.Ntrk                      Jet.Ntrk                      Jet.Ntrk                                                        'F'    [0,61]
Jet.EhadOverEem               Jet.EhadOverEem               Jet.EhadOverEem               Jet.EhadOverEem                                                 'F'    [0,999]
MissingET.Phi                 MissingET.Phi                 MissingET.Phi                 MissingET.Phi                                                   'F'    [0,6.28299999237]
MissingET.MET                 MissingET.MET                 MissingET.MET                 MissingET.MET                                                   'F'    [100.010002136,1585.47998047]
NSpec 0


============================================================================ */

#include <vector>
#include <cmath>
#include <string>
#include <iostream>

#ifndef IClassifierReader__def
#define IClassifierReader__def

class IClassifierReader {

 public:

   // constructor
   IClassifierReader() : fStatusIsClean( true ) {}
   virtual ~IClassifierReader() {}

   // return classifier response
   virtual double GetMvaValue( const std::vector<double>& inputValues ) const = 0;

   // returns classifier status
   bool IsStatusClean() const { return fStatusIsClean; }

 protected:

   bool fStatusIsClean;
};

#endif

class Read3Layers24Decrease : public IClassifierReader {

 public:

   // constructor
   Read3Layers24Decrease( std::vector<std::string>& theInputVars ) 
      : IClassifierReader(),
        fClassName( "Read3Layers24Decrease" ),
        fNvars( 8 ),
        fIsNormalised( false )
   {      
      // the training input variables
      const char* inputVars[] = { "Jet.PT", "Jet.Eta", "Jet.Phi", "Jet.Mass", "Jet.Ntrk", "Jet.EhadOverEem", "MissingET.Phi", "MissingET.MET" };

      // sanity checks
      if (theInputVars.size() <= 0) {
         std::cout << "Problem in class \"" << fClassName << "\": empty input vector" << std::endl;
         fStatusIsClean = false;
      }

      if (theInputVars.size() != fNvars) {
         std::cout << "Problem in class \"" << fClassName << "\": mismatch in number of input values: "
                   << theInputVars.size() << " != " << fNvars << std::endl;
         fStatusIsClean = false;
      }

      // validate input variables
      for (size_t ivar = 0; ivar < theInputVars.size(); ivar++) {
         if (theInputVars[ivar] != inputVars[ivar]) {
            std::cout << "Problem in class \"" << fClassName << "\": mismatch in input variable names" << std::endl
                      << " for variable [" << ivar << "]: " << theInputVars[ivar].c_str() << " != " << inputVars[ivar] << std::endl;
            fStatusIsClean = false;
         }
      }

      // initialize min and max vectors (for normalisation)
      fVmin[0] = -1;
      fVmax[0] = 1;
      fVmin[1] = -1;
      fVmax[1] = 1;
      fVmin[2] = -1;
      fVmax[2] = 0.99999988079071;
      fVmin[3] = -1;
      fVmax[3] = 1;
      fVmin[4] = -1;
      fVmax[4] = 0.99999988079071;
      fVmin[5] = -1;
      fVmax[5] = 1;
      fVmin[6] = -1;
      fVmax[6] = 0.99999988079071;
      fVmin[7] = -1;
      fVmax[7] = 1;

      // initialize input variable types
      fType[0] = 'F';
      fType[1] = 'F';
      fType[2] = 'F';
      fType[3] = 'F';
      fType[4] = 'F';
      fType[5] = 'F';
      fType[6] = 'F';
      fType[7] = 'F';

      // initialize constants
      Initialize();

      // initialize transformation
      InitTransform();
   }

   // destructor
   virtual ~Read3Layers24Decrease() {
      Clear(); // method-specific
   }

   // the classifier response
   // "inputValues" is a vector of input values in the same order as the 
   // variables given to the constructor
   double GetMvaValue( const std::vector<double>& inputValues ) const;

 private:

   // method-specific destructor
   void Clear();

   // input variable transformation

   double fMin_1[3][8];
   double fMax_1[3][8];
   void InitTransform_1();
   void Transform_1( std::vector<double> & iv, int sigOrBgd ) const;
   void InitTransform();
   void Transform( std::vector<double> & iv, int sigOrBgd ) const;

   // common member variables
   const char* fClassName;

   const size_t fNvars;
   size_t GetNvar()           const { return fNvars; }
   char   GetType( int ivar ) const { return fType[ivar]; }

   // normalisation of input variables
   const bool fIsNormalised;
   bool IsNormalised() const { return fIsNormalised; }
   double fVmin[8];
   double fVmax[8];
   double NormVariable( double x, double xmin, double xmax ) const {
      // normalise to output range: [-1, 1]
      return 2*(x - xmin)/(xmax - xmin) - 1.0;
   }

   // type of input variable: 'F' or 'I'
   char   fType[8];

   // initialize internal variables
   void Initialize();
   double GetMvaValue__( const std::vector<double>& inputValues ) const;

   // private members (method specific)

   double ActivationFnc(double x) const;
   double OutputActivationFnc(double x) const;

   int fLayers;
   int fLayerSize[5];
   double fWeightMatrix0to1[12][9];   // weight matrix from layer 0 to 1
   double fWeightMatrix1to2[9][12];   // weight matrix from layer 1 to 2
   double fWeightMatrix2to3[6][9];   // weight matrix from layer 2 to 3
   double fWeightMatrix3to4[1][6];   // weight matrix from layer 3 to 4

   double * fWeights[5];
};

inline void Read3Layers24Decrease::Initialize()
{
   // build network structure
   fLayers = 5;
   fLayerSize[0] = 9; fWeights[0] = new double[9]; 
   fLayerSize[1] = 12; fWeights[1] = new double[12]; 
   fLayerSize[2] = 9; fWeights[2] = new double[9]; 
   fLayerSize[3] = 6; fWeights[3] = new double[6]; 
   fLayerSize[4] = 1; fWeights[4] = new double[1]; 
   // weight matrix from layer 0 to 1
   fWeightMatrix0to1[0][0] = -0.43404734551472;
   fWeightMatrix0to1[1][0] = 1.53945074717984;
   fWeightMatrix0to1[2][0] = 2.91147122469393;
   fWeightMatrix0to1[3][0] = 0.284413631618618;
   fWeightMatrix0to1[4][0] = -1.97702846955958;
   fWeightMatrix0to1[5][0] = -4.32593670555758;
   fWeightMatrix0to1[6][0] = -2.16461472236819;
   fWeightMatrix0to1[7][0] = 6.34301831409874;
   fWeightMatrix0to1[8][0] = -1.99199421062883;
   fWeightMatrix0to1[9][0] = -0.988238956845448;
   fWeightMatrix0to1[10][0] = -1.20521530851193;
   fWeightMatrix0to1[0][1] = -0.096355062881739;
   fWeightMatrix0to1[1][1] = -0.383285706006019;
   fWeightMatrix0to1[2][1] = 0.231204699193526;
   fWeightMatrix0to1[3][1] = -0.189793938999106;
   fWeightMatrix0to1[4][1] = 1.3854558115653;
   fWeightMatrix0to1[5][1] = -0.284817925109951;
   fWeightMatrix0to1[6][1] = 0.0837923766909578;
   fWeightMatrix0to1[7][1] = -0.0401679243495918;
   fWeightMatrix0to1[8][1] = 2.1385250830482;
   fWeightMatrix0to1[9][1] = -0.247425912205436;
   fWeightMatrix0to1[10][1] = 0.148055593895607;
   fWeightMatrix0to1[0][2] = 1.6833855593596;
   fWeightMatrix0to1[1][2] = 1.11694709829801;
   fWeightMatrix0to1[2][2] = -3.16525572706908;
   fWeightMatrix0to1[3][2] = 1.59711869728045;
   fWeightMatrix0to1[4][2] = 0.895529036567839;
   fWeightMatrix0to1[5][2] = 0.28223514161148;
   fWeightMatrix0to1[6][2] = -3.55844878893484;
   fWeightMatrix0to1[7][2] = 0.093398574885014;
   fWeightMatrix0to1[8][2] = 0.487642605856801;
   fWeightMatrix0to1[9][2] = 1.64901416891827;
   fWeightMatrix0to1[10][2] = 1.81077587818743;
   fWeightMatrix0to1[0][3] = 0.413417939477255;
   fWeightMatrix0to1[1][3] = 0.246482753340372;
   fWeightMatrix0to1[2][3] = 0.825216954803822;
   fWeightMatrix0to1[3][3] = -1.75039345854345;
   fWeightMatrix0to1[4][3] = 1.73465078724866;
   fWeightMatrix0to1[5][3] = -1.68094389480454;
   fWeightMatrix0to1[6][3] = 0.0927370759447407;
   fWeightMatrix0to1[7][3] = 2.20289000798474;
   fWeightMatrix0to1[8][3] = 0.5271150109492;
   fWeightMatrix0to1[9][3] = 1.90669156297493;
   fWeightMatrix0to1[10][3] = 1.36005813244159;
   fWeightMatrix0to1[0][4] = -0.169807229796967;
   fWeightMatrix0to1[1][4] = -2.12707507266887;
   fWeightMatrix0to1[2][4] = 0.773131783837426;
   fWeightMatrix0to1[3][4] = 0.437260849867987;
   fWeightMatrix0to1[4][4] = 1.49983993244487;
   fWeightMatrix0to1[5][4] = 0.895717491680331;
   fWeightMatrix0to1[6][4] = -0.522224283605549;
   fWeightMatrix0to1[7][4] = 0.242331299931331;
   fWeightMatrix0to1[8][4] = -1.45542160829044;
   fWeightMatrix0to1[9][4] = 1.35559164111726;
   fWeightMatrix0to1[10][4] = 0.600709020224488;
   fWeightMatrix0to1[0][5] = -1.49210253764625;
   fWeightMatrix0to1[1][5] = -1.8921941929925;
   fWeightMatrix0to1[2][5] = -3.1487943463531;
   fWeightMatrix0to1[3][5] = 2.41510199463271;
   fWeightMatrix0to1[4][5] = 0.693824070160504;
   fWeightMatrix0to1[5][5] = -0.963750251137172;
   fWeightMatrix0to1[6][5] = 1.27821002022995;
   fWeightMatrix0to1[7][5] = -0.864901351797823;
   fWeightMatrix0to1[8][5] = 0.4268230654236;
   fWeightMatrix0to1[9][5] = 1.83980796685383;
   fWeightMatrix0to1[10][5] = -0.367834861660386;
   fWeightMatrix0to1[0][6] = -1.72392734680859;
   fWeightMatrix0to1[1][6] = -1.38490816293449;
   fWeightMatrix0to1[2][6] = 3.21471084539386;
   fWeightMatrix0to1[3][6] = -1.82323878948528;
   fWeightMatrix0to1[4][6] = -0.88160138669379;
   fWeightMatrix0to1[5][6] = -0.104776208943848;
   fWeightMatrix0to1[6][6] = 3.62464794037662;
   fWeightMatrix0to1[7][6] = -0.338251178142349;
   fWeightMatrix0to1[8][6] = 0.436275695238487;
   fWeightMatrix0to1[9][6] = -0.382582440330637;
   fWeightMatrix0to1[10][6] = -1.65665056363131;
   fWeightMatrix0to1[0][7] = -5.48754491986039;
   fWeightMatrix0to1[1][7] = 2.12801516661772;
   fWeightMatrix0to1[2][7] = 0.56509217546499;
   fWeightMatrix0to1[3][7] = 2.89685847965356;
   fWeightMatrix0to1[4][7] = 1.79123330393695;
   fWeightMatrix0to1[5][7] = 6.1003898192956;
   fWeightMatrix0to1[6][7] = -0.553453389285666;
   fWeightMatrix0to1[7][7] = -3.1172515932822;
   fWeightMatrix0to1[8][7] = 0.167359345834867;
   fWeightMatrix0to1[9][7] = 1.2073600160659;
   fWeightMatrix0to1[10][7] = -4.1070357073901;
   fWeightMatrix0to1[0][8] = -3.22117908563789;
   fWeightMatrix0to1[1][8] = -0.755569370697349;
   fWeightMatrix0to1[2][8] = 1.8964120443268;
   fWeightMatrix0to1[3][8] = 0.862924084752462;
   fWeightMatrix0to1[4][8] = 2.0056613453566;
   fWeightMatrix0to1[5][8] = -1.21117045757625;
   fWeightMatrix0to1[6][8] = -2.58088434732574;
   fWeightMatrix0to1[7][8] = 2.54227380387211;
   fWeightMatrix0to1[8][8] = -0.259727808287301;
   fWeightMatrix0to1[9][8] = -1.61452236465463;
   fWeightMatrix0to1[10][8] = -3.59332278282089;
   // weight matrix from layer 1 to 2
   fWeightMatrix1to2[0][0] = -0.0461668685360137;
   fWeightMatrix1to2[1][0] = -4.55209065910066;
   fWeightMatrix1to2[2][0] = -0.803777653603235;
   fWeightMatrix1to2[3][0] = 0.835244734182343;
   fWeightMatrix1to2[4][0] = 1.88898150904542;
   fWeightMatrix1to2[5][0] = -1.44916175562279;
   fWeightMatrix1to2[6][0] = 0.593504757268308;
   fWeightMatrix1to2[7][0] = -1.39347684322573;
   fWeightMatrix1to2[0][1] = -0.779021781891154;
   fWeightMatrix1to2[1][1] = 1.73847094135062;
   fWeightMatrix1to2[2][1] = 0.617569667709111;
   fWeightMatrix1to2[3][1] = -2.21929296170124;
   fWeightMatrix1to2[4][1] = 0.483551138042079;
   fWeightMatrix1to2[5][1] = 0.519014291745991;
   fWeightMatrix1to2[6][1] = 0.880044139005137;
   fWeightMatrix1to2[7][1] = -1.68780098516546;
   fWeightMatrix1to2[0][2] = 2.10150715841831;
   fWeightMatrix1to2[1][2] = 3.15079940007206;
   fWeightMatrix1to2[2][2] = -1.15887508796965;
   fWeightMatrix1to2[3][2] = 0.734474454385806;
   fWeightMatrix1to2[4][2] = -2.64245437345657;
   fWeightMatrix1to2[5][2] = -1.93756971358739;
   fWeightMatrix1to2[6][2] = 0.162419227268519;
   fWeightMatrix1to2[7][2] = -0.688719347018481;
   fWeightMatrix1to2[0][3] = 1.81367927626081;
   fWeightMatrix1to2[1][3] = 2.99978942825341;
   fWeightMatrix1to2[2][3] = -0.172164228159997;
   fWeightMatrix1to2[3][3] = -0.80505051236394;
   fWeightMatrix1to2[4][3] = 0.260320002144909;
   fWeightMatrix1to2[5][3] = -1.45506297917268;
   fWeightMatrix1to2[6][3] = 1.71926345155387;
   fWeightMatrix1to2[7][3] = 0.265621662802884;
   fWeightMatrix1to2[0][4] = -2.08434167587401;
   fWeightMatrix1to2[1][4] = 1.04469945144486;
   fWeightMatrix1to2[2][4] = -2.11355013920427;
   fWeightMatrix1to2[3][4] = -0.651291275163465;
   fWeightMatrix1to2[4][4] = 1.33416540968556;
   fWeightMatrix1to2[5][4] = 2.1214027452129;
   fWeightMatrix1to2[6][4] = -2.28837980582409;
   fWeightMatrix1to2[7][4] = -0.0545341302386985;
   fWeightMatrix1to2[0][5] = 1.26206934949014;
   fWeightMatrix1to2[1][5] = 4.82204213797136;
   fWeightMatrix1to2[2][5] = 0.355321338435612;
   fWeightMatrix1to2[3][5] = -1.7893553627408;
   fWeightMatrix1to2[4][5] = 0.906214899199797;
   fWeightMatrix1to2[5][5] = -1.37589390033921;
   fWeightMatrix1to2[6][5] = 2.04237078416291;
   fWeightMatrix1to2[7][5] = 1.55983454151996;
   fWeightMatrix1to2[0][6] = 0.129042879507993;
   fWeightMatrix1to2[1][6] = -3.83720621089416;
   fWeightMatrix1to2[2][6] = 0.217217089336322;
   fWeightMatrix1to2[3][6] = -1.86516622024521;
   fWeightMatrix1to2[4][6] = 2.2438363917452;
   fWeightMatrix1to2[5][6] = 2.18821080451185;
   fWeightMatrix1to2[6][6] = -1.30555245348386;
   fWeightMatrix1to2[7][6] = -0.910315112270943;
   fWeightMatrix1to2[0][7] = 0.67815502893433;
   fWeightMatrix1to2[1][7] = 3.85861307843873;
   fWeightMatrix1to2[2][7] = 0.00984328985591324;
   fWeightMatrix1to2[3][7] = 0.655488889779294;
   fWeightMatrix1to2[4][7] = -3.90831525101664;
   fWeightMatrix1to2[5][7] = 0.910680654375722;
   fWeightMatrix1to2[6][7] = 0.751822264423975;
   fWeightMatrix1to2[7][7] = 0.162916100572108;
   fWeightMatrix1to2[0][8] = 0.59183801206046;
   fWeightMatrix1to2[1][8] = 1.38696611583693;
   fWeightMatrix1to2[2][8] = -1.08880247846932;
   fWeightMatrix1to2[3][8] = -0.895628348183739;
   fWeightMatrix1to2[4][8] = 0.413018441111338;
   fWeightMatrix1to2[5][8] = -0.430527017764738;
   fWeightMatrix1to2[6][8] = -0.338838216173888;
   fWeightMatrix1to2[7][8] = 1.27493759907029;
   fWeightMatrix1to2[0][9] = 1.07239549805671;
   fWeightMatrix1to2[1][9] = -0.0753996525644817;
   fWeightMatrix1to2[2][9] = 1.46295899740091;
   fWeightMatrix1to2[3][9] = 1.80381830294189;
   fWeightMatrix1to2[4][9] = -1.98794438529851;
   fWeightMatrix1to2[5][9] = 0.654112186325792;
   fWeightMatrix1to2[6][9] = 0.107980099663938;
   fWeightMatrix1to2[7][9] = 0.459045175939995;
   fWeightMatrix1to2[0][10] = -1.87687372592554;
   fWeightMatrix1to2[1][10] = -3.55318987478743;
   fWeightMatrix1to2[2][10] = 1.7004648651397;
   fWeightMatrix1to2[3][10] = 1.84273311780686;
   fWeightMatrix1to2[4][10] = -1.47258266698827;
   fWeightMatrix1to2[5][10] = -0.349821726894926;
   fWeightMatrix1to2[6][10] = -0.890881637518003;
   fWeightMatrix1to2[7][10] = -0.0555562921251794;
   fWeightMatrix1to2[0][11] = 1.71002419555945;
   fWeightMatrix1to2[1][11] = 1.34612598071098;
   fWeightMatrix1to2[2][11] = -0.280920674242093;
   fWeightMatrix1to2[3][11] = -1.6636919570681;
   fWeightMatrix1to2[4][11] = 0.397716742643028;
   fWeightMatrix1to2[5][11] = 1.65047677342237;
   fWeightMatrix1to2[6][11] = 1.13271188195205;
   fWeightMatrix1to2[7][11] = -0.171362694621694;
   // weight matrix from layer 2 to 3
   fWeightMatrix2to3[0][0] = -1.86671591212891;
   fWeightMatrix2to3[1][0] = -2.47717645147574;
   fWeightMatrix2to3[2][0] = 0.249535980216028;
   fWeightMatrix2to3[3][0] = 0.414463174249866;
   fWeightMatrix2to3[4][0] = -1.94811645327647;
   fWeightMatrix2to3[0][1] = -3.0894421235703;
   fWeightMatrix2to3[1][1] = 0.165094884314937;
   fWeightMatrix2to3[2][1] = 0.417119867632663;
   fWeightMatrix2to3[3][1] = -6.94190456490472;
   fWeightMatrix2to3[4][1] = 1.20478258823355;
   fWeightMatrix2to3[0][2] = 0.839234369976785;
   fWeightMatrix2to3[1][2] = -0.675324370332317;
   fWeightMatrix2to3[2][2] = -0.175856722662866;
   fWeightMatrix2to3[3][2] = 2.11843153929565;
   fWeightMatrix2to3[4][2] = 0.884397569553054;
   fWeightMatrix2to3[0][3] = 1.25582925133121;
   fWeightMatrix2to3[1][3] = -0.561876538576417;
   fWeightMatrix2to3[2][3] = -2.10786487136549;
   fWeightMatrix2to3[3][3] = -1.25161748910515;
   fWeightMatrix2to3[4][3] = 0.897248737526749;
   fWeightMatrix2to3[0][4] = 1.11105416998786;
   fWeightMatrix2to3[1][4] = 0.0507948702903113;
   fWeightMatrix2to3[2][4] = -0.659717281826757;
   fWeightMatrix2to3[3][4] = 4.86242756209956;
   fWeightMatrix2to3[4][4] = -1.76245438567763;
   fWeightMatrix2to3[0][5] = -2.27909550872765;
   fWeightMatrix2to3[1][5] = -0.542893689049222;
   fWeightMatrix2to3[2][5] = -1.28466487737861;
   fWeightMatrix2to3[3][5] = 2.11382493389424;
   fWeightMatrix2to3[4][5] = 1.0220551755807;
   fWeightMatrix2to3[0][6] = -0.900946246936041;
   fWeightMatrix2to3[1][6] = -0.0324214687780084;
   fWeightMatrix2to3[2][6] = -0.82286044595412;
   fWeightMatrix2to3[3][6] = -1.75543727487405;
   fWeightMatrix2to3[4][6] = -1.81950459093684;
   fWeightMatrix2to3[0][7] = 0.862190528142488;
   fWeightMatrix2to3[1][7] = -0.365189533648929;
   fWeightMatrix2to3[2][7] = -0.250062036258833;
   fWeightMatrix2to3[3][7] = -1.75316853015447;
   fWeightMatrix2to3[4][7] = 1.23895909780175;
   fWeightMatrix2to3[0][8] = -2.24663452840668;
   fWeightMatrix2to3[1][8] = -0.0491648835307893;
   fWeightMatrix2to3[2][8] = -0.898534029814058;
   fWeightMatrix2to3[3][8] = -0.19298736343403;
   fWeightMatrix2to3[4][8] = -2.15754958211619;
   // weight matrix from layer 3 to 4
   fWeightMatrix3to4[0][0] = -1.06373366875055;
   fWeightMatrix3to4[0][1] = -0.0949598314076553;
   fWeightMatrix3to4[0][2] = -0.761573481220842;
   fWeightMatrix3to4[0][3] = -1.12380174382075;
   fWeightMatrix3to4[0][4] = -1.08283646511007;
   fWeightMatrix3to4[0][5] = 1.10834750420174;
}

inline double Read3Layers24Decrease::GetMvaValue__( const std::vector<double>& inputValues ) const
{
   if (inputValues.size() != (unsigned int)fLayerSize[0]-1) {
      std::cout << "Input vector needs to be of size " << fLayerSize[0]-1 << std::endl;
      return 0;
   }

   for (int l=0; l<fLayers; l++)
      for (int i=0; i<fLayerSize[l]; i++) fWeights[l][i]=0;

   for (int l=0; l<fLayers-1; l++)
      fWeights[l][fLayerSize[l]-1]=1;

   for (int i=0; i<fLayerSize[0]-1; i++)
      fWeights[0][i]=inputValues[i];

   // layer 0 to 1
   for (int o=0; o<fLayerSize[1]-1; o++) {
      for (int i=0; i<fLayerSize[0]; i++) {
         double inputVal = fWeightMatrix0to1[o][i] * fWeights[0][i];
         fWeights[1][o] += inputVal;
      }
      fWeights[1][o] = ActivationFnc(fWeights[1][o]);
   }
   // layer 1 to 2
   for (int o=0; o<fLayerSize[2]-1; o++) {
      for (int i=0; i<fLayerSize[1]; i++) {
         double inputVal = fWeightMatrix1to2[o][i] * fWeights[1][i];
         fWeights[2][o] += inputVal;
      }
      fWeights[2][o] = ActivationFnc(fWeights[2][o]);
   }
   // layer 2 to 3
   for (int o=0; o<fLayerSize[3]-1; o++) {
      for (int i=0; i<fLayerSize[2]; i++) {
         double inputVal = fWeightMatrix2to3[o][i] * fWeights[2][i];
         fWeights[3][o] += inputVal;
      }
      fWeights[3][o] = ActivationFnc(fWeights[3][o]);
   }
   // layer 3 to 4
   for (int o=0; o<fLayerSize[4]; o++) {
      for (int i=0; i<fLayerSize[3]; i++) {
         double inputVal = fWeightMatrix3to4[o][i] * fWeights[3][i];
         fWeights[4][o] += inputVal;
      }
      fWeights[4][o] = OutputActivationFnc(fWeights[4][o]);
   }

   return fWeights[4][0];
}

double Read3Layers24Decrease::ActivationFnc(double x) const {
   // sigmoid
   return 1.0/(1.0+exp(-x));
}
double Read3Layers24Decrease::OutputActivationFnc(double x) const {
   // identity
   return x;
}
   
// Clean up
inline void Read3Layers24Decrease::Clear() 
{
   // clean up the arrays
   for (int lIdx = 0; lIdx < 5; lIdx++) {
      delete[] fWeights[lIdx];
   }
}
   inline double Read3Layers24Decrease::GetMvaValue( const std::vector<double>& inputValues ) const
   {
      // classifier response value
      double retval = 0;

      // classifier response, sanity check first
      if (!IsStatusClean()) {
         std::cout << "Problem in class \"" << fClassName << "\": cannot return classifier response"
                   << " because status is dirty" << std::endl;
         retval = 0;
      }
      else {
         if (IsNormalised()) {
            // normalise variables
            std::vector<double> iV;
            iV.resize(inputValues.size());
            int ivar = 0;
            for (std::vector<double>::const_iterator varIt = inputValues.begin();
                 varIt != inputValues.end(); varIt++, ivar++) {
               iV.push_back(NormVariable( *varIt, fVmin[ivar], fVmax[ivar] ));
            }
            Transform( iV, -1 );
            retval = GetMvaValue__( iV );
         }
         else {
            std::vector<double> iV;
            int ivar = 0;
            for (std::vector<double>::const_iterator varIt = inputValues.begin();
                 varIt != inputValues.end(); varIt++, ivar++) {
               iV.push_back(*varIt);
            }
            Transform( iV, -1 );
            retval = GetMvaValue__( iV );
         }
      }

      return retval;
   }

//_______________________________________________________________________
inline void Read3Layers24Decrease::InitTransform_1()
{
   // Normalization transformation, initialisation
   fMin_1[0][0] = 5;
   fMax_1[0][0] = 2543.40991211;
   fMin_1[1][0] = 4.73000001907;
   fMax_1[1][0] = 817.520019531;
   fMin_1[2][0] = 4.73000001907;
   fMax_1[2][0] = 2543.40991211;
   fMin_1[0][1] = -3.99099993706;
   fMax_1[0][1] = 3.99099993706;
   fMin_1[1][1] = -3.99300003052;
   fMax_1[1][1] = 3.99000000954;
   fMin_1[2][1] = -3.99300003052;
   fMax_1[2][1] = 3.99099993706;
   fMin_1[0][2] = 0;
   fMax_1[0][2] = 6.28299999237;
   fMin_1[1][2] = 0;
   fMax_1[1][2] = 6.28299999237;
   fMin_1[2][2] = 0;
   fMax_1[2][2] = 6.28299999237;
   fMin_1[0][3] = 0;
   fMax_1[0][3] = 258.730010986;
   fMin_1[1][3] = 0;
   fMax_1[1][3] = 159.369995117;
   fMin_1[2][3] = 0;
   fMax_1[2][3] = 258.730010986;
   fMin_1[0][4] = 0;
   fMax_1[0][4] = 61;
   fMin_1[1][4] = 0;
   fMax_1[1][4] = 59;
   fMin_1[2][4] = 0;
   fMax_1[2][4] = 61;
   fMin_1[0][5] = 0;
   fMax_1[0][5] = 999;
   fMin_1[1][5] = 0;
   fMax_1[1][5] = 999;
   fMin_1[2][5] = 0;
   fMax_1[2][5] = 999;
   fMin_1[0][6] = 0;
   fMax_1[0][6] = 6.28299999237;
   fMin_1[1][6] = 0.0010000000475;
   fMax_1[1][6] = 6.28200006485;
   fMin_1[2][6] = 0;
   fMax_1[2][6] = 6.28299999237;
   fMin_1[0][7] = 100.019996643;
   fMax_1[0][7] = 1585.47998047;
   fMin_1[1][7] = 100.010002136;
   fMax_1[1][7] = 662.650024414;
   fMin_1[2][7] = 100.010002136;
   fMax_1[2][7] = 1585.47998047;
}

//_______________________________________________________________________
inline void Read3Layers24Decrease::Transform_1( std::vector<double>& iv, int cls) const
{
   // Normalization transformation
   if (cls < 0 || cls > 2) {
   if (2 > 1 ) cls = 2;
      else cls = 2;
   }
   const int nVar = 8;

   // get indices of used variables

   // define the indices of the variables which are transformed by this transformation
   static std::vector<int> indicesGet;
   static std::vector<int> indicesPut;

   if ( indicesGet.empty() ) { 
      indicesGet.reserve(nVar);
      indicesGet.push_back( 0);
      indicesGet.push_back( 1);
      indicesGet.push_back( 2);
      indicesGet.push_back( 3);
      indicesGet.push_back( 4);
      indicesGet.push_back( 5);
      indicesGet.push_back( 6);
      indicesGet.push_back( 7);
   } 
   if ( indicesPut.empty() ) { 
      indicesPut.reserve(nVar);
      indicesPut.push_back( 0);
      indicesPut.push_back( 1);
      indicesPut.push_back( 2);
      indicesPut.push_back( 3);
      indicesPut.push_back( 4);
      indicesPut.push_back( 5);
      indicesPut.push_back( 6);
      indicesPut.push_back( 7);
   } 

   static std::vector<double> dv;
   dv.resize(nVar);
   for (int ivar=0; ivar<nVar; ivar++) dv[ivar] = iv[indicesGet.at(ivar)];
   for (int ivar=0;ivar<8;ivar++) {
      double offset = fMin_1[cls][ivar];
      double scale  = 1.0/(fMax_1[cls][ivar]-fMin_1[cls][ivar]);
      iv[indicesPut.at(ivar)] = (dv[ivar]-offset)*scale * 2 - 1;
   }
}

//_______________________________________________________________________
inline void Read3Layers24Decrease::InitTransform()
{
   InitTransform_1();
}

//_______________________________________________________________________
inline void Read3Layers24Decrease::Transform( std::vector<double>& iv, int sigOrBgd ) const
{
   Transform_1( iv, sigOrBgd );
}
