// Class: Read3 Layers, 33 Nodes Increasing
// Automatically generated by MethodBase::MakeClass
//

/* configuration options =====================================================

#GEN -*-*-*-*-*-*-*-*-*-*-*- general info -*-*-*-*-*-*-*-*-*-*-*-

Method         : MLP::3 Layers, 33 Nodes Increasing
TMVA Release   : 4.2.0         [262656]
ROOT Release   : 5.34/18       [336402]
Creator        : zxb0111
Date           : Thu Dec  4 21:38:59 2014
Host           : Linux localhost.localdomain 2.6.32-431.17.1.el6.x86_64 #1 SMP Wed May 7 14:14:17 CDT 2014 x86_64 x86_64 x86_64 GNU/Linux
Dir            : /home/zxb0111/seminar
Training events: 34086
Analysis type  : [Classification]


#OPT -*-*-*-*-*-*-*-*-*-*-*-*- options -*-*-*-*-*-*-*-*-*-*-*-*-

# Set by User:
NCycles: "600" [Number of training cycles]
HiddenLayers: "14,10,9" [Specification of hidden layer architecture]
NeuronType: "sigmoid" [Neuron activation function type]
VarTransform: "N" [List of variable transformations performed before training, e.g., "D_Background,P_Signal,G,N_AllClasses" for: "Decorrelation, PCA-transformation, Gaussianisation, Normalisation, each for the given class of events ('AllClasses' denotes all events of all classes, if no class indication is given, 'All' is assumed)"]
TestRate: "5" [Test for overtraining performed at each #th epochs]
UseRegulator: "False" [Use regulator to avoid over-training]
# Default:
RandomSeed: "1" [Random seed for initial synapse weights (0 means unique seed for each run; default value '1')]
EstimatorType: "MSE" [MSE (Mean Square Estimator) for Gaussian Likelihood or CE(Cross-Entropy) for Bernoulli Likelihood]
NeuronInputType: "sum" [Neuron input function type]
V: "False" [Verbose output (short form of "VerbosityLevel" below - overrides the latter one)]
VerbosityLevel: "Default" [Verbosity level]
H: "False" [Print method-specific help message]
CreateMVAPdfs: "False" [Create PDFs for classifier outputs (signal and background)]
IgnoreNegWeightsInTraining: "False" [Events with negative weights are ignored in the training (but are included for testing and performance evaluation)]
TrainingMethod: "BP" [Train with Back-Propagation (BP), BFGS Algorithm (BFGS), or Genetic Algorithm (GA - slower and worse)]
LearningRate: "2.000000e-02" [ANN learning rate parameter]
DecayRate: "1.000000e-02" [Decay rate for learning parameter]
EpochMonitoring: "False" [Provide epoch-wise monitoring plots according to TestRate (caution: causes big ROOT output file!)]
Sampling: "1.000000e+00" [Only 'Sampling' (randomly selected) events are trained each epoch]
SamplingEpoch: "1.000000e+00" [Sampling is used for the first 'SamplingEpoch' epochs, afterwards, all events are taken for training]
SamplingImportance: "1.000000e+00" [ The sampling weights of events in epochs which successful (worse estimator than before) are multiplied with SamplingImportance, else they are divided.]
SamplingTraining: "True" [The training sample is sampled]
SamplingTesting: "False" [The testing sample is sampled]
ResetStep: "50" [How often BFGS should reset history]
Tau: "3.000000e+00" [LineSearch "size step"]
BPMode: "sequential" [Back-propagation learning mode: sequential or batch]
BatchSize: "-1" [Batch size: number of events/batch, only set if in Batch Mode, -1 for BatchSize=number_of_events]
ConvergenceImprove: "1.000000e-30" [Minimum improvement which counts as improvement (<0 means automatic convergence check is turned off)]
ConvergenceTests: "-1" [Number of steps (without improvement) required for convergence (<0 means automatic convergence check is turned off)]
UpdateLimit: "10000" [Maximum times of regulator update]
CalculateErrors: "False" [Calculates inverse Hessian matrix at the end of the training to be able to calculate the uncertainties of an MVA value]
WeightRange: "1.000000e+00" [Take the events for the estimator calculations from small deviations from the desired value to large deviations only over the weight range]
##


#VAR -*-*-*-*-*-*-*-*-*-*-*-* variables *-*-*-*-*-*-*-*-*-*-*-*-

NVar 8
Jet.PT                        Jet.PT                        Jet.PT                        Jet.PT                                                          'F'    [4.73000001907,2543.40991211]
Jet.Eta                       Jet.Eta                       Jet.Eta                       Jet.Eta                                                         'F'    [-3.99300003052,3.99099993706]
Jet.Phi                       Jet.Phi                       Jet.Phi                       Jet.Phi                                                         'F'    [0,6.28299999237]
Jet.Mass                      Jet.Mass                      Jet.Mass                      Jet.Mass                                                        'F'    [0,258.730010986]
Jet.Ntrk                      Jet.Ntrk                      Jet.Ntrk                      Jet.Ntrk                                                        'F'    [0,61]
Jet.EhadOverEem               Jet.EhadOverEem               Jet.EhadOverEem               Jet.EhadOverEem                                                 'F'    [0,999]
MissingET.Phi                 MissingET.Phi                 MissingET.Phi                 MissingET.Phi                                                   'F'    [0,6.28299999237]
MissingET.MET                 MissingET.MET                 MissingET.MET                 MissingET.MET                                                   'F'    [100.010002136,1585.47998047]
NSpec 0


============================================================================ */

#include <vector>
#include <cmath>
#include <string>
#include <iostream>

#ifndef IClassifierReader__def
#define IClassifierReader__def

class IClassifierReader {

 public:

   // constructor
   IClassifierReader() : fStatusIsClean( true ) {}
   virtual ~IClassifierReader() {}

   // return classifier response
   virtual double GetMvaValue( const std::vector<double>& inputValues ) const = 0;

   // returns classifier status
   bool IsStatusClean() const { return fStatusIsClean; }

 protected:

   bool fStatusIsClean;
};

#endif

class Read3 Layers, 33 Nodes Increasing : public IClassifierReader {

 public:

   // constructor
   Read3 Layers, 33 Nodes Increasing( std::vector<std::string>& theInputVars ) 
      : IClassifierReader(),
        fClassName( "Read3 Layers, 33 Nodes Increasing" ),
        fNvars( 8 ),
        fIsNormalised( false )
   {      
      // the training input variables
      const char* inputVars[] = { "Jet.PT", "Jet.Eta", "Jet.Phi", "Jet.Mass", "Jet.Ntrk", "Jet.EhadOverEem", "MissingET.Phi", "MissingET.MET" };

      // sanity checks
      if (theInputVars.size() <= 0) {
         std::cout << "Problem in class \"" << fClassName << "\": empty input vector" << std::endl;
         fStatusIsClean = false;
      }

      if (theInputVars.size() != fNvars) {
         std::cout << "Problem in class \"" << fClassName << "\": mismatch in number of input values: "
                   << theInputVars.size() << " != " << fNvars << std::endl;
         fStatusIsClean = false;
      }

      // validate input variables
      for (size_t ivar = 0; ivar < theInputVars.size(); ivar++) {
         if (theInputVars[ivar] != inputVars[ivar]) {
            std::cout << "Problem in class \"" << fClassName << "\": mismatch in input variable names" << std::endl
                      << " for variable [" << ivar << "]: " << theInputVars[ivar].c_str() << " != " << inputVars[ivar] << std::endl;
            fStatusIsClean = false;
         }
      }

      // initialize min and max vectors (for normalisation)
      fVmin[0] = -1;
      fVmax[0] = 1;
      fVmin[1] = -1;
      fVmax[1] = 1;
      fVmin[2] = -1;
      fVmax[2] = 0.99999988079071;
      fVmin[3] = -1;
      fVmax[3] = 1;
      fVmin[4] = -1;
      fVmax[4] = 0.99999988079071;
      fVmin[5] = -1;
      fVmax[5] = 1;
      fVmin[6] = -1;
      fVmax[6] = 0.99999988079071;
      fVmin[7] = -1;
      fVmax[7] = 1;

      // initialize input variable types
      fType[0] = 'F';
      fType[1] = 'F';
      fType[2] = 'F';
      fType[3] = 'F';
      fType[4] = 'F';
      fType[5] = 'F';
      fType[6] = 'F';
      fType[7] = 'F';

      // initialize constants
      Initialize();

      // initialize transformation
      InitTransform();
   }

   // destructor
   virtual ~Read3 Layers, 33 Nodes Increasing() {
      Clear(); // method-specific
   }

   // the classifier response
   // "inputValues" is a vector of input values in the same order as the 
   // variables given to the constructor
   double GetMvaValue( const std::vector<double>& inputValues ) const;

 private:

   // method-specific destructor
   void Clear();

   // input variable transformation

   double fMin_1[3][8];
   double fMax_1[3][8];
   void InitTransform_1();
   void Transform_1( std::vector<double> & iv, int sigOrBgd ) const;
   void InitTransform();
   void Transform( std::vector<double> & iv, int sigOrBgd ) const;

   // common member variables
   const char* fClassName;

   const size_t fNvars;
   size_t GetNvar()           const { return fNvars; }
   char   GetType( int ivar ) const { return fType[ivar]; }

   // normalisation of input variables
   const bool fIsNormalised;
   bool IsNormalised() const { return fIsNormalised; }
   double fVmin[8];
   double fVmax[8];
   double NormVariable( double x, double xmin, double xmax ) const {
      // normalise to output range: [-1, 1]
      return 2*(x - xmin)/(xmax - xmin) - 1.0;
   }

   // type of input variable: 'F' or 'I'
   char   fType[8];

   // initialize internal variables
   void Initialize();
   double GetMvaValue__( const std::vector<double>& inputValues ) const;

   // private members (method specific)

   double ActivationFnc(double x) const;
   double OutputActivationFnc(double x) const;

   int fLayers;
   int fLayerSize[5];
   double fWeightMatrix0to1[15][9];   // weight matrix from layer 0 to 1
   double fWeightMatrix1to2[11][15];   // weight matrix from layer 1 to 2
   double fWeightMatrix2to3[10][11];   // weight matrix from layer 2 to 3
   double fWeightMatrix3to4[1][10];   // weight matrix from layer 3 to 4

   double * fWeights[5];
};

inline void Read3 Layers, 33 Nodes Increasing::Initialize()
{
   // build network structure
   fLayers = 5;
   fLayerSize[0] = 9; fWeights[0] = new double[9]; 
   fLayerSize[1] = 15; fWeights[1] = new double[15]; 
   fLayerSize[2] = 11; fWeights[2] = new double[11]; 
   fLayerSize[3] = 10; fWeights[3] = new double[10]; 
   fLayerSize[4] = 1; fWeights[4] = new double[1]; 
   // weight matrix from layer 0 to 1
   fWeightMatrix0to1[0][0] = 0.299853076110456;
   fWeightMatrix0to1[1][0] = 3.71994572198945;
   fWeightMatrix0to1[2][0] = 1.18556648548454;
   fWeightMatrix0to1[3][0] = 1.85843829864897;
   fWeightMatrix0to1[4][0] = -3.25910218375821;
   fWeightMatrix0to1[5][0] = -0.558661715851977;
   fWeightMatrix0to1[6][0] = -0.881871133468779;
   fWeightMatrix0to1[7][0] = 4.41508228254977;
   fWeightMatrix0to1[8][0] = -0.943368073236335;
   fWeightMatrix0to1[9][0] = -0.123524195218207;
   fWeightMatrix0to1[10][0] = -5.01411366269386;
   fWeightMatrix0to1[11][0] = -1.1579579307642;
   fWeightMatrix0to1[12][0] = -1.19550163996373;
   fWeightMatrix0to1[13][0] = -0.430779201824184;
   fWeightMatrix0to1[0][1] = 0.291727989358461;
   fWeightMatrix0to1[1][1] = 0.257809173927869;
   fWeightMatrix0to1[2][1] = 0.263085536170949;
   fWeightMatrix0to1[3][1] = 4.32024378731625;
   fWeightMatrix0to1[4][1] = 0.763793069216683;
   fWeightMatrix0to1[5][1] = -0.468493223395448;
   fWeightMatrix0to1[6][1] = -0.140159812855274;
   fWeightMatrix0to1[7][1] = -0.10123282155634;
   fWeightMatrix0to1[8][1] = -0.132307213820116;
   fWeightMatrix0to1[9][1] = -0.235198471272092;
   fWeightMatrix0to1[10][1] = 0.428586809634375;
   fWeightMatrix0to1[11][1] = 0.0150288806046495;
   fWeightMatrix0to1[12][1] = 0.751411843072624;
   fWeightMatrix0to1[13][1] = -0.0539039503445635;
   fWeightMatrix0to1[0][2] = 0.164438068930157;
   fWeightMatrix0to1[1][2] = 0.461541075454053;
   fWeightMatrix0to1[2][2] = 0.101572263589104;
   fWeightMatrix0to1[3][2] = -0.0408495769046575;
   fWeightMatrix0to1[4][2] = 0.703625908669973;
   fWeightMatrix0to1[5][2] = 3.77389644111009;
   fWeightMatrix0to1[6][2] = -0.0399191753392153;
   fWeightMatrix0to1[7][2] = -0.971034611779692;
   fWeightMatrix0to1[8][2] = -1.65236468229955;
   fWeightMatrix0to1[9][2] = 4.3635486405919;
   fWeightMatrix0to1[10][2] = 1.05106204583615;
   fWeightMatrix0to1[11][2] = 0.949592343800302;
   fWeightMatrix0to1[12][2] = 0.792787816051772;
   fWeightMatrix0to1[13][2] = 1.45862623558395;
   fWeightMatrix0to1[0][3] = 2.87845022964069;
   fWeightMatrix0to1[1][3] = 2.53722374166199;
   fWeightMatrix0to1[2][3] = -0.197342265163193;
   fWeightMatrix0to1[3][3] = -1.44508850610547;
   fWeightMatrix0to1[4][3] = 0.527961112407191;
   fWeightMatrix0to1[5][3] = 0.895530035746552;
   fWeightMatrix0to1[6][3] = 1.36062490717108;
   fWeightMatrix0to1[7][3] = 0.938191726101713;
   fWeightMatrix0to1[8][3] = 1.67343049494018;
   fWeightMatrix0to1[9][3] = 0.291848926307002;
   fWeightMatrix0to1[10][3] = -1.53751798490301;
   fWeightMatrix0to1[11][3] = 0.965758218590949;
   fWeightMatrix0to1[12][3] = -1.84665629399366;
   fWeightMatrix0to1[13][3] = -0.327928718668448;
   fWeightMatrix0to1[0][4] = -0.752062280405834;
   fWeightMatrix0to1[1][4] = -1.33542747138763;
   fWeightMatrix0to1[2][4] = 1.02044514538532;
   fWeightMatrix0to1[3][4] = 0.951256958727033;
   fWeightMatrix0to1[4][4] = -1.12629913948501;
   fWeightMatrix0to1[5][4] = 0.180298979602514;
   fWeightMatrix0to1[6][4] = -0.427368247962549;
   fWeightMatrix0to1[7][4] = -0.551558316562409;
   fWeightMatrix0to1[8][4] = 1.42189338991089;
   fWeightMatrix0to1[9][4] = 0.155680964697506;
   fWeightMatrix0to1[10][4] = 0.156532903321497;
   fWeightMatrix0to1[11][4] = -1.39262069866551;
   fWeightMatrix0to1[12][4] = 0.644335235844789;
   fWeightMatrix0to1[13][4] = -0.724353537475769;
   fWeightMatrix0to1[0][5] = -0.420943414445193;
   fWeightMatrix0to1[1][5] = -0.46048412107235;
   fWeightMatrix0to1[2][5] = 0.2173810174484;
   fWeightMatrix0to1[3][5] = 0.979756320421;
   fWeightMatrix0to1[4][5] = 1.38053404110297;
   fWeightMatrix0to1[5][5] = 0.395237964225629;
   fWeightMatrix0to1[6][5] = -2.35549060493189;
   fWeightMatrix0to1[7][5] = -3.60941230973043;
   fWeightMatrix0to1[8][5] = 1.52293410256907;
   fWeightMatrix0to1[9][5] = -0.500241811270049;
   fWeightMatrix0to1[10][5] = 3.3475237722019;
   fWeightMatrix0to1[11][5] = 0.418248478532209;
   fWeightMatrix0to1[12][5] = 0.940022895389521;
   fWeightMatrix0to1[13][5] = 0.0272353000303961;
   fWeightMatrix0to1[0][6] = -0.933473224116583;
   fWeightMatrix0to1[1][6] = -0.159386469728045;
   fWeightMatrix0to1[2][6] = -0.120881906408804;
   fWeightMatrix0to1[3][6] = -0.115975799499585;
   fWeightMatrix0to1[4][6] = -0.512537894584743;
   fWeightMatrix0to1[5][6] = -3.7717697363849;
   fWeightMatrix0to1[6][6] = 0.196323131383621;
   fWeightMatrix0to1[7][6] = 0.830034228138172;
   fWeightMatrix0to1[8][6] = 1.7537420470409;
   fWeightMatrix0to1[9][6] = -4.39291995395192;
   fWeightMatrix0to1[10][6] = -1.18560361425216;
   fWeightMatrix0to1[11][6] = 1.51811897616093;
   fWeightMatrix0to1[12][6] = -0.765011207090557;
   fWeightMatrix0to1[13][6] = -1.20413276226487;
   fWeightMatrix0to1[0][7] = -5.04128441323639;
   fWeightMatrix0to1[1][7] = -5.19711917722698;
   fWeightMatrix0to1[2][7] = -5.58766844012878;
   fWeightMatrix0to1[3][7] = -1.65350713461401;
   fWeightMatrix0to1[4][7] = 2.16584742718357;
   fWeightMatrix0to1[5][7] = 3.83541940123925;
   fWeightMatrix0to1[6][7] = -0.965580906065394;
   fWeightMatrix0to1[7][7] = 3.31838452735385;
   fWeightMatrix0to1[8][7] = -0.505221827620219;
   fWeightMatrix0to1[9][7] = -0.30415653980237;
   fWeightMatrix0to1[10][7] = -0.278670661092165;
   fWeightMatrix0to1[11][7] = 0.337343068543788;
   fWeightMatrix0to1[12][7] = -2.3710626623126;
   fWeightMatrix0to1[13][7] = 0.136581847027954;
   fWeightMatrix0to1[0][8] = -0.472147953350135;
   fWeightMatrix0to1[1][8] = 0.12845780005076;
   fWeightMatrix0to1[2][8] = -1.98015379729795;
   fWeightMatrix0to1[3][8] = 1.96932355161698;
   fWeightMatrix0to1[4][8] = 0.204854273153124;
   fWeightMatrix0to1[5][8] = -1.61985502716792;
   fWeightMatrix0to1[6][8] = 0.990515740316354;
   fWeightMatrix0to1[7][8] = 1.53237202219672;
   fWeightMatrix0to1[8][8] = -1.89948424973847;
   fWeightMatrix0to1[9][8] = 1.92227923142941;
   fWeightMatrix0to1[10][8] = -2.5661617430333;
   fWeightMatrix0to1[11][8] = 1.80165204666497;
   fWeightMatrix0to1[12][8] = 0.803353082268199;
   fWeightMatrix0to1[13][8] = -0.493222384723474;
   // weight matrix from layer 1 to 2
   fWeightMatrix1to2[0][0] = 1.0737925357327;
   fWeightMatrix1to2[1][0] = -1.82337721161591;
   fWeightMatrix1to2[2][0] = -2.17567985011467;
   fWeightMatrix1to2[3][0] = 1.00284897541101;
   fWeightMatrix1to2[4][0] = 0.641182952466474;
   fWeightMatrix1to2[5][0] = -2.76294836144821;
   fWeightMatrix1to2[6][0] = 0.644282936166639;
   fWeightMatrix1to2[7][0] = -1.21102885845917;
   fWeightMatrix1to2[8][0] = 0.37757409296303;
   fWeightMatrix1to2[9][0] = 0.811453376465064;
   fWeightMatrix1to2[0][1] = 2.75900111348282;
   fWeightMatrix1to2[1][1] = -4.24043189348681;
   fWeightMatrix1to2[2][1] = 1.19901084641771;
   fWeightMatrix1to2[3][1] = 1.46495119391359;
   fWeightMatrix1to2[4][1] = 2.24081023746098;
   fWeightMatrix1to2[5][1] = -0.344054904704726;
   fWeightMatrix1to2[6][1] = -1.39928913707082;
   fWeightMatrix1to2[7][1] = -0.0598506943969002;
   fWeightMatrix1to2[8][1] = -1.16548536247587;
   fWeightMatrix1to2[9][1] = 1.22430032288271;
   fWeightMatrix1to2[0][2] = 2.48378747424058;
   fWeightMatrix1to2[1][2] = -3.06292981911758;
   fWeightMatrix1to2[2][2] = -1.35338434640952;
   fWeightMatrix1to2[3][2] = 0.120852186655226;
   fWeightMatrix1to2[4][2] = -0.405891129896197;
   fWeightMatrix1to2[5][2] = -0.37723367855059;
   fWeightMatrix1to2[6][2] = 1.7477796901481;
   fWeightMatrix1to2[7][2] = -0.315234056666585;
   fWeightMatrix1to2[8][2] = -0.371752259714968;
   fWeightMatrix1to2[9][2] = 0.0826673467986872;
   fWeightMatrix1to2[0][3] = -0.429923319805232;
   fWeightMatrix1to2[1][3] = 0.753224543663928;
   fWeightMatrix1to2[2][3] = 2.30540484736907;
   fWeightMatrix1to2[3][3] = -1.54461961983066;
   fWeightMatrix1to2[4][3] = 1.28415322605454;
   fWeightMatrix1to2[5][3] = 1.6157367233692;
   fWeightMatrix1to2[6][3] = 0.57178836295721;
   fWeightMatrix1to2[7][3] = 0.507272282687321;
   fWeightMatrix1to2[8][3] = 1.1576991890026;
   fWeightMatrix1to2[9][3] = -0.796339512303641;
   fWeightMatrix1to2[0][4] = -0.250147127997134;
   fWeightMatrix1to2[1][4] = 2.02794578522211;
   fWeightMatrix1to2[2][4] = -3.00113036361066;
   fWeightMatrix1to2[3][4] = -0.578964584347096;
   fWeightMatrix1to2[4][4] = 1.72804105442238;
   fWeightMatrix1to2[5][4] = 0.747528597943401;
   fWeightMatrix1to2[6][4] = -0.216174699810208;
   fWeightMatrix1to2[7][4] = 1.37221788769907;
   fWeightMatrix1to2[8][4] = 2.04107947837469;
   fWeightMatrix1to2[9][4] = -2.00015314934326;
   fWeightMatrix1to2[0][5] = -0.800430080721174;
   fWeightMatrix1to2[1][5] = 1.43542911004568;
   fWeightMatrix1to2[2][5] = 2.54074112430345;
   fWeightMatrix1to2[3][5] = -1.71117176549383;
   fWeightMatrix1to2[4][5] = -2.39441557863881;
   fWeightMatrix1to2[5][5] = 1.95124046884772;
   fWeightMatrix1to2[6][5] = 1.86261827205205;
   fWeightMatrix1to2[7][5] = -1.93226673548377;
   fWeightMatrix1to2[8][5] = -0.177121743157883;
   fWeightMatrix1to2[9][5] = -0.594917637038497;
   fWeightMatrix1to2[0][6] = 0.153701112572969;
   fWeightMatrix1to2[1][6] = 2.21465174864807;
   fWeightMatrix1to2[2][6] = -0.550565118567431;
   fWeightMatrix1to2[3][6] = -0.554542058370636;
   fWeightMatrix1to2[4][6] = -1.30139352321223;
   fWeightMatrix1to2[5][6] = 1.27319834497893;
   fWeightMatrix1to2[6][6] = 1.65971314391367;
   fWeightMatrix1to2[7][6] = 1.19481732310341;
   fWeightMatrix1to2[8][6] = 0.702724152362599;
   fWeightMatrix1to2[9][6] = -1.16362117995025;
   fWeightMatrix1to2[0][7] = -3.50336472620617;
   fWeightMatrix1to2[1][7] = 1.21284117506186;
   fWeightMatrix1to2[2][7] = 2.53903388224577;
   fWeightMatrix1to2[3][7] = -1.43781522451755;
   fWeightMatrix1to2[4][7] = -1.47319438249803;
   fWeightMatrix1to2[5][7] = 1.92947506853838;
   fWeightMatrix1to2[6][7] = 0.182081446177386;
   fWeightMatrix1to2[7][7] = -1.91239754213899;
   fWeightMatrix1to2[8][7] = 1.56141890666689;
   fWeightMatrix1to2[9][7] = 0.620527801292316;
   fWeightMatrix1to2[0][8] = -0.687935378945575;
   fWeightMatrix1to2[1][8] = -0.0614483878145558;
   fWeightMatrix1to2[2][8] = 1.40685258048476;
   fWeightMatrix1to2[3][8] = 1.03607110557622;
   fWeightMatrix1to2[4][8] = 0.535698462066314;
   fWeightMatrix1to2[5][8] = -0.0800466147550233;
   fWeightMatrix1to2[6][8] = -1.92762723645985;
   fWeightMatrix1to2[7][8] = -0.922598602652612;
   fWeightMatrix1to2[8][8] = 1.6942580250227;
   fWeightMatrix1to2[9][8] = 1.22194849972242;
   fWeightMatrix1to2[0][9] = -1.30629580003104;
   fWeightMatrix1to2[1][9] = 0.799979936270172;
   fWeightMatrix1to2[2][9] = 5.38625799220075;
   fWeightMatrix1to2[3][9] = -1.69322408826738;
   fWeightMatrix1to2[4][9] = -1.56762517749025;
   fWeightMatrix1to2[5][9] = 0.860800726613721;
   fWeightMatrix1to2[6][9] = -1.30106679096571;
   fWeightMatrix1to2[7][9] = 0.694455442439588;
   fWeightMatrix1to2[8][9] = 1.78960922548995;
   fWeightMatrix1to2[9][9] = -1.26159388057201;
   fWeightMatrix1to2[0][10] = 1.91008006420815;
   fWeightMatrix1to2[1][10] = 0.515528641988544;
   fWeightMatrix1to2[2][10] = -4.83651359569791;
   fWeightMatrix1to2[3][10] = -1.10297886932297;
   fWeightMatrix1to2[4][10] = 1.71980078729376;
   fWeightMatrix1to2[5][10] = -1.09275018423182;
   fWeightMatrix1to2[6][10] = 0.974124105899985;
   fWeightMatrix1to2[7][10] = -1.19049186340992;
   fWeightMatrix1to2[8][10] = 1.98867532127469;
   fWeightMatrix1to2[9][10] = -1.8914168952905;
   fWeightMatrix1to2[0][11] = 0.203141650733696;
   fWeightMatrix1to2[1][11] = 1.00332095101997;
   fWeightMatrix1to2[2][11] = -1.35635693792727;
   fWeightMatrix1to2[3][11] = -1.35683263010992;
   fWeightMatrix1to2[4][11] = -2.14135967913378;
   fWeightMatrix1to2[5][11] = 0.341538870288854;
   fWeightMatrix1to2[6][11] = -1.81672131888535;
   fWeightMatrix1to2[7][11] = -1.54706592657827;
   fWeightMatrix1to2[8][11] = -1.52558627845888;
   fWeightMatrix1to2[9][11] = -0.195415963463903;
   fWeightMatrix1to2[0][12] = -1.08469725936293;
   fWeightMatrix1to2[1][12] = -1.57887115817211;
   fWeightMatrix1to2[2][12] = 0.587939076695343;
   fWeightMatrix1to2[3][12] = -0.895218495063546;
   fWeightMatrix1to2[4][12] = 0.153400963521839;
   fWeightMatrix1to2[5][12] = -1.03399916611599;
   fWeightMatrix1to2[6][12] = 0.211285285880989;
   fWeightMatrix1to2[7][12] = 1.93031613636026;
   fWeightMatrix1to2[8][12] = 1.743055486265;
   fWeightMatrix1to2[9][12] = -1.14551825417445;
   fWeightMatrix1to2[0][13] = -1.41852904936173;
   fWeightMatrix1to2[1][13] = -1.03766870889308;
   fWeightMatrix1to2[2][13] = -1.36915550529328;
   fWeightMatrix1to2[3][13] = -1.63819041556454;
   fWeightMatrix1to2[4][13] = 0.536380311814748;
   fWeightMatrix1to2[5][13] = 0.209472467051153;
   fWeightMatrix1to2[6][13] = 1.90970882853387;
   fWeightMatrix1to2[7][13] = -0.382462897633301;
   fWeightMatrix1to2[8][13] = 0.571426780930621;
   fWeightMatrix1to2[9][13] = -0.635392857576538;
   fWeightMatrix1to2[0][14] = -2.29990308860522;
   fWeightMatrix1to2[1][14] = 1.79657199237131;
   fWeightMatrix1to2[2][14] = 1.1888569727099;
   fWeightMatrix1to2[3][14] = -0.917827481227389;
   fWeightMatrix1to2[4][14] = -1.41013806262614;
   fWeightMatrix1to2[5][14] = 1.27064022821111;
   fWeightMatrix1to2[6][14] = 1.24430810556973;
   fWeightMatrix1to2[7][14] = 0.567196285433474;
   fWeightMatrix1to2[8][14] = -0.0299684852778498;
   fWeightMatrix1to2[9][14] = -0.671534455289857;
   // weight matrix from layer 2 to 3
   fWeightMatrix2to3[0][0] = 1.66430289226089;
   fWeightMatrix2to3[1][0] = 1.4477889211862;
   fWeightMatrix2to3[2][0] = 1.52023787194239;
   fWeightMatrix2to3[3][0] = -0.416142607125903;
   fWeightMatrix2to3[4][0] = -0.57051612605836;
   fWeightMatrix2to3[5][0] = -0.910077829600644;
   fWeightMatrix2to3[6][0] = -1.52154427232726;
   fWeightMatrix2to3[7][0] = -0.466926138425662;
   fWeightMatrix2to3[8][0] = -3.64037640685991;
   fWeightMatrix2to3[0][1] = -1.32986396291351;
   fWeightMatrix2to3[1][1] = -1.6572752709206;
   fWeightMatrix2to3[2][1] = 1.58934603877372;
   fWeightMatrix2to3[3][1] = -2.10364893163046;
   fWeightMatrix2to3[4][1] = 1.06105045832768;
   fWeightMatrix2to3[5][1] = -2.29810458960365;
   fWeightMatrix2to3[6][1] = 1.44705000029831;
   fWeightMatrix2to3[7][1] = -2.30856643227212;
   fWeightMatrix2to3[8][1] = 4.2143898137403;
   fWeightMatrix2to3[0][2] = 0.910316666102657;
   fWeightMatrix2to3[1][2] = -2.44283194582589;
   fWeightMatrix2to3[2][2] = -1.05130854581676;
   fWeightMatrix2to3[3][2] = 0.588890698914291;
   fWeightMatrix2to3[4][2] = -2.19241036753;
   fWeightMatrix2to3[5][2] = -2.07577146675205;
   fWeightMatrix2to3[6][2] = -1.62240375891105;
   fWeightMatrix2to3[7][2] = -1.13164600877069;
   fWeightMatrix2to3[8][2] = 5.72173781199825;
   fWeightMatrix2to3[0][3] = -0.557306352360976;
   fWeightMatrix2to3[1][3] = 0.286328626664226;
   fWeightMatrix2to3[2][3] = -0.876199276104862;
   fWeightMatrix2to3[3][3] = -1.18015064302618;
   fWeightMatrix2to3[4][3] = -1.71365971442375;
   fWeightMatrix2to3[5][3] = -0.998762669116969;
   fWeightMatrix2to3[6][3] = -1.39714601173202;
   fWeightMatrix2to3[7][3] = 0.933873837648006;
   fWeightMatrix2to3[8][3] = -1.31807256016541;
   fWeightMatrix2to3[0][4] = -1.23474509780285;
   fWeightMatrix2to3[1][4] = 1.62300132368572;
   fWeightMatrix2to3[2][4] = 0.173862302734175;
   fWeightMatrix2to3[3][4] = -1.03501921200872;
   fWeightMatrix2to3[4][4] = 1.69036510926172;
   fWeightMatrix2to3[5][4] = -1.77193186129222;
   fWeightMatrix2to3[6][4] = 1.09482087337271;
   fWeightMatrix2to3[7][4] = 0.873871381335859;
   fWeightMatrix2to3[8][4] = -2.95479364571196;
   fWeightMatrix2to3[0][5] = -0.680749320268476;
   fWeightMatrix2to3[1][5] = -0.360879165140607;
   fWeightMatrix2to3[2][5] = -1.90448858385963;
   fWeightMatrix2to3[3][5] = -0.0542643658339665;
   fWeightMatrix2to3[4][5] = 1.53664843159285;
   fWeightMatrix2to3[5][5] = 1.2710502018189;
   fWeightMatrix2to3[6][5] = 1.69275347222775;
   fWeightMatrix2to3[7][5] = -1.9674380151921;
   fWeightMatrix2to3[8][5] = 2.78473057016163;
   fWeightMatrix2to3[0][6] = -1.69219119466577;
   fWeightMatrix2to3[1][6] = 0.43626466367707;
   fWeightMatrix2to3[2][6] = -1.82143597992074;
   fWeightMatrix2to3[3][6] = -2.4816192676783;
   fWeightMatrix2to3[4][6] = -0.991249793713893;
   fWeightMatrix2to3[5][6] = 0.977343677658326;
   fWeightMatrix2to3[6][6] = 0.1828792739587;
   fWeightMatrix2to3[7][6] = -0.0631264607340722;
   fWeightMatrix2to3[8][6] = -0.00306806768769215;
   fWeightMatrix2to3[0][7] = -0.0605258439598078;
   fWeightMatrix2to3[1][7] = -0.949282423736304;
   fWeightMatrix2to3[2][7] = -0.0850321412597986;
   fWeightMatrix2to3[3][7] = 1.26595563562621;
   fWeightMatrix2to3[4][7] = -2.1569744307455;
   fWeightMatrix2to3[5][7] = 0.330737860134079;
   fWeightMatrix2to3[6][7] = -1.55057608862778;
   fWeightMatrix2to3[7][7] = -0.423335924297224;
   fWeightMatrix2to3[8][7] = -0.431599837082527;
   fWeightMatrix2to3[0][8] = 0.428306666524964;
   fWeightMatrix2to3[1][8] = -1.32495441811733;
   fWeightMatrix2to3[2][8] = 0.845608527658341;
   fWeightMatrix2to3[3][8] = 1.00071055840864;
   fWeightMatrix2to3[4][8] = -0.284367154175562;
   fWeightMatrix2to3[5][8] = -0.505666165629613;
   fWeightMatrix2to3[6][8] = -1.13461691275259;
   fWeightMatrix2to3[7][8] = -2.43737941828303;
   fWeightMatrix2to3[8][8] = -1.75936268488474;
   fWeightMatrix2to3[0][9] = 1.02967341861358;
   fWeightMatrix2to3[1][9] = -0.482379900430983;
   fWeightMatrix2to3[2][9] = -1.09647553529451;
   fWeightMatrix2to3[3][9] = 0.533244280247326;
   fWeightMatrix2to3[4][9] = -1.72362888850959;
   fWeightMatrix2to3[5][9] = -1.24721870034635;
   fWeightMatrix2to3[6][9] = -1.65792757624205;
   fWeightMatrix2to3[7][9] = 0.773310030241878;
   fWeightMatrix2to3[8][9] = -0.982978287563379;
   fWeightMatrix2to3[0][10] = -1.51692385682852;
   fWeightMatrix2to3[1][10] = -0.79274413787703;
   fWeightMatrix2to3[2][10] = -1.14001664611921;
   fWeightMatrix2to3[3][10] = -2.26775747679536;
   fWeightMatrix2to3[4][10] = 0.2930663260468;
   fWeightMatrix2to3[5][10] = -1.72313617669206;
   fWeightMatrix2to3[6][10] = -1.4988721693493;
   fWeightMatrix2to3[7][10] = 0.531720394429844;
   fWeightMatrix2to3[8][10] = 0.450567564169081;
   // weight matrix from layer 3 to 4
   fWeightMatrix3to4[0][0] = 0.729818591344252;
   fWeightMatrix3to4[0][1] = 0.824225041683943;
   fWeightMatrix3to4[0][2] = 1.36414392142039;
   fWeightMatrix3to4[0][3] = 1.19823955104077;
   fWeightMatrix3to4[0][4] = -0.369546039891863;
   fWeightMatrix3to4[0][5] = -1.31570279589492;
   fWeightMatrix3to4[0][6] = 0.512924323055736;
   fWeightMatrix3to4[0][7] = -1.11740920418465;
   fWeightMatrix3to4[0][8] = 1.1668319606655;
   fWeightMatrix3to4[0][9] = -0.231812548403501;
}

inline double Read3 Layers, 33 Nodes Increasing::GetMvaValue__( const std::vector<double>& inputValues ) const
{
   if (inputValues.size() != (unsigned int)fLayerSize[0]-1) {
      std::cout << "Input vector needs to be of size " << fLayerSize[0]-1 << std::endl;
      return 0;
   }

   for (int l=0; l<fLayers; l++)
      for (int i=0; i<fLayerSize[l]; i++) fWeights[l][i]=0;

   for (int l=0; l<fLayers-1; l++)
      fWeights[l][fLayerSize[l]-1]=1;

   for (int i=0; i<fLayerSize[0]-1; i++)
      fWeights[0][i]=inputValues[i];

   // layer 0 to 1
   for (int o=0; o<fLayerSize[1]-1; o++) {
      for (int i=0; i<fLayerSize[0]; i++) {
         double inputVal = fWeightMatrix0to1[o][i] * fWeights[0][i];
         fWeights[1][o] += inputVal;
      }
      fWeights[1][o] = ActivationFnc(fWeights[1][o]);
   }
   // layer 1 to 2
   for (int o=0; o<fLayerSize[2]-1; o++) {
      for (int i=0; i<fLayerSize[1]; i++) {
         double inputVal = fWeightMatrix1to2[o][i] * fWeights[1][i];
         fWeights[2][o] += inputVal;
      }
      fWeights[2][o] = ActivationFnc(fWeights[2][o]);
   }
   // layer 2 to 3
   for (int o=0; o<fLayerSize[3]-1; o++) {
      for (int i=0; i<fLayerSize[2]; i++) {
         double inputVal = fWeightMatrix2to3[o][i] * fWeights[2][i];
         fWeights[3][o] += inputVal;
      }
      fWeights[3][o] = ActivationFnc(fWeights[3][o]);
   }
   // layer 3 to 4
   for (int o=0; o<fLayerSize[4]; o++) {
      for (int i=0; i<fLayerSize[3]; i++) {
         double inputVal = fWeightMatrix3to4[o][i] * fWeights[3][i];
         fWeights[4][o] += inputVal;
      }
      fWeights[4][o] = OutputActivationFnc(fWeights[4][o]);
   }

   return fWeights[4][0];
}

double Read3 Layers, 33 Nodes Increasing::ActivationFnc(double x) const {
   // sigmoid
   return 1.0/(1.0+exp(-x));
}
double Read3 Layers, 33 Nodes Increasing::OutputActivationFnc(double x) const {
   // identity
   return x;
}
   
// Clean up
inline void Read3 Layers, 33 Nodes Increasing::Clear() 
{
   // clean up the arrays
   for (int lIdx = 0; lIdx < 5; lIdx++) {
      delete[] fWeights[lIdx];
   }
}
   inline double Read3 Layers, 33 Nodes Increasing::GetMvaValue( const std::vector<double>& inputValues ) const
   {
      // classifier response value
      double retval = 0;

      // classifier response, sanity check first
      if (!IsStatusClean()) {
         std::cout << "Problem in class \"" << fClassName << "\": cannot return classifier response"
                   << " because status is dirty" << std::endl;
         retval = 0;
      }
      else {
         if (IsNormalised()) {
            // normalise variables
            std::vector<double> iV;
            iV.resize(inputValues.size());
            int ivar = 0;
            for (std::vector<double>::const_iterator varIt = inputValues.begin();
                 varIt != inputValues.end(); varIt++, ivar++) {
               iV.push_back(NormVariable( *varIt, fVmin[ivar], fVmax[ivar] ));
            }
            Transform( iV, -1 );
            retval = GetMvaValue__( iV );
         }
         else {
            std::vector<double> iV;
            int ivar = 0;
            for (std::vector<double>::const_iterator varIt = inputValues.begin();
                 varIt != inputValues.end(); varIt++, ivar++) {
               iV.push_back(*varIt);
            }
            Transform( iV, -1 );
            retval = GetMvaValue__( iV );
         }
      }

      return retval;
   }

//_______________________________________________________________________
inline void Read3 Layers, 33 Nodes Increasing::InitTransform_1()
{
   // Normalization transformation, initialisation
   fMin_1[0][0] = 5;
   fMax_1[0][0] = 2543.40991211;
   fMin_1[1][0] = 4.73000001907;
   fMax_1[1][0] = 817.520019531;
   fMin_1[2][0] = 4.73000001907;
   fMax_1[2][0] = 2543.40991211;
   fMin_1[0][1] = -3.99099993706;
   fMax_1[0][1] = 3.99099993706;
   fMin_1[1][1] = -3.99300003052;
   fMax_1[1][1] = 3.99000000954;
   fMin_1[2][1] = -3.99300003052;
   fMax_1[2][1] = 3.99099993706;
   fMin_1[0][2] = 0;
   fMax_1[0][2] = 6.28299999237;
   fMin_1[1][2] = 0;
   fMax_1[1][2] = 6.28299999237;
   fMin_1[2][2] = 0;
   fMax_1[2][2] = 6.28299999237;
   fMin_1[0][3] = 0;
   fMax_1[0][3] = 258.730010986;
   fMin_1[1][3] = 0;
   fMax_1[1][3] = 159.369995117;
   fMin_1[2][3] = 0;
   fMax_1[2][3] = 258.730010986;
   fMin_1[0][4] = 0;
   fMax_1[0][4] = 61;
   fMin_1[1][4] = 0;
   fMax_1[1][4] = 59;
   fMin_1[2][4] = 0;
   fMax_1[2][4] = 61;
   fMin_1[0][5] = 0;
   fMax_1[0][5] = 999;
   fMin_1[1][5] = 0;
   fMax_1[1][5] = 999;
   fMin_1[2][5] = 0;
   fMax_1[2][5] = 999;
   fMin_1[0][6] = 0;
   fMax_1[0][6] = 6.28299999237;
   fMin_1[1][6] = 0.0010000000475;
   fMax_1[1][6] = 6.28200006485;
   fMin_1[2][6] = 0;
   fMax_1[2][6] = 6.28299999237;
   fMin_1[0][7] = 100.019996643;
   fMax_1[0][7] = 1585.47998047;
   fMin_1[1][7] = 100.010002136;
   fMax_1[1][7] = 662.650024414;
   fMin_1[2][7] = 100.010002136;
   fMax_1[2][7] = 1585.47998047;
}

//_______________________________________________________________________
inline void Read3 Layers, 33 Nodes Increasing::Transform_1( std::vector<double>& iv, int cls) const
{
   // Normalization transformation
   if (cls < 0 || cls > 2) {
   if (2 > 1 ) cls = 2;
      else cls = 2;
   }
   const int nVar = 8;

   // get indices of used variables

   // define the indices of the variables which are transformed by this transformation
   static std::vector<int> indicesGet;
   static std::vector<int> indicesPut;

   if ( indicesGet.empty() ) { 
      indicesGet.reserve(nVar);
      indicesGet.push_back( 0);
      indicesGet.push_back( 1);
      indicesGet.push_back( 2);
      indicesGet.push_back( 3);
      indicesGet.push_back( 4);
      indicesGet.push_back( 5);
      indicesGet.push_back( 6);
      indicesGet.push_back( 7);
   } 
   if ( indicesPut.empty() ) { 
      indicesPut.reserve(nVar);
      indicesPut.push_back( 0);
      indicesPut.push_back( 1);
      indicesPut.push_back( 2);
      indicesPut.push_back( 3);
      indicesPut.push_back( 4);
      indicesPut.push_back( 5);
      indicesPut.push_back( 6);
      indicesPut.push_back( 7);
   } 

   static std::vector<double> dv;
   dv.resize(nVar);
   for (int ivar=0; ivar<nVar; ivar++) dv[ivar] = iv[indicesGet.at(ivar)];
   for (int ivar=0;ivar<8;ivar++) {
      double offset = fMin_1[cls][ivar];
      double scale  = 1.0/(fMax_1[cls][ivar]-fMin_1[cls][ivar]);
      iv[indicesPut.at(ivar)] = (dv[ivar]-offset)*scale * 2 - 1;
   }
}

//_______________________________________________________________________
inline void Read3 Layers, 33 Nodes Increasing::InitTransform()
{
   InitTransform_1();
}

//_______________________________________________________________________
inline void Read3 Layers, 33 Nodes Increasing::Transform( std::vector<double>& iv, int sigOrBgd ) const
{
   Transform_1( iv, sigOrBgd );
}
