// Class: Read1Layer20Nodes
// Automatically generated by MethodBase::MakeClass
//

/* configuration options =====================================================

#GEN -*-*-*-*-*-*-*-*-*-*-*- general info -*-*-*-*-*-*-*-*-*-*-*-

Method         : MLP::1Layer20Nodes
TMVA Release   : 4.2.0         [262656]
ROOT Release   : 5.34/18       [336402]
Creator        : zxb0111
Date           : Sat Dec  6 22:30:41 2014
Host           : Linux localhost.localdomain 2.6.32-431.17.1.el6.x86_64 #1 SMP Wed May 7 14:14:17 CDT 2014 x86_64 x86_64 x86_64 GNU/Linux
Dir            : /home/zxb0111/seminar
Training events: 34086
Analysis type  : [Classification]


#OPT -*-*-*-*-*-*-*-*-*-*-*-*- options -*-*-*-*-*-*-*-*-*-*-*-*-

# Set by User:
NCycles: "600" [Number of training cycles]
HiddenLayers: "20" [Specification of hidden layer architecture]
NeuronType: "sigmoid" [Neuron activation function type]
VarTransform: "N" [List of variable transformations performed before training, e.g., "D_Background,P_Signal,G,N_AllClasses" for: "Decorrelation, PCA-transformation, Gaussianisation, Normalisation, each for the given class of events ('AllClasses' denotes all events of all classes, if no class indication is given, 'All' is assumed)"]
TestRate: "5" [Test for overtraining performed at each #th epochs]
UseRegulator: "False" [Use regulator to avoid over-training]
# Default:
RandomSeed: "1" [Random seed for initial synapse weights (0 means unique seed for each run; default value '1')]
EstimatorType: "MSE" [MSE (Mean Square Estimator) for Gaussian Likelihood or CE(Cross-Entropy) for Bernoulli Likelihood]
NeuronInputType: "sum" [Neuron input function type]
V: "False" [Verbose output (short form of "VerbosityLevel" below - overrides the latter one)]
VerbosityLevel: "Default" [Verbosity level]
H: "False" [Print method-specific help message]
CreateMVAPdfs: "False" [Create PDFs for classifier outputs (signal and background)]
IgnoreNegWeightsInTraining: "False" [Events with negative weights are ignored in the training (but are included for testing and performance evaluation)]
TrainingMethod: "BP" [Train with Back-Propagation (BP), BFGS Algorithm (BFGS), or Genetic Algorithm (GA - slower and worse)]
LearningRate: "2.000000e-02" [ANN learning rate parameter]
DecayRate: "1.000000e-02" [Decay rate for learning parameter]
EpochMonitoring: "False" [Provide epoch-wise monitoring plots according to TestRate (caution: causes big ROOT output file!)]
Sampling: "1.000000e+00" [Only 'Sampling' (randomly selected) events are trained each epoch]
SamplingEpoch: "1.000000e+00" [Sampling is used for the first 'SamplingEpoch' epochs, afterwards, all events are taken for training]
SamplingImportance: "1.000000e+00" [ The sampling weights of events in epochs which successful (worse estimator than before) are multiplied with SamplingImportance, else they are divided.]
SamplingTraining: "True" [The training sample is sampled]
SamplingTesting: "False" [The testing sample is sampled]
ResetStep: "50" [How often BFGS should reset history]
Tau: "3.000000e+00" [LineSearch "size step"]
BPMode: "sequential" [Back-propagation learning mode: sequential or batch]
BatchSize: "-1" [Batch size: number of events/batch, only set if in Batch Mode, -1 for BatchSize=number_of_events]
ConvergenceImprove: "1.000000e-30" [Minimum improvement which counts as improvement (<0 means automatic convergence check is turned off)]
ConvergenceTests: "-1" [Number of steps (without improvement) required for convergence (<0 means automatic convergence check is turned off)]
UpdateLimit: "10000" [Maximum times of regulator update]
CalculateErrors: "False" [Calculates inverse Hessian matrix at the end of the training to be able to calculate the uncertainties of an MVA value]
WeightRange: "1.000000e+00" [Take the events for the estimator calculations from small deviations from the desired value to large deviations only over the weight range]
##


#VAR -*-*-*-*-*-*-*-*-*-*-*-* variables *-*-*-*-*-*-*-*-*-*-*-*-

NVar 8
Jet.PT                        Jet.PT                        Jet.PT                        Jet.PT                                                          'F'    [4.73000001907,2543.40991211]
Jet.Eta                       Jet.Eta                       Jet.Eta                       Jet.Eta                                                         'F'    [-3.99300003052,3.99099993706]
Jet.Phi                       Jet.Phi                       Jet.Phi                       Jet.Phi                                                         'F'    [0,6.28299999237]
Jet.Mass                      Jet.Mass                      Jet.Mass                      Jet.Mass                                                        'F'    [0,258.730010986]
Jet.Ntrk                      Jet.Ntrk                      Jet.Ntrk                      Jet.Ntrk                                                        'F'    [0,61]
Jet.EhadOverEem               Jet.EhadOverEem               Jet.EhadOverEem               Jet.EhadOverEem                                                 'F'    [0,999]
MissingET.Phi                 MissingET.Phi                 MissingET.Phi                 MissingET.Phi                                                   'F'    [0,6.28299999237]
MissingET.MET                 MissingET.MET                 MissingET.MET                 MissingET.MET                                                   'F'    [100.010002136,1585.47998047]
NSpec 0


============================================================================ */

#include <vector>
#include <cmath>
#include <string>
#include <iostream>

#ifndef IClassifierReader__def
#define IClassifierReader__def

class IClassifierReader {

 public:

   // constructor
   IClassifierReader() : fStatusIsClean( true ) {}
   virtual ~IClassifierReader() {}

   // return classifier response
   virtual double GetMvaValue( const std::vector<double>& inputValues ) const = 0;

   // returns classifier status
   bool IsStatusClean() const { return fStatusIsClean; }

 protected:

   bool fStatusIsClean;
};

#endif

class Read1Layer20Nodes : public IClassifierReader {

 public:

   // constructor
   Read1Layer20Nodes( std::vector<std::string>& theInputVars ) 
      : IClassifierReader(),
        fClassName( "Read1Layer20Nodes" ),
        fNvars( 8 ),
        fIsNormalised( false )
   {      
      // the training input variables
      const char* inputVars[] = { "Jet.PT", "Jet.Eta", "Jet.Phi", "Jet.Mass", "Jet.Ntrk", "Jet.EhadOverEem", "MissingET.Phi", "MissingET.MET" };

      // sanity checks
      if (theInputVars.size() <= 0) {
         std::cout << "Problem in class \"" << fClassName << "\": empty input vector" << std::endl;
         fStatusIsClean = false;
      }

      if (theInputVars.size() != fNvars) {
         std::cout << "Problem in class \"" << fClassName << "\": mismatch in number of input values: "
                   << theInputVars.size() << " != " << fNvars << std::endl;
         fStatusIsClean = false;
      }

      // validate input variables
      for (size_t ivar = 0; ivar < theInputVars.size(); ivar++) {
         if (theInputVars[ivar] != inputVars[ivar]) {
            std::cout << "Problem in class \"" << fClassName << "\": mismatch in input variable names" << std::endl
                      << " for variable [" << ivar << "]: " << theInputVars[ivar].c_str() << " != " << inputVars[ivar] << std::endl;
            fStatusIsClean = false;
         }
      }

      // initialize min and max vectors (for normalisation)
      fVmin[0] = -1;
      fVmax[0] = 1;
      fVmin[1] = -1;
      fVmax[1] = 1;
      fVmin[2] = -1;
      fVmax[2] = 0.99999988079071;
      fVmin[3] = -1;
      fVmax[3] = 1;
      fVmin[4] = -1;
      fVmax[4] = 0.99999988079071;
      fVmin[5] = -1;
      fVmax[5] = 1;
      fVmin[6] = -1;
      fVmax[6] = 0.99999988079071;
      fVmin[7] = -1;
      fVmax[7] = 1;

      // initialize input variable types
      fType[0] = 'F';
      fType[1] = 'F';
      fType[2] = 'F';
      fType[3] = 'F';
      fType[4] = 'F';
      fType[5] = 'F';
      fType[6] = 'F';
      fType[7] = 'F';

      // initialize constants
      Initialize();

      // initialize transformation
      InitTransform();
   }

   // destructor
   virtual ~Read1Layer20Nodes() {
      Clear(); // method-specific
   }

   // the classifier response
   // "inputValues" is a vector of input values in the same order as the 
   // variables given to the constructor
   double GetMvaValue( const std::vector<double>& inputValues ) const;

 private:

   // method-specific destructor
   void Clear();

   // input variable transformation

   double fMin_1[3][8];
   double fMax_1[3][8];
   void InitTransform_1();
   void Transform_1( std::vector<double> & iv, int sigOrBgd ) const;
   void InitTransform();
   void Transform( std::vector<double> & iv, int sigOrBgd ) const;

   // common member variables
   const char* fClassName;

   const size_t fNvars;
   size_t GetNvar()           const { return fNvars; }
   char   GetType( int ivar ) const { return fType[ivar]; }

   // normalisation of input variables
   const bool fIsNormalised;
   bool IsNormalised() const { return fIsNormalised; }
   double fVmin[8];
   double fVmax[8];
   double NormVariable( double x, double xmin, double xmax ) const {
      // normalise to output range: [-1, 1]
      return 2*(x - xmin)/(xmax - xmin) - 1.0;
   }

   // type of input variable: 'F' or 'I'
   char   fType[8];

   // initialize internal variables
   void Initialize();
   double GetMvaValue__( const std::vector<double>& inputValues ) const;

   // private members (method specific)

   double ActivationFnc(double x) const;
   double OutputActivationFnc(double x) const;

   int fLayers;
   int fLayerSize[3];
   double fWeightMatrix0to1[21][9];   // weight matrix from layer 0 to 1
   double fWeightMatrix1to2[1][21];   // weight matrix from layer 1 to 2

   double * fWeights[3];
};

inline void Read1Layer20Nodes::Initialize()
{
   // build network structure
   fLayers = 3;
   fLayerSize[0] = 9; fWeights[0] = new double[9]; 
   fLayerSize[1] = 21; fWeights[1] = new double[21]; 
   fLayerSize[2] = 1; fWeights[2] = new double[1]; 
   // weight matrix from layer 0 to 1
   fWeightMatrix0to1[0][0] = -1.95676945620353;
   fWeightMatrix0to1[1][0] = 3.39105673416982;
   fWeightMatrix0to1[2][0] = 1.80757761293509;
   fWeightMatrix0to1[3][0] = 2.48907574082855;
   fWeightMatrix0to1[4][0] = -2.2800397302196;
   fWeightMatrix0to1[5][0] = -0.774728543467561;
   fWeightMatrix0to1[6][0] = -0.456656951726229;
   fWeightMatrix0to1[7][0] = 0.610820589629396;
   fWeightMatrix0to1[8][0] = -1.05852804379337;
   fWeightMatrix0to1[9][0] = -0.270714006604095;
   fWeightMatrix0to1[10][0] = -1.62063105626041;
   fWeightMatrix0to1[11][0] = 0.596973410196149;
   fWeightMatrix0to1[12][0] = -1.57395846782487;
   fWeightMatrix0to1[13][0] = 0.776328568881902;
   fWeightMatrix0to1[14][0] = 0.503751224000961;
   fWeightMatrix0to1[15][0] = 0.867177471056053;
   fWeightMatrix0to1[16][0] = -0.702707306133964;
   fWeightMatrix0to1[17][0] = 2.48845438513459;
   fWeightMatrix0to1[18][0] = 0.0499845067167368;
   fWeightMatrix0to1[19][0] = -2.88273976700065;
   fWeightMatrix0to1[0][1] = -0.74226135296871;
   fWeightMatrix0to1[1][1] = 0.395912543062494;
   fWeightMatrix0to1[2][1] = 0.571593199012903;
   fWeightMatrix0to1[3][1] = 0.511027686151404;
   fWeightMatrix0to1[4][1] = -0.0802188010138558;
   fWeightMatrix0to1[5][1] = 0.102705452217732;
   fWeightMatrix0to1[6][1] = 1.35336988421682;
   fWeightMatrix0to1[7][1] = -2.10780032517585;
   fWeightMatrix0to1[8][1] = -0.619720500245455;
   fWeightMatrix0to1[9][1] = 0.000963346927731467;
   fWeightMatrix0to1[10][1] = 0.687679843247418;
   fWeightMatrix0to1[11][1] = 1.17085596291538;
   fWeightMatrix0to1[12][1] = 0.162316333458115;
   fWeightMatrix0to1[13][1] = -0.194355504529221;
   fWeightMatrix0to1[14][1] = 0.300344244233661;
   fWeightMatrix0to1[15][1] = -0.357109173133463;
   fWeightMatrix0to1[16][1] = -0.982247924991886;
   fWeightMatrix0to1[17][1] = 0.895382044448609;
   fWeightMatrix0to1[18][1] = -1.15839332278369;
   fWeightMatrix0to1[19][1] = 0.0349633275029659;
   fWeightMatrix0to1[0][2] = 2.59898261720645;
   fWeightMatrix0to1[1][2] = -0.129064052826564;
   fWeightMatrix0to1[2][2] = 0.327700559643255;
   fWeightMatrix0to1[3][2] = 0.794348797513648;
   fWeightMatrix0to1[4][2] = 0.0113919758932633;
   fWeightMatrix0to1[5][2] = -1.61975403667802;
   fWeightMatrix0to1[6][2] = 0.350237768736028;
   fWeightMatrix0to1[7][2] = 0.0243630438683598;
   fWeightMatrix0to1[8][2] = 2.66761532046985;
   fWeightMatrix0to1[9][2] = 1.04252335317156;
   fWeightMatrix0to1[10][2] = 1.58128858904245;
   fWeightMatrix0to1[11][2] = 2.24897814959268;
   fWeightMatrix0to1[12][2] = -0.745215741422907;
   fWeightMatrix0to1[13][2] = 2.93343571149288;
   fWeightMatrix0to1[14][2] = -1.72689605695133;
   fWeightMatrix0to1[15][2] = -0.749239269513271;
   fWeightMatrix0to1[16][2] = -2.84665805488082;
   fWeightMatrix0to1[17][2] = -1.18598445536252;
   fWeightMatrix0to1[18][2] = 0.519880996086403;
   fWeightMatrix0to1[19][2] = 0.042669782478128;
   fWeightMatrix0to1[0][3] = -1.96648251145474;
   fWeightMatrix0to1[1][3] = -0.296793798497155;
   fWeightMatrix0to1[2][3] = -0.0675773347818389;
   fWeightMatrix0to1[3][3] = 1.4666425823258;
   fWeightMatrix0to1[4][3] = 0.477319598322711;
   fWeightMatrix0to1[5][3] = -0.0729458875389526;
   fWeightMatrix0to1[6][3] = 0.623072087962244;
   fWeightMatrix0to1[7][3] = -1.64630971966502;
   fWeightMatrix0to1[8][3] = 0.56215765870359;
   fWeightMatrix0to1[9][3] = -0.129575003573468;
   fWeightMatrix0to1[10][3] = -0.789919981810645;
   fWeightMatrix0to1[11][3] = -1.0524851641504;
   fWeightMatrix0to1[12][3] = -0.721663970983801;
   fWeightMatrix0to1[13][3] = 1.97854879907453;
   fWeightMatrix0to1[14][3] = 2.50873477575596;
   fWeightMatrix0to1[15][3] = -0.222032243900087;
   fWeightMatrix0to1[16][3] = -2.24440661773917;
   fWeightMatrix0to1[17][3] = -1.59065965144542;
   fWeightMatrix0to1[18][3] = 1.07400509487107;
   fWeightMatrix0to1[19][3] = 0.55847014166725;
   fWeightMatrix0to1[0][4] = 0.471629352896533;
   fWeightMatrix0to1[1][4] = 0.80957613528613;
   fWeightMatrix0to1[2][4] = 1.40694620449801;
   fWeightMatrix0to1[3][4] = -0.511077893518649;
   fWeightMatrix0to1[4][4] = -0.499107392960713;
   fWeightMatrix0to1[5][4] = -0.612568169345798;
   fWeightMatrix0to1[6][4] = 1.30701026893026;
   fWeightMatrix0to1[7][4] = -1.17579357223709;
   fWeightMatrix0to1[8][4] = -0.49436095274151;
   fWeightMatrix0to1[9][4] = -1.26333419806385;
   fWeightMatrix0to1[10][4] = -0.242743563309383;
   fWeightMatrix0to1[11][4] = 0.381519467102469;
   fWeightMatrix0to1[12][4] = 0.388561326546821;
   fWeightMatrix0to1[13][4] = 0.220763734906141;
   fWeightMatrix0to1[14][4] = -0.0953948071924484;
   fWeightMatrix0to1[15][4] = 1.56691591676987;
   fWeightMatrix0to1[16][4] = -0.380130132403062;
   fWeightMatrix0to1[17][4] = -1.12313061405849;
   fWeightMatrix0to1[18][4] = -2.29342713932269;
   fWeightMatrix0to1[19][4] = -0.75395152556466;
   fWeightMatrix0to1[0][5] = -1.62736806156188;
   fWeightMatrix0to1[1][5] = -3.99103961653431;
   fWeightMatrix0to1[2][5] = 1.38685405140333;
   fWeightMatrix0to1[3][5] = 1.38185980570084;
   fWeightMatrix0to1[4][5] = 3.3546311408062;
   fWeightMatrix0to1[5][5] = 2.01819164480287;
   fWeightMatrix0to1[6][5] = -0.677778901901689;
   fWeightMatrix0to1[7][5] = -0.283453834399492;
   fWeightMatrix0to1[8][5] = -0.0222137758565767;
   fWeightMatrix0to1[9][5] = 1.26943656949903;
   fWeightMatrix0to1[10][5] = -1.67094230577841;
   fWeightMatrix0to1[11][5] = -0.180248187187948;
   fWeightMatrix0to1[12][5] = 0.333566871927774;
   fWeightMatrix0to1[13][5] = 0.507889446557673;
   fWeightMatrix0to1[14][5] = 0.187200266077322;
   fWeightMatrix0to1[15][5] = 2.02894989487039;
   fWeightMatrix0to1[16][5] = -1.21053245708786;
   fWeightMatrix0to1[17][5] = -0.590680195439961;
   fWeightMatrix0to1[18][5] = 1.36418407744722;
   fWeightMatrix0to1[19][5] = 1.56960232841189;
   fWeightMatrix0to1[0][6] = -2.61112017389411;
   fWeightMatrix0to1[1][6] = -0.136630589646299;
   fWeightMatrix0to1[2][6] = 1.01770707243433;
   fWeightMatrix0to1[3][6] = 0.78421022412938;
   fWeightMatrix0to1[4][6] = -0.0120528500746535;
   fWeightMatrix0to1[5][6] = 0.552684271614537;
   fWeightMatrix0to1[6][6] = -0.210992790485136;
   fWeightMatrix0to1[7][6] = 0.2476939701032;
   fWeightMatrix0to1[8][6] = -2.69691250801415;
   fWeightMatrix0to1[9][6] = 0.449781626992731;
   fWeightMatrix0to1[10][6] = 0.0287358017763719;
   fWeightMatrix0to1[11][6] = -2.66535020900777;
   fWeightMatrix0to1[12][6] = 0.699011067944417;
   fWeightMatrix0to1[13][6] = -2.88904731143453;
   fWeightMatrix0to1[14][6] = -0.0729369213633387;
   fWeightMatrix0to1[15][6] = 0.779565465466016;
   fWeightMatrix0to1[16][6] = 2.90391894873988;
   fWeightMatrix0to1[17][6] = -1.08141212956282;
   fWeightMatrix0to1[18][6] = 0.131005585576934;
   fWeightMatrix0to1[19][6] = -0.146511430812492;
   fWeightMatrix0to1[0][7] = 1.43851544557243;
   fWeightMatrix0to1[1][7] = 6.06480192809761;
   fWeightMatrix0to1[2][7] = -0.95041360052407;
   fWeightMatrix0to1[3][7] = 0.293495942580496;
   fWeightMatrix0to1[4][7] = -5.65418676321615;
   fWeightMatrix0to1[5][7] = 2.05927909211016;
   fWeightMatrix0to1[6][7] = 1.82407189626013;
   fWeightMatrix0to1[7][7] = 0.767996950258799;
   fWeightMatrix0to1[8][7] = 0.43010188258859;
   fWeightMatrix0to1[9][7] = 1.09396309084861;
   fWeightMatrix0to1[10][7] = -1.34872636095214;
   fWeightMatrix0to1[11][7] = 0.198958672424902;
   fWeightMatrix0to1[12][7] = 3.12672602769581;
   fWeightMatrix0to1[13][7] = -2.80811214448038;
   fWeightMatrix0to1[14][7] = 0.281131561875084;
   fWeightMatrix0to1[15][7] = 0.447433924790955;
   fWeightMatrix0to1[16][7] = 1.62868373099283;
   fWeightMatrix0to1[17][7] = 1.27275134356073;
   fWeightMatrix0to1[18][7] = 1.10369723159331;
   fWeightMatrix0to1[19][7] = -9.19457440036584;
   fWeightMatrix0to1[0][8] = 1.28860810295383;
   fWeightMatrix0to1[1][8] = 4.58605549130198;
   fWeightMatrix0to1[2][8] = 0.167140184152681;
   fWeightMatrix0to1[3][8] = 0.247183547912484;
   fWeightMatrix0to1[4][8] = -2.82070355345681;
   fWeightMatrix0to1[5][8] = -0.961065582288763;
   fWeightMatrix0to1[6][8] = -0.93645816641942;
   fWeightMatrix0to1[7][8] = 1.14791541741079;
   fWeightMatrix0to1[8][8] = -1.3196787665674;
   fWeightMatrix0to1[9][8] = -1.47441816069162;
   fWeightMatrix0to1[10][8] = 1.55509324937927;
   fWeightMatrix0to1[11][8] = 1.37727685345505;
   fWeightMatrix0to1[12][8] = 0.0883459617348674;
   fWeightMatrix0to1[13][8] = 1.3437011530277;
   fWeightMatrix0to1[14][8] = 0.435547644878954;
   fWeightMatrix0to1[15][8] = -2.15269186283951;
   fWeightMatrix0to1[16][8] = 2.21333037384169;
   fWeightMatrix0to1[17][8] = -0.241945277118463;
   fWeightMatrix0to1[18][8] = -0.0433545518181189;
   fWeightMatrix0to1[19][8] = -9.18943770620104;
   // weight matrix from layer 1 to 2
   fWeightMatrix1to2[0][0] = -0.974476798698825;
   fWeightMatrix1to2[0][1] = 0.486575282826936;
   fWeightMatrix1to2[0][2] = 0.346779210372754;
   fWeightMatrix1to2[0][3] = -1.18420057773406;
   fWeightMatrix1to2[0][4] = 1.26456282602228;
   fWeightMatrix1to2[0][5] = -0.546029535354669;
   fWeightMatrix1to2[0][6] = 0.302111631700593;
   fWeightMatrix1to2[0][7] = 1.11997895891674;
   fWeightMatrix1to2[0][8] = -1.21845169145823;
   fWeightMatrix1to2[0][9] = -0.214764058884254;
   fWeightMatrix1to2[0][10] = 0.276267806459994;
   fWeightMatrix1to2[0][11] = 0.422255183135786;
   fWeightMatrix1to2[0][12] = 0.972669988818097;
   fWeightMatrix1to2[0][13] = 1.06599512135537;
   fWeightMatrix1to2[0][14] = 0.0106319703415511;
   fWeightMatrix1to2[0][15] = -0.387200751653005;
   fWeightMatrix1to2[0][16] = -1.13611191471651;
   fWeightMatrix1to2[0][17] = 0.141005759354282;
   fWeightMatrix1to2[0][18] = 0.623515555031942;
   fWeightMatrix1to2[0][19] = -1.75819281090583;
   fWeightMatrix1to2[0][20] = 0.184342438206301;
}

inline double Read1Layer20Nodes::GetMvaValue__( const std::vector<double>& inputValues ) const
{
   if (inputValues.size() != (unsigned int)fLayerSize[0]-1) {
      std::cout << "Input vector needs to be of size " << fLayerSize[0]-1 << std::endl;
      return 0;
   }

   for (int l=0; l<fLayers; l++)
      for (int i=0; i<fLayerSize[l]; i++) fWeights[l][i]=0;

   for (int l=0; l<fLayers-1; l++)
      fWeights[l][fLayerSize[l]-1]=1;

   for (int i=0; i<fLayerSize[0]-1; i++)
      fWeights[0][i]=inputValues[i];

   // layer 0 to 1
   for (int o=0; o<fLayerSize[1]-1; o++) {
      for (int i=0; i<fLayerSize[0]; i++) {
         double inputVal = fWeightMatrix0to1[o][i] * fWeights[0][i];
         fWeights[1][o] += inputVal;
      }
      fWeights[1][o] = ActivationFnc(fWeights[1][o]);
   }
   // layer 1 to 2
   for (int o=0; o<fLayerSize[2]; o++) {
      for (int i=0; i<fLayerSize[1]; i++) {
         double inputVal = fWeightMatrix1to2[o][i] * fWeights[1][i];
         fWeights[2][o] += inputVal;
      }
      fWeights[2][o] = OutputActivationFnc(fWeights[2][o]);
   }

   return fWeights[2][0];
}

double Read1Layer20Nodes::ActivationFnc(double x) const {
   // sigmoid
   return 1.0/(1.0+exp(-x));
}
double Read1Layer20Nodes::OutputActivationFnc(double x) const {
   // identity
   return x;
}
   
// Clean up
inline void Read1Layer20Nodes::Clear() 
{
   // clean up the arrays
   for (int lIdx = 0; lIdx < 3; lIdx++) {
      delete[] fWeights[lIdx];
   }
}
   inline double Read1Layer20Nodes::GetMvaValue( const std::vector<double>& inputValues ) const
   {
      // classifier response value
      double retval = 0;

      // classifier response, sanity check first
      if (!IsStatusClean()) {
         std::cout << "Problem in class \"" << fClassName << "\": cannot return classifier response"
                   << " because status is dirty" << std::endl;
         retval = 0;
      }
      else {
         if (IsNormalised()) {
            // normalise variables
            std::vector<double> iV;
            iV.resize(inputValues.size());
            int ivar = 0;
            for (std::vector<double>::const_iterator varIt = inputValues.begin();
                 varIt != inputValues.end(); varIt++, ivar++) {
               iV.push_back(NormVariable( *varIt, fVmin[ivar], fVmax[ivar] ));
            }
            Transform( iV, -1 );
            retval = GetMvaValue__( iV );
         }
         else {
            std::vector<double> iV;
            int ivar = 0;
            for (std::vector<double>::const_iterator varIt = inputValues.begin();
                 varIt != inputValues.end(); varIt++, ivar++) {
               iV.push_back(*varIt);
            }
            Transform( iV, -1 );
            retval = GetMvaValue__( iV );
         }
      }

      return retval;
   }

//_______________________________________________________________________
inline void Read1Layer20Nodes::InitTransform_1()
{
   // Normalization transformation, initialisation
   fMin_1[0][0] = 5;
   fMax_1[0][0] = 2543.40991211;
   fMin_1[1][0] = 4.73000001907;
   fMax_1[1][0] = 817.520019531;
   fMin_1[2][0] = 4.73000001907;
   fMax_1[2][0] = 2543.40991211;
   fMin_1[0][1] = -3.99099993706;
   fMax_1[0][1] = 3.99099993706;
   fMin_1[1][1] = -3.99300003052;
   fMax_1[1][1] = 3.99000000954;
   fMin_1[2][1] = -3.99300003052;
   fMax_1[2][1] = 3.99099993706;
   fMin_1[0][2] = 0;
   fMax_1[0][2] = 6.28299999237;
   fMin_1[1][2] = 0;
   fMax_1[1][2] = 6.28299999237;
   fMin_1[2][2] = 0;
   fMax_1[2][2] = 6.28299999237;
   fMin_1[0][3] = 0;
   fMax_1[0][3] = 258.730010986;
   fMin_1[1][3] = 0;
   fMax_1[1][3] = 159.369995117;
   fMin_1[2][3] = 0;
   fMax_1[2][3] = 258.730010986;
   fMin_1[0][4] = 0;
   fMax_1[0][4] = 61;
   fMin_1[1][4] = 0;
   fMax_1[1][4] = 59;
   fMin_1[2][4] = 0;
   fMax_1[2][4] = 61;
   fMin_1[0][5] = 0;
   fMax_1[0][5] = 999;
   fMin_1[1][5] = 0;
   fMax_1[1][5] = 999;
   fMin_1[2][5] = 0;
   fMax_1[2][5] = 999;
   fMin_1[0][6] = 0;
   fMax_1[0][6] = 6.28299999237;
   fMin_1[1][6] = 0.0010000000475;
   fMax_1[1][6] = 6.28200006485;
   fMin_1[2][6] = 0;
   fMax_1[2][6] = 6.28299999237;
   fMin_1[0][7] = 100.019996643;
   fMax_1[0][7] = 1585.47998047;
   fMin_1[1][7] = 100.010002136;
   fMax_1[1][7] = 662.650024414;
   fMin_1[2][7] = 100.010002136;
   fMax_1[2][7] = 1585.47998047;
}

//_______________________________________________________________________
inline void Read1Layer20Nodes::Transform_1( std::vector<double>& iv, int cls) const
{
   // Normalization transformation
   if (cls < 0 || cls > 2) {
   if (2 > 1 ) cls = 2;
      else cls = 2;
   }
   const int nVar = 8;

   // get indices of used variables

   // define the indices of the variables which are transformed by this transformation
   static std::vector<int> indicesGet;
   static std::vector<int> indicesPut;

   if ( indicesGet.empty() ) { 
      indicesGet.reserve(nVar);
      indicesGet.push_back( 0);
      indicesGet.push_back( 1);
      indicesGet.push_back( 2);
      indicesGet.push_back( 3);
      indicesGet.push_back( 4);
      indicesGet.push_back( 5);
      indicesGet.push_back( 6);
      indicesGet.push_back( 7);
   } 
   if ( indicesPut.empty() ) { 
      indicesPut.reserve(nVar);
      indicesPut.push_back( 0);
      indicesPut.push_back( 1);
      indicesPut.push_back( 2);
      indicesPut.push_back( 3);
      indicesPut.push_back( 4);
      indicesPut.push_back( 5);
      indicesPut.push_back( 6);
      indicesPut.push_back( 7);
   } 

   static std::vector<double> dv;
   dv.resize(nVar);
   for (int ivar=0; ivar<nVar; ivar++) dv[ivar] = iv[indicesGet.at(ivar)];
   for (int ivar=0;ivar<8;ivar++) {
      double offset = fMin_1[cls][ivar];
      double scale  = 1.0/(fMax_1[cls][ivar]-fMin_1[cls][ivar]);
      iv[indicesPut.at(ivar)] = (dv[ivar]-offset)*scale * 2 - 1;
   }
}

//_______________________________________________________________________
inline void Read1Layer20Nodes::InitTransform()
{
   InitTransform_1();
}

//_______________________________________________________________________
inline void Read1Layer20Nodes::Transform( std::vector<double>& iv, int sigOrBgd ) const
{
   Transform_1( iv, sigOrBgd );
}
