// Class: Read3Layers33Decrease
// Automatically generated by MethodBase::MakeClass
//

/* configuration options =====================================================

#GEN -*-*-*-*-*-*-*-*-*-*-*- general info -*-*-*-*-*-*-*-*-*-*-*-

Method         : MLP::3Layers33Decrease
TMVA Release   : 4.2.0         [262656]
ROOT Release   : 5.34/18       [336402]
Creator        : zxb0111
Date           : Sat Dec  6 23:18:43 2014
Host           : Linux localhost.localdomain 2.6.32-431.17.1.el6.x86_64 #1 SMP Wed May 7 14:14:17 CDT 2014 x86_64 x86_64 x86_64 GNU/Linux
Dir            : /home/zxb0111/seminar
Training events: 34086
Analysis type  : [Classification]


#OPT -*-*-*-*-*-*-*-*-*-*-*-*- options -*-*-*-*-*-*-*-*-*-*-*-*-

# Set by User:
NCycles: "600" [Number of training cycles]
HiddenLayers: "14,11,8" [Specification of hidden layer architecture]
NeuronType: "sigmoid" [Neuron activation function type]
VarTransform: "N" [List of variable transformations performed before training, e.g., "D_Background,P_Signal,G,N_AllClasses" for: "Decorrelation, PCA-transformation, Gaussianisation, Normalisation, each for the given class of events ('AllClasses' denotes all events of all classes, if no class indication is given, 'All' is assumed)"]
TestRate: "5" [Test for overtraining performed at each #th epochs]
UseRegulator: "False" [Use regulator to avoid over-training]
# Default:
RandomSeed: "1" [Random seed for initial synapse weights (0 means unique seed for each run; default value '1')]
EstimatorType: "MSE" [MSE (Mean Square Estimator) for Gaussian Likelihood or CE(Cross-Entropy) for Bernoulli Likelihood]
NeuronInputType: "sum" [Neuron input function type]
V: "False" [Verbose output (short form of "VerbosityLevel" below - overrides the latter one)]
VerbosityLevel: "Default" [Verbosity level]
H: "False" [Print method-specific help message]
CreateMVAPdfs: "False" [Create PDFs for classifier outputs (signal and background)]
IgnoreNegWeightsInTraining: "False" [Events with negative weights are ignored in the training (but are included for testing and performance evaluation)]
TrainingMethod: "BP" [Train with Back-Propagation (BP), BFGS Algorithm (BFGS), or Genetic Algorithm (GA - slower and worse)]
LearningRate: "2.000000e-02" [ANN learning rate parameter]
DecayRate: "1.000000e-02" [Decay rate for learning parameter]
EpochMonitoring: "False" [Provide epoch-wise monitoring plots according to TestRate (caution: causes big ROOT output file!)]
Sampling: "1.000000e+00" [Only 'Sampling' (randomly selected) events are trained each epoch]
SamplingEpoch: "1.000000e+00" [Sampling is used for the first 'SamplingEpoch' epochs, afterwards, all events are taken for training]
SamplingImportance: "1.000000e+00" [ The sampling weights of events in epochs which successful (worse estimator than before) are multiplied with SamplingImportance, else they are divided.]
SamplingTraining: "True" [The training sample is sampled]
SamplingTesting: "False" [The testing sample is sampled]
ResetStep: "50" [How often BFGS should reset history]
Tau: "3.000000e+00" [LineSearch "size step"]
BPMode: "sequential" [Back-propagation learning mode: sequential or batch]
BatchSize: "-1" [Batch size: number of events/batch, only set if in Batch Mode, -1 for BatchSize=number_of_events]
ConvergenceImprove: "1.000000e-30" [Minimum improvement which counts as improvement (<0 means automatic convergence check is turned off)]
ConvergenceTests: "-1" [Number of steps (without improvement) required for convergence (<0 means automatic convergence check is turned off)]
UpdateLimit: "10000" [Maximum times of regulator update]
CalculateErrors: "False" [Calculates inverse Hessian matrix at the end of the training to be able to calculate the uncertainties of an MVA value]
WeightRange: "1.000000e+00" [Take the events for the estimator calculations from small deviations from the desired value to large deviations only over the weight range]
##


#VAR -*-*-*-*-*-*-*-*-*-*-*-* variables *-*-*-*-*-*-*-*-*-*-*-*-

NVar 8
Jet.PT                        Jet.PT                        Jet.PT                        Jet.PT                                                          'F'    [4.73000001907,2543.40991211]
Jet.Eta                       Jet.Eta                       Jet.Eta                       Jet.Eta                                                         'F'    [-3.99300003052,3.99099993706]
Jet.Phi                       Jet.Phi                       Jet.Phi                       Jet.Phi                                                         'F'    [0,6.28299999237]
Jet.Mass                      Jet.Mass                      Jet.Mass                      Jet.Mass                                                        'F'    [0,258.730010986]
Jet.Ntrk                      Jet.Ntrk                      Jet.Ntrk                      Jet.Ntrk                                                        'F'    [0,61]
Jet.EhadOverEem               Jet.EhadOverEem               Jet.EhadOverEem               Jet.EhadOverEem                                                 'F'    [0,999]
MissingET.Phi                 MissingET.Phi                 MissingET.Phi                 MissingET.Phi                                                   'F'    [0,6.28299999237]
MissingET.MET                 MissingET.MET                 MissingET.MET                 MissingET.MET                                                   'F'    [100.010002136,1585.47998047]
NSpec 0


============================================================================ */

#include <vector>
#include <cmath>
#include <string>
#include <iostream>

#ifndef IClassifierReader__def
#define IClassifierReader__def

class IClassifierReader {

 public:

   // constructor
   IClassifierReader() : fStatusIsClean( true ) {}
   virtual ~IClassifierReader() {}

   // return classifier response
   virtual double GetMvaValue( const std::vector<double>& inputValues ) const = 0;

   // returns classifier status
   bool IsStatusClean() const { return fStatusIsClean; }

 protected:

   bool fStatusIsClean;
};

#endif

class Read3Layers33Decrease : public IClassifierReader {

 public:

   // constructor
   Read3Layers33Decrease( std::vector<std::string>& theInputVars ) 
      : IClassifierReader(),
        fClassName( "Read3Layers33Decrease" ),
        fNvars( 8 ),
        fIsNormalised( false )
   {      
      // the training input variables
      const char* inputVars[] = { "Jet.PT", "Jet.Eta", "Jet.Phi", "Jet.Mass", "Jet.Ntrk", "Jet.EhadOverEem", "MissingET.Phi", "MissingET.MET" };

      // sanity checks
      if (theInputVars.size() <= 0) {
         std::cout << "Problem in class \"" << fClassName << "\": empty input vector" << std::endl;
         fStatusIsClean = false;
      }

      if (theInputVars.size() != fNvars) {
         std::cout << "Problem in class \"" << fClassName << "\": mismatch in number of input values: "
                   << theInputVars.size() << " != " << fNvars << std::endl;
         fStatusIsClean = false;
      }

      // validate input variables
      for (size_t ivar = 0; ivar < theInputVars.size(); ivar++) {
         if (theInputVars[ivar] != inputVars[ivar]) {
            std::cout << "Problem in class \"" << fClassName << "\": mismatch in input variable names" << std::endl
                      << " for variable [" << ivar << "]: " << theInputVars[ivar].c_str() << " != " << inputVars[ivar] << std::endl;
            fStatusIsClean = false;
         }
      }

      // initialize min and max vectors (for normalisation)
      fVmin[0] = -1;
      fVmax[0] = 1;
      fVmin[1] = -1;
      fVmax[1] = 1;
      fVmin[2] = -1;
      fVmax[2] = 0.99999988079071;
      fVmin[3] = -1;
      fVmax[3] = 1;
      fVmin[4] = -1;
      fVmax[4] = 0.99999988079071;
      fVmin[5] = -1;
      fVmax[5] = 1;
      fVmin[6] = -1;
      fVmax[6] = 0.99999988079071;
      fVmin[7] = -1;
      fVmax[7] = 1;

      // initialize input variable types
      fType[0] = 'F';
      fType[1] = 'F';
      fType[2] = 'F';
      fType[3] = 'F';
      fType[4] = 'F';
      fType[5] = 'F';
      fType[6] = 'F';
      fType[7] = 'F';

      // initialize constants
      Initialize();

      // initialize transformation
      InitTransform();
   }

   // destructor
   virtual ~Read3Layers33Decrease() {
      Clear(); // method-specific
   }

   // the classifier response
   // "inputValues" is a vector of input values in the same order as the 
   // variables given to the constructor
   double GetMvaValue( const std::vector<double>& inputValues ) const;

 private:

   // method-specific destructor
   void Clear();

   // input variable transformation

   double fMin_1[3][8];
   double fMax_1[3][8];
   void InitTransform_1();
   void Transform_1( std::vector<double> & iv, int sigOrBgd ) const;
   void InitTransform();
   void Transform( std::vector<double> & iv, int sigOrBgd ) const;

   // common member variables
   const char* fClassName;

   const size_t fNvars;
   size_t GetNvar()           const { return fNvars; }
   char   GetType( int ivar ) const { return fType[ivar]; }

   // normalisation of input variables
   const bool fIsNormalised;
   bool IsNormalised() const { return fIsNormalised; }
   double fVmin[8];
   double fVmax[8];
   double NormVariable( double x, double xmin, double xmax ) const {
      // normalise to output range: [-1, 1]
      return 2*(x - xmin)/(xmax - xmin) - 1.0;
   }

   // type of input variable: 'F' or 'I'
   char   fType[8];

   // initialize internal variables
   void Initialize();
   double GetMvaValue__( const std::vector<double>& inputValues ) const;

   // private members (method specific)

   double ActivationFnc(double x) const;
   double OutputActivationFnc(double x) const;

   int fLayers;
   int fLayerSize[5];
   double fWeightMatrix0to1[15][9];   // weight matrix from layer 0 to 1
   double fWeightMatrix1to2[12][15];   // weight matrix from layer 1 to 2
   double fWeightMatrix2to3[9][12];   // weight matrix from layer 2 to 3
   double fWeightMatrix3to4[1][9];   // weight matrix from layer 3 to 4

   double * fWeights[5];
};

inline void Read3Layers33Decrease::Initialize()
{
   // build network structure
   fLayers = 5;
   fLayerSize[0] = 9; fWeights[0] = new double[9]; 
   fLayerSize[1] = 15; fWeights[1] = new double[15]; 
   fLayerSize[2] = 12; fWeights[2] = new double[12]; 
   fLayerSize[3] = 9; fWeights[3] = new double[9]; 
   fLayerSize[4] = 1; fWeights[4] = new double[1]; 
   // weight matrix from layer 0 to 1
   fWeightMatrix0to1[0][0] = -0.318468505485327;
   fWeightMatrix0to1[1][0] = 5.15120387570139;
   fWeightMatrix0to1[2][0] = 1.07842077148282;
   fWeightMatrix0to1[3][0] = 2.50116575061351;
   fWeightMatrix0to1[4][0] = -3.71140246275528;
   fWeightMatrix0to1[5][0] = -2.53395583040373;
   fWeightMatrix0to1[6][0] = -1.21723002994343;
   fWeightMatrix0to1[7][0] = 2.89269729004854;
   fWeightMatrix0to1[8][0] = -0.895912338975164;
   fWeightMatrix0to1[9][0] = -0.998751789134633;
   fWeightMatrix0to1[10][0] = -4.95610995934773;
   fWeightMatrix0to1[11][0] = -0.400921227839649;
   fWeightMatrix0to1[12][0] = -0.324654046462889;
   fWeightMatrix0to1[13][0] = -0.244725253430404;
   fWeightMatrix0to1[0][1] = 0.105861287377534;
   fWeightMatrix0to1[1][1] = 0.154353727304183;
   fWeightMatrix0to1[2][1] = -0.846876421319017;
   fWeightMatrix0to1[3][1] = 0.935529871614594;
   fWeightMatrix0to1[4][1] = 0.0815351487688645;
   fWeightMatrix0to1[5][1] = -0.0419202359814924;
   fWeightMatrix0to1[6][1] = -0.181630762425611;
   fWeightMatrix0to1[7][1] = -0.0402630740377036;
   fWeightMatrix0to1[8][1] = 0.190021696978167;
   fWeightMatrix0to1[9][1] = 0.192127376766689;
   fWeightMatrix0to1[10][1] = 0.241844159879192;
   fWeightMatrix0to1[11][1] = 0.0610062496607451;
   fWeightMatrix0to1[12][1] = 0.67490891829058;
   fWeightMatrix0to1[13][1] = -0.66492515898566;
   fWeightMatrix0to1[0][2] = -1.99891024915296;
   fWeightMatrix0to1[1][2] = -0.27390670340354;
   fWeightMatrix0to1[2][2] = 0.0669343309640144;
   fWeightMatrix0to1[3][2] = 2.81430992543546;
   fWeightMatrix0to1[4][2] = -0.194131946172667;
   fWeightMatrix0to1[5][2] = 1.0212673806575;
   fWeightMatrix0to1[6][2] = 1.66904308632034;
   fWeightMatrix0to1[7][2] = 1.84725932765516;
   fWeightMatrix0to1[8][2] = -2.36579977125822;
   fWeightMatrix0to1[9][2] = 4.57744368966088;
   fWeightMatrix0to1[10][2] = 0.12309797067262;
   fWeightMatrix0to1[11][2] = -1.23701719670506;
   fWeightMatrix0to1[12][2] = 1.78337511591437;
   fWeightMatrix0to1[13][2] = 4.68586716005811;
   fWeightMatrix0to1[0][3] = 1.54271124846327;
   fWeightMatrix0to1[1][3] = 2.02085777105174;
   fWeightMatrix0to1[2][3] = -0.825329806694802;
   fWeightMatrix0to1[3][3] = -1.56810825893787;
   fWeightMatrix0to1[4][3] = -1.09104635538377;
   fWeightMatrix0to1[5][3] = -0.921665012242384;
   fWeightMatrix0to1[6][3] = 1.75475840809504;
   fWeightMatrix0to1[7][3] = 1.66266438488763;
   fWeightMatrix0to1[8][3] = 1.31243065384347;
   fWeightMatrix0to1[9][3] = 2.10237976626618;
   fWeightMatrix0to1[10][3] = -1.00150223416124;
   fWeightMatrix0to1[11][3] = 0.317227723514864;
   fWeightMatrix0to1[12][3] = -0.864080978335959;
   fWeightMatrix0to1[13][3] = -1.47513997546411;
   fWeightMatrix0to1[0][4] = -0.873497655798915;
   fWeightMatrix0to1[1][4] = -1.43177700443668;
   fWeightMatrix0to1[2][4] = 1.04796221770094;
   fWeightMatrix0to1[3][4] = 1.18272587748296;
   fWeightMatrix0to1[4][4] = -0.0861065986133176;
   fWeightMatrix0to1[5][4] = -0.0377926996181703;
   fWeightMatrix0to1[6][4] = -0.201437454951923;
   fWeightMatrix0to1[7][4] = 0.469401573302498;
   fWeightMatrix0to1[8][4] = 1.74636012365171;
   fWeightMatrix0to1[9][4] = -0.22485144983925;
   fWeightMatrix0to1[10][4] = -1.45651567206762;
   fWeightMatrix0to1[11][4] = -0.545121959390386;
   fWeightMatrix0to1[12][4] = 0.95033046232143;
   fWeightMatrix0to1[13][4] = 0.180542828046714;
   fWeightMatrix0to1[0][5] = -0.894888509898737;
   fWeightMatrix0to1[1][5] = -1.96395750374077;
   fWeightMatrix0to1[2][5] = 0.72023216976345;
   fWeightMatrix0to1[3][5] = 0.834019376511616;
   fWeightMatrix0to1[4][5] = 0.570461554937945;
   fWeightMatrix0to1[5][5] = -0.567144228782027;
   fWeightMatrix0to1[6][5] = -1.63270661938707;
   fWeightMatrix0to1[7][5] = -2.41405152652636;
   fWeightMatrix0to1[8][5] = 1.10331996451946;
   fWeightMatrix0to1[9][5] = 2.05246102840928;
   fWeightMatrix0to1[10][5] = 4.66193211298876;
   fWeightMatrix0to1[11][5] = 0.743848380771224;
   fWeightMatrix0to1[12][5] = 1.4578564185628;
   fWeightMatrix0to1[13][5] = -1.54134561623695;
   fWeightMatrix0to1[0][6] = 1.56101916164505;
   fWeightMatrix0to1[1][6] = 0.0419090622865573;
   fWeightMatrix0to1[2][6] = 1.17191888738675;
   fWeightMatrix0to1[3][6] = -3.13423046882064;
   fWeightMatrix0to1[4][6] = 0.596773811376662;
   fWeightMatrix0to1[5][6] = -1.35991136946159;
   fWeightMatrix0to1[6][6] = -1.27898172964325;
   fWeightMatrix0to1[7][6] = -2.02171445710501;
   fWeightMatrix0to1[8][6] = 2.53344821230232;
   fWeightMatrix0to1[9][6] = -4.61338848494767;
   fWeightMatrix0to1[10][6] = -0.26154493420412;
   fWeightMatrix0to1[11][6] = 1.504138937435;
   fWeightMatrix0to1[12][6] = -2.03521503984932;
   fWeightMatrix0to1[13][6] = -4.47257830440799;
   fWeightMatrix0to1[0][7] = -2.10366442289028;
   fWeightMatrix0to1[1][7] = -1.71703683209498;
   fWeightMatrix0to1[2][7] = -2.33855973908796;
   fWeightMatrix0to1[3][7] = -1.32096306778704;
   fWeightMatrix0to1[4][7] = 6.69738731530037;
   fWeightMatrix0to1[5][7] = 4.37629986134251;
   fWeightMatrix0to1[6][7] = -0.69827335227517;
   fWeightMatrix0to1[7][7] = 1.36843035683444;
   fWeightMatrix0to1[8][7] = -0.57740463872086;
   fWeightMatrix0to1[9][7] = -0.802712883856374;
   fWeightMatrix0to1[10][7] = -1.50232377047084;
   fWeightMatrix0to1[11][7] = 3.57103925410261;
   fWeightMatrix0to1[12][7] = -2.1043540544604;
   fWeightMatrix0to1[13][7] = 0.67312770163051;
   fWeightMatrix0to1[0][8] = 0.377899283622527;
   fWeightMatrix0to1[1][8] = 1.40840645575858;
   fWeightMatrix0to1[2][8] = -1.20277745425858;
   fWeightMatrix0to1[3][8] = 2.31750113896126;
   fWeightMatrix0to1[4][8] = 1.00809971896558;
   fWeightMatrix0to1[5][8] = -0.104983124645773;
   fWeightMatrix0to1[6][8] = 0.261635237722892;
   fWeightMatrix0to1[7][8] = -0.381286288711777;
   fWeightMatrix0to1[8][8] = -1.86495923351314;
   fWeightMatrix0to1[9][8] = -1.67183311635951;
   fWeightMatrix0to1[10][8] = -3.89921167872067;
   fWeightMatrix0to1[11][8] = 2.3862724358471;
   fWeightMatrix0to1[12][8] = 0.320854133890527;
   fWeightMatrix0to1[13][8] = 0.977216040055115;
   // weight matrix from layer 1 to 2
   fWeightMatrix1to2[0][0] = -0.733883154745564;
   fWeightMatrix1to2[1][0] = -1.37016647220863;
   fWeightMatrix1to2[2][0] = -1.60853830803268;
   fWeightMatrix1to2[3][0] = 0.240209259179618;
   fWeightMatrix1to2[4][0] = 0.564825826127831;
   fWeightMatrix1to2[5][0] = -1.9696772087537;
   fWeightMatrix1to2[6][0] = -0.236295658839306;
   fWeightMatrix1to2[7][0] = -1.59516894777728;
   fWeightMatrix1to2[8][0] = 0.258653290213454;
   fWeightMatrix1to2[9][0] = 1.66514664967944;
   fWeightMatrix1to2[10][0] = 1.22217200968686;
   fWeightMatrix1to2[0][1] = -2.53926679969344;
   fWeightMatrix1to2[1][1] = 0.952925434629024;
   fWeightMatrix1to2[2][1] = 2.7367768514511;
   fWeightMatrix1to2[3][1] = 3.78623220115965;
   fWeightMatrix1to2[4][1] = 1.27998484165784;
   fWeightMatrix1to2[5][1] = -1.44585531201521;
   fWeightMatrix1to2[6][1] = 1.19144378388505;
   fWeightMatrix1to2[7][1] = -0.900396167009918;
   fWeightMatrix1to2[8][1] = 2.07161863600621;
   fWeightMatrix1to2[9][1] = 1.32713767427042;
   fWeightMatrix1to2[10][1] = -0.302532941628894;
   fWeightMatrix1to2[0][2] = -0.745083539625588;
   fWeightMatrix1to2[1][2] = -0.326473947890215;
   fWeightMatrix1to2[2][2] = -1.03211258830859;
   fWeightMatrix1to2[3][2] = 0.226663049400792;
   fWeightMatrix1to2[4][2] = 1.83468208298392;
   fWeightMatrix1to2[5][2] = -0.686957225620322;
   fWeightMatrix1to2[6][2] = -0.664046724157654;
   fWeightMatrix1to2[7][2] = -0.265814991378758;
   fWeightMatrix1to2[8][2] = 1.14011301427032;
   fWeightMatrix1to2[9][2] = 1.15320474019641;
   fWeightMatrix1to2[10][2] = 0.694067511506513;
   fWeightMatrix1to2[0][3] = -1.44251684962327;
   fWeightMatrix1to2[1][3] = 1.20110129815839;
   fWeightMatrix1to2[2][3] = 0.827909231387569;
   fWeightMatrix1to2[3][3] = 1.72173952830711;
   fWeightMatrix1to2[4][3] = 0.853469007477289;
   fWeightMatrix1to2[5][3] = 0.756584386702759;
   fWeightMatrix1to2[6][3] = -0.144197591075563;
   fWeightMatrix1to2[7][3] = -0.370160066127779;
   fWeightMatrix1to2[8][3] = 1.16608613681731;
   fWeightMatrix1to2[9][3] = -0.854134521319588;
   fWeightMatrix1to2[10][3] = -0.389161028313739;
   fWeightMatrix1to2[0][4] = 2.24517408795356;
   fWeightMatrix1to2[1][4] = 1.55294195520679;
   fWeightMatrix1to2[2][4] = -0.807098545890691;
   fWeightMatrix1to2[3][4] = 0.736823822448279;
   fWeightMatrix1to2[4][4] = 1.075739949628;
   fWeightMatrix1to2[5][4] = -1.97813469332065;
   fWeightMatrix1to2[6][4] = 2.02142186381307;
   fWeightMatrix1to2[7][4] = 0.779130624839101;
   fWeightMatrix1to2[8][4] = 0.453077483722233;
   fWeightMatrix1to2[9][4] = -4.0567476598659;
   fWeightMatrix1to2[10][4] = -1.88592470083989;
   fWeightMatrix1to2[0][5] = 2.12920844392077;
   fWeightMatrix1to2[1][5] = 2.14513932396331;
   fWeightMatrix1to2[2][5] = -2.44931076461433;
   fWeightMatrix1to2[3][5] = -0.964078194314973;
   fWeightMatrix1to2[4][5] = -1.6225861202702;
   fWeightMatrix1to2[5][5] = 0.260336398435706;
   fWeightMatrix1to2[6][5] = 2.47980455020391;
   fWeightMatrix1to2[7][5] = 0.413319133318386;
   fWeightMatrix1to2[8][5] = -0.635578672526775;
   fWeightMatrix1to2[9][5] = -2.91292561946431;
   fWeightMatrix1to2[10][5] = 0.671959641967491;
   fWeightMatrix1to2[0][6] = 1.47853699528293;
   fWeightMatrix1to2[1][6] = -0.0773269752798781;
   fWeightMatrix1to2[2][6] = 0.431020240427505;
   fWeightMatrix1to2[3][6] = -2.6166330860563;
   fWeightMatrix1to2[4][6] = -2.30115421816476;
   fWeightMatrix1to2[5][6] = 0.850207560513854;
   fWeightMatrix1to2[6][6] = 0.059339391507437;
   fWeightMatrix1to2[7][6] = -1.68284702323216;
   fWeightMatrix1to2[8][6] = -0.432234650729734;
   fWeightMatrix1to2[9][6] = 0.234110305486538;
   fWeightMatrix1to2[10][6] = -0.29843563757416;
   fWeightMatrix1to2[0][7] = -2.28857117818945;
   fWeightMatrix1to2[1][7] = 2.30052282975698;
   fWeightMatrix1to2[2][7] = 1.39874719624184;
   fWeightMatrix1to2[3][7] = -0.217637679264648;
   fWeightMatrix1to2[4][7] = -0.0990321385021774;
   fWeightMatrix1to2[5][7] = 1.68734377402259;
   fWeightMatrix1to2[6][7] = 1.90556913186382;
   fWeightMatrix1to2[7][7] = 0.854058644327571;
   fWeightMatrix1to2[8][7] = -0.0204218093063837;
   fWeightMatrix1to2[9][7] = -2.42904444071042;
   fWeightMatrix1to2[10][7] = -0.873422475401708;
   fWeightMatrix1to2[0][8] = 1.96446219953822;
   fWeightMatrix1to2[1][8] = 1.61262913430102;
   fWeightMatrix1to2[2][8] = 0.565213567043356;
   fWeightMatrix1to2[3][8] = 0.762152343153097;
   fWeightMatrix1to2[4][8] = 2.16270777127573;
   fWeightMatrix1to2[5][8] = -1.71599770279734;
   fWeightMatrix1to2[6][8] = -0.906461071428781;
   fWeightMatrix1to2[7][8] = 0.19640888323356;
   fWeightMatrix1to2[8][8] = -1.47582896525385;
   fWeightMatrix1to2[9][8] = 0.577150491576114;
   fWeightMatrix1to2[10][8] = 1.53034967096358;
   fWeightMatrix1to2[0][9] = -0.584484457507636;
   fWeightMatrix1to2[1][9] = 0.734178502622489;
   fWeightMatrix1to2[2][9] = -0.514551514650164;
   fWeightMatrix1to2[3][9] = -3.73608782670095;
   fWeightMatrix1to2[4][9] = -2.23156642418602;
   fWeightMatrix1to2[5][9] = 0.975558756369014;
   fWeightMatrix1to2[6][9] = -0.766069627268573;
   fWeightMatrix1to2[7][9] = 0.429306640808993;
   fWeightMatrix1to2[8][9] = -1.10769014886774;
   fWeightMatrix1to2[9][9] = 1.41878153577924;
   fWeightMatrix1to2[10][9] = -1.95302666630152;
   fWeightMatrix1to2[0][10] = 1.05256693088193;
   fWeightMatrix1to2[1][10] = -0.460947662176505;
   fWeightMatrix1to2[2][10] = -1.68601953067515;
   fWeightMatrix1to2[3][10] = -4.70088283582752;
   fWeightMatrix1to2[4][10] = -2.40392930017817;
   fWeightMatrix1to2[5][10] = -0.657986170085459;
   fWeightMatrix1to2[6][10] = -3.31710626355939;
   fWeightMatrix1to2[7][10] = -2.07707751278129;
   fWeightMatrix1to2[8][10] = -1.89629610051039;
   fWeightMatrix1to2[9][10] = -0.45606599652577;
   fWeightMatrix1to2[10][10] = -1.41285064618136;
   fWeightMatrix1to2[0][11] = -1.55733355241228;
   fWeightMatrix1to2[1][11] = 1.38834578080641;
   fWeightMatrix1to2[2][11] = -0.858524931662487;
   fWeightMatrix1to2[3][11] = 0.121245304942603;
   fWeightMatrix1to2[4][11] = -1.12455796801743;
   fWeightMatrix1to2[5][11] = 0.219510464641095;
   fWeightMatrix1to2[6][11] = 2.7294254493274;
   fWeightMatrix1to2[7][11] = 1.38182534836017;
   fWeightMatrix1to2[8][11] = -0.805323631120581;
   fWeightMatrix1to2[9][11] = -2.23319641830183;
   fWeightMatrix1to2[10][11] = -1.4828319390362;
   fWeightMatrix1to2[0][12] = -0.788520734625334;
   fWeightMatrix1to2[1][12] = -2.53929673560731;
   fWeightMatrix1to2[2][12] = 0.346189232888887;
   fWeightMatrix1to2[3][12] = -0.486990988076283;
   fWeightMatrix1to2[4][12] = 1.63693615652389;
   fWeightMatrix1to2[5][12] = -0.594929767383652;
   fWeightMatrix1to2[6][12] = 0.0499424847415335;
   fWeightMatrix1to2[7][12] = -0.544366908739279;
   fWeightMatrix1to2[8][12] = -1.85166042958151;
   fWeightMatrix1to2[9][12] = 1.0403651649863;
   fWeightMatrix1to2[10][12] = 0.90678273882106;
   fWeightMatrix1to2[0][13] = -0.609233571998724;
   fWeightMatrix1to2[1][13] = -0.581249846646451;
   fWeightMatrix1to2[2][13] = 1.38164913731959;
   fWeightMatrix1to2[3][13] = 3.05820445813808;
   fWeightMatrix1to2[4][13] = 1.1917487098701;
   fWeightMatrix1to2[5][13] = -0.662946044016108;
   fWeightMatrix1to2[6][13] = 0.970098446820409;
   fWeightMatrix1to2[7][13] = 2.11351353222796;
   fWeightMatrix1to2[8][13] = 1.18073914596718;
   fWeightMatrix1to2[9][13] = -0.120043386643024;
   fWeightMatrix1to2[10][13] = -0.299725985662853;
   fWeightMatrix1to2[0][14] = 0.0336198186334973;
   fWeightMatrix1to2[1][14] = -1.07063132668558;
   fWeightMatrix1to2[2][14] = -1.26474732158306;
   fWeightMatrix1to2[3][14] = -1.52861703249442;
   fWeightMatrix1to2[4][14] = -1.81180281956643;
   fWeightMatrix1to2[5][14] = -1.65868928573336;
   fWeightMatrix1to2[6][14] = -1.15461175301494;
   fWeightMatrix1to2[7][14] = 1.83805753463326;
   fWeightMatrix1to2[8][14] = -1.53717708055802;
   fWeightMatrix1to2[9][14] = 1.24261071009003;
   fWeightMatrix1to2[10][14] = -2.19873795338329;
   // weight matrix from layer 2 to 3
   fWeightMatrix2to3[0][0] = 1.21833487487334;
   fWeightMatrix2to3[1][0] = -1.58344075557994;
   fWeightMatrix2to3[2][0] = -0.751667165571615;
   fWeightMatrix2to3[3][0] = 1.75473332635789;
   fWeightMatrix2to3[4][0] = -1.76506443792749;
   fWeightMatrix2to3[5][0] = -0.530779297647274;
   fWeightMatrix2to3[6][0] = 0.515670377877745;
   fWeightMatrix2to3[7][0] = -2.23291136355011;
   fWeightMatrix2to3[0][1] = -2.05306061198322;
   fWeightMatrix2to3[1][1] = -2.2191352284984;
   fWeightMatrix2to3[2][1] = -0.856844750837792;
   fWeightMatrix2to3[3][1] = 2.44199744960605;
   fWeightMatrix2to3[4][1] = -0.728374695076147;
   fWeightMatrix2to3[5][1] = 0.952610166195013;
   fWeightMatrix2to3[6][1] = -1.14004348444517;
   fWeightMatrix2to3[7][1] = -1.70257481549809;
   fWeightMatrix2to3[0][2] = -1.93337726405853;
   fWeightMatrix2to3[1][2] = -1.20180327897712;
   fWeightMatrix2to3[2][2] = -0.770880047432442;
   fWeightMatrix2to3[3][2] = 2.85517811650964;
   fWeightMatrix2to3[4][2] = -1.52937669551091;
   fWeightMatrix2to3[5][2] = -0.459469521278464;
   fWeightMatrix2to3[6][2] = 1.66421773224835;
   fWeightMatrix2to3[7][2] = -0.060738767281703;
   fWeightMatrix2to3[0][3] = -1.40315885467229;
   fWeightMatrix2to3[1][3] = 1.54681765776503;
   fWeightMatrix2to3[2][3] = -1.62086922218033;
   fWeightMatrix2to3[3][3] = 4.65215460517789;
   fWeightMatrix2to3[4][3] = 0.896741532761253;
   fWeightMatrix2to3[5][3] = 0.67649271342274;
   fWeightMatrix2to3[6][3] = -0.896047937311941;
   fWeightMatrix2to3[7][3] = -0.437960508395062;
   fWeightMatrix2to3[0][4] = -1.2930140337216;
   fWeightMatrix2to3[1][4] = 0.222882754835738;
   fWeightMatrix2to3[2][4] = 2.10401755174961;
   fWeightMatrix2to3[3][4] = 2.53401062179277;
   fWeightMatrix2to3[4][4] = 1.44252493077658;
   fWeightMatrix2to3[5][4] = -0.262925150922376;
   fWeightMatrix2to3[6][4] = 0.995782505215328;
   fWeightMatrix2to3[7][4] = -1.91357320961616;
   fWeightMatrix2to3[0][5] = 0.687133117964932;
   fWeightMatrix2to3[1][5] = -1.74601700483099;
   fWeightMatrix2to3[2][5] = -1.76422760941327;
   fWeightMatrix2to3[3][5] = 0.338020684262496;
   fWeightMatrix2to3[4][5] = 1.21207793320471;
   fWeightMatrix2to3[5][5] = 0.236117747517242;
   fWeightMatrix2to3[6][5] = 0.995852933714887;
   fWeightMatrix2to3[7][5] = 0.0133498814112424;
   fWeightMatrix2to3[0][6] = -0.921329110531086;
   fWeightMatrix2to3[1][6] = -1.28667483604146;
   fWeightMatrix2to3[2][6] = 0.131809600076726;
   fWeightMatrix2to3[3][6] = 3.18602357243787;
   fWeightMatrix2to3[4][6] = -1.6420878185484;
   fWeightMatrix2to3[5][6] = 1.52115687840083;
   fWeightMatrix2to3[6][6] = -1.68352867100866;
   fWeightMatrix2to3[7][6] = -0.706681447301462;
   fWeightMatrix2to3[0][7] = -0.908544738897514;
   fWeightMatrix2to3[1][7] = -0.349689031273307;
   fWeightMatrix2to3[2][7] = -1.39921897604653;
   fWeightMatrix2to3[3][7] = 1.13884951593984;
   fWeightMatrix2to3[4][7] = 1.48174774785917;
   fWeightMatrix2to3[5][7] = 1.50387770099665;
   fWeightMatrix2to3[6][7] = -0.365033533066513;
   fWeightMatrix2to3[7][7] = -1.04948792469297;
   fWeightMatrix2to3[0][8] = -1.50504975944144;
   fWeightMatrix2to3[1][8] = -1.84742468155761;
   fWeightMatrix2to3[2][8] = 1.28292167177496;
   fWeightMatrix2to3[3][8] = -0.093611842284888;
   fWeightMatrix2to3[4][8] = -1.27329819265646;
   fWeightMatrix2to3[5][8] = 1.01536547685093;
   fWeightMatrix2to3[6][8] = -1.70099643323035;
   fWeightMatrix2to3[7][8] = -1.17381364220442;
   fWeightMatrix2to3[0][9] = -1.02411299059371;
   fWeightMatrix2to3[1][9] = 0.759305260984367;
   fWeightMatrix2to3[2][9] = -1.18182303654018;
   fWeightMatrix2to3[3][9] = -3.94717517028416;
   fWeightMatrix2to3[4][9] = -1.50236981138777;
   fWeightMatrix2to3[5][9] = -2.14943439170875;
   fWeightMatrix2to3[6][9] = -1.82978464804307;
   fWeightMatrix2to3[7][9] = 0.216478149249859;
   fWeightMatrix2to3[0][10] = -1.20986901975378;
   fWeightMatrix2to3[1][10] = -1.26998066202399;
   fWeightMatrix2to3[2][10] = 1.74354980451951;
   fWeightMatrix2to3[3][10] = 0.494727189141342;
   fWeightMatrix2to3[4][10] = 0.270929994395325;
   fWeightMatrix2to3[5][10] = -0.0855065332337951;
   fWeightMatrix2to3[6][10] = 1.33215259390449;
   fWeightMatrix2to3[7][10] = 1.49964591270477;
   fWeightMatrix2to3[0][11] = 0.105633961876924;
   fWeightMatrix2to3[1][11] = -1.73066396153387;
   fWeightMatrix2to3[2][11] = -0.888948375691159;
   fWeightMatrix2to3[3][11] = -2.95013416588503;
   fWeightMatrix2to3[4][11] = 0.121904306805404;
   fWeightMatrix2to3[5][11] = 0.589044021469421;
   fWeightMatrix2to3[6][11] = -0.266495932042529;
   fWeightMatrix2to3[7][11] = 0.214251572939433;
   // weight matrix from layer 3 to 4
   fWeightMatrix3to4[0][0] = 0.70761949259706;
   fWeightMatrix3to4[0][1] = 1.09194467756437;
   fWeightMatrix3to4[0][2] = -1.30851547069092;
   fWeightMatrix3to4[0][3] = 1.29812916087878;
   fWeightMatrix3to4[0][4] = 0.265778244365985;
   fWeightMatrix3to4[0][5] = -0.521736143830196;
   fWeightMatrix3to4[0][6] = -0.330038320901207;
   fWeightMatrix3to4[0][7] = -0.158160134633152;
   fWeightMatrix3to4[0][8] = 0.207513053796867;
}

inline double Read3Layers33Decrease::GetMvaValue__( const std::vector<double>& inputValues ) const
{
   if (inputValues.size() != (unsigned int)fLayerSize[0]-1) {
      std::cout << "Input vector needs to be of size " << fLayerSize[0]-1 << std::endl;
      return 0;
   }

   for (int l=0; l<fLayers; l++)
      for (int i=0; i<fLayerSize[l]; i++) fWeights[l][i]=0;

   for (int l=0; l<fLayers-1; l++)
      fWeights[l][fLayerSize[l]-1]=1;

   for (int i=0; i<fLayerSize[0]-1; i++)
      fWeights[0][i]=inputValues[i];

   // layer 0 to 1
   for (int o=0; o<fLayerSize[1]-1; o++) {
      for (int i=0; i<fLayerSize[0]; i++) {
         double inputVal = fWeightMatrix0to1[o][i] * fWeights[0][i];
         fWeights[1][o] += inputVal;
      }
      fWeights[1][o] = ActivationFnc(fWeights[1][o]);
   }
   // layer 1 to 2
   for (int o=0; o<fLayerSize[2]-1; o++) {
      for (int i=0; i<fLayerSize[1]; i++) {
         double inputVal = fWeightMatrix1to2[o][i] * fWeights[1][i];
         fWeights[2][o] += inputVal;
      }
      fWeights[2][o] = ActivationFnc(fWeights[2][o]);
   }
   // layer 2 to 3
   for (int o=0; o<fLayerSize[3]-1; o++) {
      for (int i=0; i<fLayerSize[2]; i++) {
         double inputVal = fWeightMatrix2to3[o][i] * fWeights[2][i];
         fWeights[3][o] += inputVal;
      }
      fWeights[3][o] = ActivationFnc(fWeights[3][o]);
   }
   // layer 3 to 4
   for (int o=0; o<fLayerSize[4]; o++) {
      for (int i=0; i<fLayerSize[3]; i++) {
         double inputVal = fWeightMatrix3to4[o][i] * fWeights[3][i];
         fWeights[4][o] += inputVal;
      }
      fWeights[4][o] = OutputActivationFnc(fWeights[4][o]);
   }

   return fWeights[4][0];
}

double Read3Layers33Decrease::ActivationFnc(double x) const {
   // sigmoid
   return 1.0/(1.0+exp(-x));
}
double Read3Layers33Decrease::OutputActivationFnc(double x) const {
   // identity
   return x;
}
   
// Clean up
inline void Read3Layers33Decrease::Clear() 
{
   // clean up the arrays
   for (int lIdx = 0; lIdx < 5; lIdx++) {
      delete[] fWeights[lIdx];
   }
}
   inline double Read3Layers33Decrease::GetMvaValue( const std::vector<double>& inputValues ) const
   {
      // classifier response value
      double retval = 0;

      // classifier response, sanity check first
      if (!IsStatusClean()) {
         std::cout << "Problem in class \"" << fClassName << "\": cannot return classifier response"
                   << " because status is dirty" << std::endl;
         retval = 0;
      }
      else {
         if (IsNormalised()) {
            // normalise variables
            std::vector<double> iV;
            iV.resize(inputValues.size());
            int ivar = 0;
            for (std::vector<double>::const_iterator varIt = inputValues.begin();
                 varIt != inputValues.end(); varIt++, ivar++) {
               iV.push_back(NormVariable( *varIt, fVmin[ivar], fVmax[ivar] ));
            }
            Transform( iV, -1 );
            retval = GetMvaValue__( iV );
         }
         else {
            std::vector<double> iV;
            int ivar = 0;
            for (std::vector<double>::const_iterator varIt = inputValues.begin();
                 varIt != inputValues.end(); varIt++, ivar++) {
               iV.push_back(*varIt);
            }
            Transform( iV, -1 );
            retval = GetMvaValue__( iV );
         }
      }

      return retval;
   }

//_______________________________________________________________________
inline void Read3Layers33Decrease::InitTransform_1()
{
   // Normalization transformation, initialisation
   fMin_1[0][0] = 5;
   fMax_1[0][0] = 2543.40991211;
   fMin_1[1][0] = 4.73000001907;
   fMax_1[1][0] = 817.520019531;
   fMin_1[2][0] = 4.73000001907;
   fMax_1[2][0] = 2543.40991211;
   fMin_1[0][1] = -3.99099993706;
   fMax_1[0][1] = 3.99099993706;
   fMin_1[1][1] = -3.99300003052;
   fMax_1[1][1] = 3.99000000954;
   fMin_1[2][1] = -3.99300003052;
   fMax_1[2][1] = 3.99099993706;
   fMin_1[0][2] = 0;
   fMax_1[0][2] = 6.28299999237;
   fMin_1[1][2] = 0;
   fMax_1[1][2] = 6.28299999237;
   fMin_1[2][2] = 0;
   fMax_1[2][2] = 6.28299999237;
   fMin_1[0][3] = 0;
   fMax_1[0][3] = 258.730010986;
   fMin_1[1][3] = 0;
   fMax_1[1][3] = 159.369995117;
   fMin_1[2][3] = 0;
   fMax_1[2][3] = 258.730010986;
   fMin_1[0][4] = 0;
   fMax_1[0][4] = 61;
   fMin_1[1][4] = 0;
   fMax_1[1][4] = 59;
   fMin_1[2][4] = 0;
   fMax_1[2][4] = 61;
   fMin_1[0][5] = 0;
   fMax_1[0][5] = 999;
   fMin_1[1][5] = 0;
   fMax_1[1][5] = 999;
   fMin_1[2][5] = 0;
   fMax_1[2][5] = 999;
   fMin_1[0][6] = 0;
   fMax_1[0][6] = 6.28299999237;
   fMin_1[1][6] = 0.0010000000475;
   fMax_1[1][6] = 6.28200006485;
   fMin_1[2][6] = 0;
   fMax_1[2][6] = 6.28299999237;
   fMin_1[0][7] = 100.019996643;
   fMax_1[0][7] = 1585.47998047;
   fMin_1[1][7] = 100.010002136;
   fMax_1[1][7] = 662.650024414;
   fMin_1[2][7] = 100.010002136;
   fMax_1[2][7] = 1585.47998047;
}

//_______________________________________________________________________
inline void Read3Layers33Decrease::Transform_1( std::vector<double>& iv, int cls) const
{
   // Normalization transformation
   if (cls < 0 || cls > 2) {
   if (2 > 1 ) cls = 2;
      else cls = 2;
   }
   const int nVar = 8;

   // get indices of used variables

   // define the indices of the variables which are transformed by this transformation
   static std::vector<int> indicesGet;
   static std::vector<int> indicesPut;

   if ( indicesGet.empty() ) { 
      indicesGet.reserve(nVar);
      indicesGet.push_back( 0);
      indicesGet.push_back( 1);
      indicesGet.push_back( 2);
      indicesGet.push_back( 3);
      indicesGet.push_back( 4);
      indicesGet.push_back( 5);
      indicesGet.push_back( 6);
      indicesGet.push_back( 7);
   } 
   if ( indicesPut.empty() ) { 
      indicesPut.reserve(nVar);
      indicesPut.push_back( 0);
      indicesPut.push_back( 1);
      indicesPut.push_back( 2);
      indicesPut.push_back( 3);
      indicesPut.push_back( 4);
      indicesPut.push_back( 5);
      indicesPut.push_back( 6);
      indicesPut.push_back( 7);
   } 

   static std::vector<double> dv;
   dv.resize(nVar);
   for (int ivar=0; ivar<nVar; ivar++) dv[ivar] = iv[indicesGet.at(ivar)];
   for (int ivar=0;ivar<8;ivar++) {
      double offset = fMin_1[cls][ivar];
      double scale  = 1.0/(fMax_1[cls][ivar]-fMin_1[cls][ivar]);
      iv[indicesPut.at(ivar)] = (dv[ivar]-offset)*scale * 2 - 1;
   }
}

//_______________________________________________________________________
inline void Read3Layers33Decrease::InitTransform()
{
   InitTransform_1();
}

//_______________________________________________________________________
inline void Read3Layers33Decrease::Transform( std::vector<double>& iv, int sigOrBgd ) const
{
   Transform_1( iv, sigOrBgd );
}
