// Class: ReadMLP1
// Automatically generated by MethodBase::MakeClass
//

/* configuration options =====================================================

#GEN -*-*-*-*-*-*-*-*-*-*-*- general info -*-*-*-*-*-*-*-*-*-*-*-

Method         : MLP::MLP1
TMVA Release   : 4.2.0         [262656]
ROOT Release   : 5.34/18       [336402]
Creator        : zxb0111
Date           : Tue Dec  2 15:34:19 2014
Host           : Linux localhost.localdomain 2.6.32-431.17.1.el6.x86_64 #1 SMP Wed May 7 14:14:17 CDT 2014 x86_64 x86_64 x86_64 GNU/Linux
Dir            : /home/zxb0111/seminar
Training events: 35264
Analysis type  : [Classification]


#OPT -*-*-*-*-*-*-*-*-*-*-*-*- options -*-*-*-*-*-*-*-*-*-*-*-*-

# Set by User:
NCycles: "600" [Number of training cycles]
HiddenLayers: "N+5" [Specification of hidden layer architecture]
NeuronType: "sigmoid" [Neuron activation function type]
V: "False" [Verbose output (short form of "VerbosityLevel" below - overrides the latter one)]
VarTransform: "N" [List of variable transformations performed before training, e.g., "D_Background,P_Signal,G,N_AllClasses" for: "Decorrelation, PCA-transformation, Gaussianisation, Normalisation, each for the given class of events ('AllClasses' denotes all events of all classes, if no class indication is given, 'All' is assumed)"]
H: "False" [Print method-specific help message]
TestRate: "5" [Test for overtraining performed at each #th epochs]
UseRegulator: "False" [Use regulator to avoid over-training]
# Default:
RandomSeed: "1" [Random seed for initial synapse weights (0 means unique seed for each run; default value '1')]
EstimatorType: "MSE" [MSE (Mean Square Estimator) for Gaussian Likelihood or CE(Cross-Entropy) for Bernoulli Likelihood]
NeuronInputType: "sum" [Neuron input function type]
VerbosityLevel: "Default" [Verbosity level]
CreateMVAPdfs: "False" [Create PDFs for classifier outputs (signal and background)]
IgnoreNegWeightsInTraining: "False" [Events with negative weights are ignored in the training (but are included for testing and performance evaluation)]
TrainingMethod: "BP" [Train with Back-Propagation (BP), BFGS Algorithm (BFGS), or Genetic Algorithm (GA - slower and worse)]
LearningRate: "2.000000e-02" [ANN learning rate parameter]
DecayRate: "1.000000e-02" [Decay rate for learning parameter]
EpochMonitoring: "False" [Provide epoch-wise monitoring plots according to TestRate (caution: causes big ROOT output file!)]
Sampling: "1.000000e+00" [Only 'Sampling' (randomly selected) events are trained each epoch]
SamplingEpoch: "1.000000e+00" [Sampling is used for the first 'SamplingEpoch' epochs, afterwards, all events are taken for training]
SamplingImportance: "1.000000e+00" [ The sampling weights of events in epochs which successful (worse estimator than before) are multiplied with SamplingImportance, else they are divided.]
SamplingTraining: "True" [The training sample is sampled]
SamplingTesting: "False" [The testing sample is sampled]
ResetStep: "50" [How often BFGS should reset history]
Tau: "3.000000e+00" [LineSearch "size step"]
BPMode: "sequential" [Back-propagation learning mode: sequential or batch]
BatchSize: "-1" [Batch size: number of events/batch, only set if in Batch Mode, -1 for BatchSize=number_of_events]
ConvergenceImprove: "1.000000e-30" [Minimum improvement which counts as improvement (<0 means automatic convergence check is turned off)]
ConvergenceTests: "-1" [Number of steps (without improvement) required for convergence (<0 means automatic convergence check is turned off)]
UpdateLimit: "10000" [Maximum times of regulator update]
CalculateErrors: "False" [Calculates inverse Hessian matrix at the end of the training to be able to calculate the uncertainties of an MVA value]
WeightRange: "1.000000e+00" [Take the events for the estimator calculations from small deviations from the desired value to large deviations only over the weight range]
##


#VAR -*-*-*-*-*-*-*-*-*-*-*-* variables *-*-*-*-*-*-*-*-*-*-*-*-

NVar 8
Jet.PT                        Jet.PT                        Jet.PT                        Jet.PT                                                          'F'    [4.73000001907,2147.32006836]
Jet.Eta                       Jet.Eta                       Jet.Eta                       Jet.Eta                                                         'F'    [-3.99399995804,3.99799990654]
Jet.Phi                       Jet.Phi                       Jet.Phi                       Jet.Phi                                                         'F'    [0,6.28299999237]
Jet.Mass                      Jet.Mass                      Jet.Mass                      Jet.Mass                                                        'F'    [0,251.460006714]
Jet.Ntrk                      Jet.Ntrk                      Jet.Ntrk                      Jet.Ntrk                                                        'F'    [0,77]
Jet.EhadOverEem               Jet.EhadOverEem               Jet.EhadOverEem               Jet.EhadOverEem                                                 'F'    [0,999]
MissingET.Phi                 MissingET.Phi                 MissingET.Phi                 MissingET.Phi                                                   'F'    [0,6.28299999237]
MissingET.MET                 MissingET.MET                 MissingET.MET                 MissingET.MET                                                   'F'    [3.57999992371,1585.47998047]
NSpec 0


============================================================================ */

#include <vector>
#include <cmath>
#include <string>
#include <iostream>

#ifndef IClassifierReader__def
#define IClassifierReader__def

class IClassifierReader {

 public:

   // constructor
   IClassifierReader() : fStatusIsClean( true ) {}
   virtual ~IClassifierReader() {}

   // return classifier response
   virtual double GetMvaValue( const std::vector<double>& inputValues ) const = 0;

   // returns classifier status
   bool IsStatusClean() const { return fStatusIsClean; }

 protected:

   bool fStatusIsClean;
};

#endif

class ReadMLP1 : public IClassifierReader {

 public:

   // constructor
   ReadMLP1( std::vector<std::string>& theInputVars ) 
      : IClassifierReader(),
        fClassName( "ReadMLP1" ),
        fNvars( 8 ),
        fIsNormalised( false )
   {      
      // the training input variables
      const char* inputVars[] = { "Jet.PT", "Jet.Eta", "Jet.Phi", "Jet.Mass", "Jet.Ntrk", "Jet.EhadOverEem", "MissingET.Phi", "MissingET.MET" };

      // sanity checks
      if (theInputVars.size() <= 0) {
         std::cout << "Problem in class \"" << fClassName << "\": empty input vector" << std::endl;
         fStatusIsClean = false;
      }

      if (theInputVars.size() != fNvars) {
         std::cout << "Problem in class \"" << fClassName << "\": mismatch in number of input values: "
                   << theInputVars.size() << " != " << fNvars << std::endl;
         fStatusIsClean = false;
      }

      // validate input variables
      for (size_t ivar = 0; ivar < theInputVars.size(); ivar++) {
         if (theInputVars[ivar] != inputVars[ivar]) {
            std::cout << "Problem in class \"" << fClassName << "\": mismatch in input variable names" << std::endl
                      << " for variable [" << ivar << "]: " << theInputVars[ivar].c_str() << " != " << inputVars[ivar] << std::endl;
            fStatusIsClean = false;
         }
      }

      // initialize min and max vectors (for normalisation)
      fVmin[0] = -1;
      fVmax[0] = 1;
      fVmin[1] = -1;
      fVmax[1] = 0.99999988079071;
      fVmin[2] = -1;
      fVmax[2] = 0.99999988079071;
      fVmin[3] = -1;
      fVmax[3] = 0.99999988079071;
      fVmin[4] = -1;
      fVmax[4] = 1;
      fVmin[5] = -1;
      fVmax[5] = 1;
      fVmin[6] = -1;
      fVmax[6] = 0.99999988079071;
      fVmin[7] = -1;
      fVmax[7] = 1;

      // initialize input variable types
      fType[0] = 'F';
      fType[1] = 'F';
      fType[2] = 'F';
      fType[3] = 'F';
      fType[4] = 'F';
      fType[5] = 'F';
      fType[6] = 'F';
      fType[7] = 'F';

      // initialize constants
      Initialize();

      // initialize transformation
      InitTransform();
   }

   // destructor
   virtual ~ReadMLP1() {
      Clear(); // method-specific
   }

   // the classifier response
   // "inputValues" is a vector of input values in the same order as the 
   // variables given to the constructor
   double GetMvaValue( const std::vector<double>& inputValues ) const;

 private:

   // method-specific destructor
   void Clear();

   // input variable transformation

   double fMin_1[3][8];
   double fMax_1[3][8];
   void InitTransform_1();
   void Transform_1( std::vector<double> & iv, int sigOrBgd ) const;
   void InitTransform();
   void Transform( std::vector<double> & iv, int sigOrBgd ) const;

   // common member variables
   const char* fClassName;

   const size_t fNvars;
   size_t GetNvar()           const { return fNvars; }
   char   GetType( int ivar ) const { return fType[ivar]; }

   // normalisation of input variables
   const bool fIsNormalised;
   bool IsNormalised() const { return fIsNormalised; }
   double fVmin[8];
   double fVmax[8];
   double NormVariable( double x, double xmin, double xmax ) const {
      // normalise to output range: [-1, 1]
      return 2*(x - xmin)/(xmax - xmin) - 1.0;
   }

   // type of input variable: 'F' or 'I'
   char   fType[8];

   // initialize internal variables
   void Initialize();
   double GetMvaValue__( const std::vector<double>& inputValues ) const;

   // private members (method specific)

   double ActivationFnc(double x) const;
   double OutputActivationFnc(double x) const;

   int fLayers;
   int fLayerSize[3];
   double fWeightMatrix0to1[14][9];   // weight matrix from layer 0 to 1
   double fWeightMatrix1to2[1][14];   // weight matrix from layer 1 to 2

   double * fWeights[3];
};

inline void ReadMLP1::Initialize()
{
   // build network structure
   fLayers = 3;
   fLayerSize[0] = 9; fWeights[0] = new double[9]; 
   fLayerSize[1] = 14; fWeights[1] = new double[14]; 
   fLayerSize[2] = 1; fWeights[2] = new double[1]; 
   // weight matrix from layer 0 to 1
   fWeightMatrix0to1[0][0] = -0.319231916712408;
   fWeightMatrix0to1[1][0] = 2.2226777594097;
   fWeightMatrix0to1[2][0] = 0.101745444054678;
   fWeightMatrix0to1[3][0] = 3.33373052714732;
   fWeightMatrix0to1[4][0] = -1.06833650589583;
   fWeightMatrix0to1[5][0] = 0.889119909658818;
   fWeightMatrix0to1[6][0] = -1.4676093434605;
   fWeightMatrix0to1[7][0] = 4.17611883846785;
   fWeightMatrix0to1[8][0] = -0.213494183922064;
   fWeightMatrix0to1[9][0] = -4.46571508724283;
   fWeightMatrix0to1[10][0] = -0.877437067420812;
   fWeightMatrix0to1[11][0] = 0.0866597561364432;
   fWeightMatrix0to1[12][0] = -2.94582534207058;
   fWeightMatrix0to1[0][1] = -1.1783348484406;
   fWeightMatrix0to1[1][1] = -0.0513681345760339;
   fWeightMatrix0to1[2][1] = 0.019710157068977;
   fWeightMatrix0to1[3][1] = -0.089029683712768;
   fWeightMatrix0to1[4][1] = 1.52874030361364;
   fWeightMatrix0to1[5][1] = -0.203091858124586;
   fWeightMatrix0to1[6][1] = -0.086301591110148;
   fWeightMatrix0to1[7][1] = -0.041250351732055;
   fWeightMatrix0to1[8][1] = -0.275870739239986;
   fWeightMatrix0to1[9][1] = -0.0712613592239618;
   fWeightMatrix0to1[10][1] = 0.0412182591378739;
   fWeightMatrix0to1[11][1] = -0.126775827898214;
   fWeightMatrix0to1[12][1] = -0.0254475727264623;
   fWeightMatrix0to1[0][2] = -0.0154189441002171;
   fWeightMatrix0to1[1][2] = -0.994444490010139;
   fWeightMatrix0to1[2][2] = -4.37635594399734;
   fWeightMatrix0to1[3][2] = -0.0604663716738911;
   fWeightMatrix0to1[4][2] = -0.346501372146692;
   fWeightMatrix0to1[5][2] = 2.92267289176448;
   fWeightMatrix0to1[6][2] = -0.00157589592092565;
   fWeightMatrix0to1[7][2] = -0.0579770403531381;
   fWeightMatrix0to1[8][2] = 0.367534900753111;
   fWeightMatrix0to1[9][2] = 0.0179482855424026;
   fWeightMatrix0to1[10][2] = -2.1228310600639;
   fWeightMatrix0to1[11][2] = 4.50265889947269;
   fWeightMatrix0to1[12][2] = 0.0426309019053057;
   fWeightMatrix0to1[0][3] = 0.863631748224528;
   fWeightMatrix0to1[1][3] = 1.94206909624165;
   fWeightMatrix0to1[2][3] = -0.45739226785852;
   fWeightMatrix0to1[3][3] = 0.821511741918447;
   fWeightMatrix0to1[4][3] = 1.78426713121288;
   fWeightMatrix0to1[5][3] = -0.496223067691454;
   fWeightMatrix0to1[6][3] = 1.46268058261995;
   fWeightMatrix0to1[7][3] = 1.31841525929368;
   fWeightMatrix0to1[8][3] = 1.26477343111016;
   fWeightMatrix0to1[9][3] = 0.515068778791328;
   fWeightMatrix0to1[10][3] = 0.531555459213082;
   fWeightMatrix0to1[11][3] = 0.214511868590245;
   fWeightMatrix0to1[12][3] = -1.80428631256645;
   fWeightMatrix0to1[0][4] = -1.02823699197948;
   fWeightMatrix0to1[1][4] = 1.06820207942399;
   fWeightMatrix0to1[2][4] = -0.0177093462796464;
   fWeightMatrix0to1[3][4] = 0.343742641370994;
   fWeightMatrix0to1[4][4] = -0.64970091325285;
   fWeightMatrix0to1[5][4] = -0.734277929430895;
   fWeightMatrix0to1[6][4] = -0.296233932207988;
   fWeightMatrix0to1[7][4] = 0.0842809927697472;
   fWeightMatrix0to1[8][4] = -0.752827433122942;
   fWeightMatrix0to1[9][4] = -0.474877636799076;
   fWeightMatrix0to1[10][4] = 0.823523204289505;
   fWeightMatrix0to1[11][4] = 0.630352203342037;
   fWeightMatrix0to1[12][4] = 0.474592987402587;
   fWeightMatrix0to1[0][5] = 0.0438340283162822;
   fWeightMatrix0to1[1][5] = 0.907100588030183;
   fWeightMatrix0to1[2][5] = 1.19978521734134;
   fWeightMatrix0to1[3][5] = 1.12369599339421;
   fWeightMatrix0to1[4][5] = 0.0559615027118613;
   fWeightMatrix0to1[5][5] = -0.172856077571599;
   fWeightMatrix0to1[6][5] = 1.79200907905199;
   fWeightMatrix0to1[7][5] = 0.678188876741171;
   fWeightMatrix0to1[8][5] = 2.04393223153525;
   fWeightMatrix0to1[9][5] = 3.92335486418149;
   fWeightMatrix0to1[10][5] = -0.862256963542336;
   fWeightMatrix0to1[11][5] = -2.19071228314257;
   fWeightMatrix0to1[12][5] = -0.768939508839791;
   fWeightMatrix0to1[0][6] = 1.03319477067756;
   fWeightMatrix0to1[1][6] = 0.505781637134525;
   fWeightMatrix0to1[2][6] = 4.33317353142052;
   fWeightMatrix0to1[3][6] = -0.0556998230553907;
   fWeightMatrix0to1[4][6] = 0.883361993529406;
   fWeightMatrix0to1[5][6] = -2.96207306091685;
   fWeightMatrix0to1[6][6] = -0.129862450235235;
   fWeightMatrix0to1[7][6] = -0.0262100855738431;
   fWeightMatrix0to1[8][6] = 1.06084666603645;
   fWeightMatrix0to1[9][6] = -0.188576458186104;
   fWeightMatrix0to1[10][6] = 1.95234508080179;
   fWeightMatrix0to1[11][6] = -4.7642638147154;
   fWeightMatrix0to1[12][6] = 0.0451540906169208;
   fWeightMatrix0to1[0][7] = 0.244576783840354;
   fWeightMatrix0to1[1][7] = 0.736696074530034;
   fWeightMatrix0to1[2][7] = 0.481927060200052;
   fWeightMatrix0to1[3][7] = -4.22538170552181;
   fWeightMatrix0to1[4][7] = 2.54011983831497;
   fWeightMatrix0to1[5][7] = 3.50018486074945;
   fWeightMatrix0to1[6][7] = -8.42430902140915;
   fWeightMatrix0to1[7][7] = -11.4288585614072;
   fWeightMatrix0to1[8][7] = 0.896137969654166;
   fWeightMatrix0to1[9][7] = -7.41927206117631;
   fWeightMatrix0to1[10][7] = -3.64286864431543;
   fWeightMatrix0to1[11][7] = -1.99977988545343;
   fWeightMatrix0to1[12][7] = 15.4577578990818;
   fWeightMatrix0to1[0][8] = -1.82363197091813;
   fWeightMatrix0to1[1][8] = 0.984525902565045;
   fWeightMatrix0to1[2][8] = -2.40788442563363;
   fWeightMatrix0to1[3][8] = -0.444395321512968;
   fWeightMatrix0to1[4][8] = -0.622374202786702;
   fWeightMatrix0to1[5][8] = 0.82499152827428;
   fWeightMatrix0to1[6][8] = -3.60378684579127;
   fWeightMatrix0to1[7][8] = -4.48979639789357;
   fWeightMatrix0to1[8][8] = -0.51842305340158;
   fWeightMatrix0to1[9][8] = -4.56079888883888;
   fWeightMatrix0to1[10][8] = -1.32447986428754;
   fWeightMatrix0to1[11][8] = 2.07484100804759;
   fWeightMatrix0to1[12][8] = 7.32833814547286;
   // weight matrix from layer 1 to 2
   fWeightMatrix1to2[0][0] = -0.262049823017079;
   fWeightMatrix1to2[0][1] = 0.438763845245023;
   fWeightMatrix1to2[0][2] = -1.32018827673842;
   fWeightMatrix1to2[0][3] = -2.15927096242125;
   fWeightMatrix1to2[0][4] = -0.390260729471542;
   fWeightMatrix1to2[0][5] = -1.09431939311787;
   fWeightMatrix1to2[0][6] = 0.977603556891153;
   fWeightMatrix1to2[0][7] = 3.99987417437361;
   fWeightMatrix1to2[0][8] = -0.207995719226489;
   fWeightMatrix1to2[0][9] = -0.749091744451409;
   fWeightMatrix1to2[0][10] = -0.970386896661554;
   fWeightMatrix1to2[0][11] = -1.24150661728723;
   fWeightMatrix1to2[0][12] = 3.01140633637072;
   fWeightMatrix1to2[0][13] = 0.539186752150438;
}

inline double ReadMLP1::GetMvaValue__( const std::vector<double>& inputValues ) const
{
   if (inputValues.size() != (unsigned int)fLayerSize[0]-1) {
      std::cout << "Input vector needs to be of size " << fLayerSize[0]-1 << std::endl;
      return 0;
   }

   for (int l=0; l<fLayers; l++)
      for (int i=0; i<fLayerSize[l]; i++) fWeights[l][i]=0;

   for (int l=0; l<fLayers-1; l++)
      fWeights[l][fLayerSize[l]-1]=1;

   for (int i=0; i<fLayerSize[0]-1; i++)
      fWeights[0][i]=inputValues[i];

   // layer 0 to 1
   for (int o=0; o<fLayerSize[1]-1; o++) {
      for (int i=0; i<fLayerSize[0]; i++) {
         double inputVal = fWeightMatrix0to1[o][i] * fWeights[0][i];
         fWeights[1][o] += inputVal;
      }
      fWeights[1][o] = ActivationFnc(fWeights[1][o]);
   }
   // layer 1 to 2
   for (int o=0; o<fLayerSize[2]; o++) {
      for (int i=0; i<fLayerSize[1]; i++) {
         double inputVal = fWeightMatrix1to2[o][i] * fWeights[1][i];
         fWeights[2][o] += inputVal;
      }
      fWeights[2][o] = OutputActivationFnc(fWeights[2][o]);
   }

   return fWeights[2][0];
}

double ReadMLP1::ActivationFnc(double x) const {
   // sigmoid
   return 1.0/(1.0+exp(-x));
}
double ReadMLP1::OutputActivationFnc(double x) const {
   // identity
   return x;
}
   
// Clean up
inline void ReadMLP1::Clear() 
{
   // clean up the arrays
   for (int lIdx = 0; lIdx < 3; lIdx++) {
      delete[] fWeights[lIdx];
   }
}
   inline double ReadMLP1::GetMvaValue( const std::vector<double>& inputValues ) const
   {
      // classifier response value
      double retval = 0;

      // classifier response, sanity check first
      if (!IsStatusClean()) {
         std::cout << "Problem in class \"" << fClassName << "\": cannot return classifier response"
                   << " because status is dirty" << std::endl;
         retval = 0;
      }
      else {
         if (IsNormalised()) {
            // normalise variables
            std::vector<double> iV;
            iV.reserve(inputValues.size());
            int ivar = 0;
            for (std::vector<double>::const_iterator varIt = inputValues.begin();
                 varIt != inputValues.end(); varIt++, ivar++) {
               iV.push_back(NormVariable( *varIt, fVmin[ivar], fVmax[ivar] ));
            }
            Transform( iV, -1 );
            retval = GetMvaValue__( iV );
         }
         else {
            std::vector<double> iV;
            int ivar = 0;
            for (std::vector<double>::const_iterator varIt = inputValues.begin();
                 varIt != inputValues.end(); varIt++, ivar++) {
               iV.push_back(*varIt);
            }
            Transform( iV, -1 );
            retval = GetMvaValue__( iV );
         }
      }

      return retval;
   }

//_______________________________________________________________________
inline void ReadMLP1::InitTransform_1()
{
   // Normalization transformation, initialisation
   fMin_1[0][0] = 5;
   fMax_1[0][0] = 2147.32006836;
   fMin_1[1][0] = 4.73000001907;
   fMax_1[1][0] = 817.520019531;
   fMin_1[2][0] = 4.73000001907;
   fMax_1[2][0] = 2147.32006836;
   fMin_1[0][1] = -3.98099994659;
   fMax_1[0][1] = 3.99799990654;
   fMin_1[1][1] = -3.99399995804;
   fMax_1[1][1] = 3.99699997902;
   fMin_1[2][1] = -3.99399995804;
   fMax_1[2][1] = 3.99799990654;
   fMin_1[0][2] = 0;
   fMax_1[0][2] = 6.28299999237;
   fMin_1[1][2] = 0;
   fMax_1[1][2] = 6.28299999237;
   fMin_1[2][2] = 0;
   fMax_1[2][2] = 6.28299999237;
   fMin_1[0][3] = 0;
   fMax_1[0][3] = 251.460006714;
   fMin_1[1][3] = 0;
   fMax_1[1][3] = 184.169998169;
   fMin_1[2][3] = 0;
   fMax_1[2][3] = 251.460006714;
   fMin_1[0][4] = 0;
   fMax_1[0][4] = 60;
   fMin_1[1][4] = 0;
   fMax_1[1][4] = 77;
   fMin_1[2][4] = 0;
   fMax_1[2][4] = 77;
   fMin_1[0][5] = 0;
   fMax_1[0][5] = 999;
   fMin_1[1][5] = 0;
   fMax_1[1][5] = 999;
   fMin_1[2][5] = 0;
   fMax_1[2][5] = 999;
   fMin_1[0][6] = 0;
   fMax_1[0][6] = 6.28299999237;
   fMin_1[1][6] = 0.0010000000475;
   fMax_1[1][6] = 6.28200006485;
   fMin_1[2][6] = 0;
   fMax_1[2][6] = 6.28299999237;
   fMin_1[0][7] = 3.57999992371;
   fMax_1[0][7] = 1585.47998047;
   fMin_1[1][7] = 100.010002136;
   fMax_1[1][7] = 662.650024414;
   fMin_1[2][7] = 3.57999992371;
   fMax_1[2][7] = 1585.47998047;
}

//_______________________________________________________________________
inline void ReadMLP1::Transform_1( std::vector<double>& iv, int cls) const
{
   // Normalization transformation
   if (cls < 0 || cls > 2) {
   if (2 > 1 ) cls = 2;
      else cls = 2;
   }
   const int nVar = 8;

   // get indices of used variables

   // define the indices of the variables which are transformed by this transformation
   static std::vector<int> indicesGet;
   static std::vector<int> indicesPut;

   if ( indicesGet.empty() ) { 
      indicesGet.reserve(fNvars);
      indicesGet.push_back( 0);
      indicesGet.push_back( 1);
      indicesGet.push_back( 2);
      indicesGet.push_back( 3);
      indicesGet.push_back( 4);
      indicesGet.push_back( 5);
      indicesGet.push_back( 6);
      indicesGet.push_back( 7);
   } 
   if ( indicesPut.empty() ) { 
      indicesPut.reserve(fNvars);
      indicesPut.push_back( 0);
      indicesPut.push_back( 1);
      indicesPut.push_back( 2);
      indicesPut.push_back( 3);
      indicesPut.push_back( 4);
      indicesPut.push_back( 5);
      indicesPut.push_back( 6);
      indicesPut.push_back( 7);
   } 

   static std::vector<double> dv;
   dv.resize(nVar);
   for (int ivar=0; ivar<nVar; ivar++) dv[ivar] = iv[indicesGet.at(ivar)];
   for (int ivar=0;ivar<8;ivar++) {
      double offset = fMin_1[cls][ivar];
      double scale  = 1.0/(fMax_1[cls][ivar]-fMin_1[cls][ivar]);
      iv[indicesPut.at(ivar)] = (dv[ivar]-offset)*scale * 2 - 1;
   }
}

//_______________________________________________________________________
inline void ReadMLP1::InitTransform()
{
   InitTransform_1();
}

//_______________________________________________________________________
inline void ReadMLP1::Transform( std::vector<double>& iv, int sigOrBgd ) const
{
   Transform_1( iv, sigOrBgd );
}
