// Class: ReadDistro15Increase
// Automatically generated by MethodBase::MakeClass
//

/* configuration options =====================================================

#GEN -*-*-*-*-*-*-*-*-*-*-*- general info -*-*-*-*-*-*-*-*-*-*-*-

Method         : MLP::Distro15Increase
TMVA Release   : 4.2.0         [262656]
ROOT Release   : 5.34/18       [336402]
Creator        : zxb0111
Date           : Thu Dec  4 11:46:06 2014
Host           : Linux localhost.localdomain 2.6.32-431.17.1.el6.x86_64 #1 SMP Wed May 7 14:14:17 CDT 2014 x86_64 x86_64 x86_64 GNU/Linux
Dir            : /home/zxb0111/seminar
Training events: 34086
Analysis type  : [Classification]


#OPT -*-*-*-*-*-*-*-*-*-*-*-*- options -*-*-*-*-*-*-*-*-*-*-*-*-

# Set by User:
NCycles: "600" [Number of training cycles]
HiddenLayers: "8,4,3" [Specification of hidden layer architecture]
NeuronType: "sigmoid" [Neuron activation function type]
VarTransform: "N" [List of variable transformations performed before training, e.g., "D_Background,P_Signal,G,N_AllClasses" for: "Decorrelation, PCA-transformation, Gaussianisation, Normalisation, each for the given class of events ('AllClasses' denotes all events of all classes, if no class indication is given, 'All' is assumed)"]
TestRate: "5" [Test for overtraining performed at each #th epochs]
UseRegulator: "False" [Use regulator to avoid over-training]
# Default:
RandomSeed: "1" [Random seed for initial synapse weights (0 means unique seed for each run; default value '1')]
EstimatorType: "MSE" [MSE (Mean Square Estimator) for Gaussian Likelihood or CE(Cross-Entropy) for Bernoulli Likelihood]
NeuronInputType: "sum" [Neuron input function type]
V: "False" [Verbose output (short form of "VerbosityLevel" below - overrides the latter one)]
VerbosityLevel: "Default" [Verbosity level]
H: "False" [Print method-specific help message]
CreateMVAPdfs: "False" [Create PDFs for classifier outputs (signal and background)]
IgnoreNegWeightsInTraining: "False" [Events with negative weights are ignored in the training (but are included for testing and performance evaluation)]
TrainingMethod: "BP" [Train with Back-Propagation (BP), BFGS Algorithm (BFGS), or Genetic Algorithm (GA - slower and worse)]
LearningRate: "2.000000e-02" [ANN learning rate parameter]
DecayRate: "1.000000e-02" [Decay rate for learning parameter]
EpochMonitoring: "False" [Provide epoch-wise monitoring plots according to TestRate (caution: causes big ROOT output file!)]
Sampling: "1.000000e+00" [Only 'Sampling' (randomly selected) events are trained each epoch]
SamplingEpoch: "1.000000e+00" [Sampling is used for the first 'SamplingEpoch' epochs, afterwards, all events are taken for training]
SamplingImportance: "1.000000e+00" [ The sampling weights of events in epochs which successful (worse estimator than before) are multiplied with SamplingImportance, else they are divided.]
SamplingTraining: "True" [The training sample is sampled]
SamplingTesting: "False" [The testing sample is sampled]
ResetStep: "50" [How often BFGS should reset history]
Tau: "3.000000e+00" [LineSearch "size step"]
BPMode: "sequential" [Back-propagation learning mode: sequential or batch]
BatchSize: "-1" [Batch size: number of events/batch, only set if in Batch Mode, -1 for BatchSize=number_of_events]
ConvergenceImprove: "1.000000e-30" [Minimum improvement which counts as improvement (<0 means automatic convergence check is turned off)]
ConvergenceTests: "-1" [Number of steps (without improvement) required for convergence (<0 means automatic convergence check is turned off)]
UpdateLimit: "10000" [Maximum times of regulator update]
CalculateErrors: "False" [Calculates inverse Hessian matrix at the end of the training to be able to calculate the uncertainties of an MVA value]
WeightRange: "1.000000e+00" [Take the events for the estimator calculations from small deviations from the desired value to large deviations only over the weight range]
##


#VAR -*-*-*-*-*-*-*-*-*-*-*-* variables *-*-*-*-*-*-*-*-*-*-*-*-

NVar 8
Jet.PT                        Jet.PT                        Jet.PT                        Jet.PT                                                          'F'    [4.73000001907,2543.40991211]
Jet.Eta                       Jet.Eta                       Jet.Eta                       Jet.Eta                                                         'F'    [-3.99300003052,3.99099993706]
Jet.Phi                       Jet.Phi                       Jet.Phi                       Jet.Phi                                                         'F'    [0,6.28299999237]
Jet.Mass                      Jet.Mass                      Jet.Mass                      Jet.Mass                                                        'F'    [0,258.730010986]
Jet.Ntrk                      Jet.Ntrk                      Jet.Ntrk                      Jet.Ntrk                                                        'F'    [0,61]
Jet.EhadOverEem               Jet.EhadOverEem               Jet.EhadOverEem               Jet.EhadOverEem                                                 'F'    [0,999]
MissingET.Phi                 MissingET.Phi                 MissingET.Phi                 MissingET.Phi                                                   'F'    [0,6.28299999237]
MissingET.MET                 MissingET.MET                 MissingET.MET                 MissingET.MET                                                   'F'    [100.010002136,1585.47998047]
NSpec 0


============================================================================ */

#include <vector>
#include <cmath>
#include <string>
#include <iostream>

#ifndef IClassifierReader__def
#define IClassifierReader__def

class IClassifierReader {

 public:

   // constructor
   IClassifierReader() : fStatusIsClean( true ) {}
   virtual ~IClassifierReader() {}

   // return classifier response
   virtual double GetMvaValue( const std::vector<double>& inputValues ) const = 0;

   // returns classifier status
   bool IsStatusClean() const { return fStatusIsClean; }

 protected:

   bool fStatusIsClean;
};

#endif

class ReadDistro15Increase : public IClassifierReader {

 public:

   // constructor
   ReadDistro15Increase( std::vector<std::string>& theInputVars ) 
      : IClassifierReader(),
        fClassName( "ReadDistro15Increase" ),
        fNvars( 8 ),
        fIsNormalised( false )
   {      
      // the training input variables
      const char* inputVars[] = { "Jet.PT", "Jet.Eta", "Jet.Phi", "Jet.Mass", "Jet.Ntrk", "Jet.EhadOverEem", "MissingET.Phi", "MissingET.MET" };

      // sanity checks
      if (theInputVars.size() <= 0) {
         std::cout << "Problem in class \"" << fClassName << "\": empty input vector" << std::endl;
         fStatusIsClean = false;
      }

      if (theInputVars.size() != fNvars) {
         std::cout << "Problem in class \"" << fClassName << "\": mismatch in number of input values: "
                   << theInputVars.size() << " != " << fNvars << std::endl;
         fStatusIsClean = false;
      }

      // validate input variables
      for (size_t ivar = 0; ivar < theInputVars.size(); ivar++) {
         if (theInputVars[ivar] != inputVars[ivar]) {
            std::cout << "Problem in class \"" << fClassName << "\": mismatch in input variable names" << std::endl
                      << " for variable [" << ivar << "]: " << theInputVars[ivar].c_str() << " != " << inputVars[ivar] << std::endl;
            fStatusIsClean = false;
         }
      }

      // initialize min and max vectors (for normalisation)
      fVmin[0] = -1;
      fVmax[0] = 1;
      fVmin[1] = -1;
      fVmax[1] = 1;
      fVmin[2] = -1;
      fVmax[2] = 0.99999988079071;
      fVmin[3] = -1;
      fVmax[3] = 1;
      fVmin[4] = -1;
      fVmax[4] = 0.99999988079071;
      fVmin[5] = -1;
      fVmax[5] = 1;
      fVmin[6] = -1;
      fVmax[6] = 0.99999988079071;
      fVmin[7] = -1;
      fVmax[7] = 1;

      // initialize input variable types
      fType[0] = 'F';
      fType[1] = 'F';
      fType[2] = 'F';
      fType[3] = 'F';
      fType[4] = 'F';
      fType[5] = 'F';
      fType[6] = 'F';
      fType[7] = 'F';

      // initialize constants
      Initialize();

      // initialize transformation
      InitTransform();
   }

   // destructor
   virtual ~ReadDistro15Increase() {
      Clear(); // method-specific
   }

   // the classifier response
   // "inputValues" is a vector of input values in the same order as the 
   // variables given to the constructor
   double GetMvaValue( const std::vector<double>& inputValues ) const;

 private:

   // method-specific destructor
   void Clear();

   // input variable transformation

   double fMin_1[3][8];
   double fMax_1[3][8];
   void InitTransform_1();
   void Transform_1( std::vector<double> & iv, int sigOrBgd ) const;
   void InitTransform();
   void Transform( std::vector<double> & iv, int sigOrBgd ) const;

   // common member variables
   const char* fClassName;

   const size_t fNvars;
   size_t GetNvar()           const { return fNvars; }
   char   GetType( int ivar ) const { return fType[ivar]; }

   // normalisation of input variables
   const bool fIsNormalised;
   bool IsNormalised() const { return fIsNormalised; }
   double fVmin[8];
   double fVmax[8];
   double NormVariable( double x, double xmin, double xmax ) const {
      // normalise to output range: [-1, 1]
      return 2*(x - xmin)/(xmax - xmin) - 1.0;
   }

   // type of input variable: 'F' or 'I'
   char   fType[8];

   // initialize internal variables
   void Initialize();
   double GetMvaValue__( const std::vector<double>& inputValues ) const;

   // private members (method specific)

   double ActivationFnc(double x) const;
   double OutputActivationFnc(double x) const;

   int fLayers;
   int fLayerSize[5];
   double fWeightMatrix0to1[9][9];   // weight matrix from layer 0 to 1
   double fWeightMatrix1to2[5][9];   // weight matrix from layer 1 to 2
   double fWeightMatrix2to3[4][5];   // weight matrix from layer 2 to 3
   double fWeightMatrix3to4[1][4];   // weight matrix from layer 3 to 4

   double * fWeights[5];
};

inline void ReadDistro15Increase::Initialize()
{
   // build network structure
   fLayers = 5;
   fLayerSize[0] = 9; fWeights[0] = new double[9]; 
   fLayerSize[1] = 9; fWeights[1] = new double[9]; 
   fLayerSize[2] = 5; fWeights[2] = new double[5]; 
   fLayerSize[3] = 4; fWeights[3] = new double[4]; 
   fLayerSize[4] = 1; fWeights[4] = new double[1]; 
   // weight matrix from layer 0 to 1
   fWeightMatrix0to1[0][0] = -0.413390716729381;
   fWeightMatrix0to1[1][0] = 3.75628315675332;
   fWeightMatrix0to1[2][0] = 0.971988153412242;
   fWeightMatrix0to1[3][0] = 2.01977665904505;
   fWeightMatrix0to1[4][0] = -1.88274333608933;
   fWeightMatrix0to1[5][0] = -1.58495285673771;
   fWeightMatrix0to1[6][0] = -8.20757205243376;
   fWeightMatrix0to1[7][0] = 2.11470650630589;
   fWeightMatrix0to1[0][1] = -0.650888388547075;
   fWeightMatrix0to1[1][1] = -0.117263849681316;
   fWeightMatrix0to1[2][1] = -0.159493388394542;
   fWeightMatrix0to1[3][1] = -0.258535221375041;
   fWeightMatrix0to1[4][1] = -1.32451572321096;
   fWeightMatrix0to1[5][1] = -0.461927217185358;
   fWeightMatrix0to1[6][1] = -0.124372538923607;
   fWeightMatrix0to1[7][1] = 0.701999140480178;
   fWeightMatrix0to1[0][2] = -1.02178060871091;
   fWeightMatrix0to1[1][2] = -0.0967441193334501;
   fWeightMatrix0to1[2][2] = 1.80640890082024;
   fWeightMatrix0to1[3][2] = 1.45061437461838;
   fWeightMatrix0to1[4][2] = -0.289075363351011;
   fWeightMatrix0to1[5][2] = 0.0996799733538117;
   fWeightMatrix0to1[6][2] = -0.00780478034296674;
   fWeightMatrix0to1[7][2] = 0.11083979870606;
   fWeightMatrix0to1[0][3] = -0.737042405859301;
   fWeightMatrix0to1[1][3] = 1.67207974935957;
   fWeightMatrix0to1[2][3] = 1.09953281753886;
   fWeightMatrix0to1[3][3] = -0.857827041510381;
   fWeightMatrix0to1[4][3] = -1.76892071958365;
   fWeightMatrix0to1[5][3] = -0.146850246005012;
   fWeightMatrix0to1[6][3] = -1.09654567474278;
   fWeightMatrix0to1[7][3] = 1.77081517513924;
   fWeightMatrix0to1[0][4] = 0.0614754974015223;
   fWeightMatrix0to1[1][4] = -0.298184596096368;
   fWeightMatrix0to1[2][4] = 1.16213994155145;
   fWeightMatrix0to1[3][4] = 0.123629668944463;
   fWeightMatrix0to1[4][4] = -1.37713613852736;
   fWeightMatrix0to1[5][4] = 1.23893951491682;
   fWeightMatrix0to1[6][4] = -0.749407917683451;
   fWeightMatrix0to1[7][4] = 1.17361690863351;
   fWeightMatrix0to1[0][5] = 1.37673951967217;
   fWeightMatrix0to1[1][5] = 0.454046101149861;
   fWeightMatrix0to1[2][5] = 1.07503241847863;
   fWeightMatrix0to1[3][5] = 0.747022526835973;
   fWeightMatrix0to1[4][5] = -0.587275036381855;
   fWeightMatrix0to1[5][5] = -1.7053216822791;
   fWeightMatrix0to1[6][5] = 3.25084955246417;
   fWeightMatrix0to1[7][5] = 0.374839248674209;
   fWeightMatrix0to1[0][6] = 1.42256195887038;
   fWeightMatrix0to1[1][6] = 0.213957234255506;
   fWeightMatrix0to1[2][6] = 1.81395425243415;
   fWeightMatrix0to1[3][6] = 1.59667066879939;
   fWeightMatrix0to1[4][6] = -1.76326675106181;
   fWeightMatrix0to1[5][6] = 1.20476191659161;
   fWeightMatrix0to1[6][6] = 0.301384827758864;
   fWeightMatrix0to1[7][6] = -0.75675790070876;
   fWeightMatrix0to1[0][7] = -1.14372752072884;
   fWeightMatrix0to1[1][7] = -9.92373626726384;
   fWeightMatrix0to1[2][7] = 1.8421757190117;
   fWeightMatrix0to1[3][7] = 0.736415646084362;
   fWeightMatrix0to1[4][7] = -1.4783618298794;
   fWeightMatrix0to1[5][7] = 1.62107351164835;
   fWeightMatrix0to1[6][7] = -0.674542635414313;
   fWeightMatrix0to1[7][7] = 0.953837793882184;
   fWeightMatrix0to1[0][8] = 1.95130686026195;
   fWeightMatrix0to1[1][8] = -2.7219914711126;
   fWeightMatrix0to1[2][8] = 1.31435458677154;
   fWeightMatrix0to1[3][8] = -1.26904840289621;
   fWeightMatrix0to1[4][8] = 0.595514175295807;
   fWeightMatrix0to1[5][8] = -0.924171346820932;
   fWeightMatrix0to1[6][8] = -4.38317277687557;
   fWeightMatrix0to1[7][8] = -1.75334667963344;
   // weight matrix from layer 1 to 2
   fWeightMatrix1to2[0][0] = 2.80255759875544;
   fWeightMatrix1to2[1][0] = 2.9773829147718;
   fWeightMatrix1to2[2][0] = 1.55456322721006;
   fWeightMatrix1to2[3][0] = -0.0849992352643428;
   fWeightMatrix1to2[0][1] = -5.63418391253915;
   fWeightMatrix1to2[1][1] = -4.36126713816903;
   fWeightMatrix1to2[2][1] = 1.49196324007717;
   fWeightMatrix1to2[3][1] = 0.205647226416062;
   fWeightMatrix1to2[0][2] = 2.78868372066839;
   fWeightMatrix1to2[1][2] = 1.44431128848513;
   fWeightMatrix1to2[2][2] = 1.08347489499379;
   fWeightMatrix1to2[3][2] = -0.516795339118324;
   fWeightMatrix1to2[0][3] = -0.0243965322073651;
   fWeightMatrix1to2[1][3] = 0.610354448255572;
   fWeightMatrix1to2[2][3] = 1.35828425162948;
   fWeightMatrix1to2[3][3] = -1.01405853071628;
   fWeightMatrix1to2[0][4] = 0.800997894408719;
   fWeightMatrix1to2[1][4] = 0.568803122356656;
   fWeightMatrix1to2[2][4] = 0.141629983115794;
   fWeightMatrix1to2[3][4] = 0.0771813883011804;
   fWeightMatrix1to2[0][5] = 2.11382018718185;
   fWeightMatrix1to2[1][5] = -0.96728966595949;
   fWeightMatrix1to2[2][5] = -1.21268797471843;
   fWeightMatrix1to2[3][5] = 2.09450036119746;
   fWeightMatrix1to2[0][6] = -3.00351502436003;
   fWeightMatrix1to2[1][6] = -4.67601209748446;
   fWeightMatrix1to2[2][6] = -4.13056901267864;
   fWeightMatrix1to2[3][6] = -0.150393560331468;
   fWeightMatrix1to2[0][7] = -1.81254621035909;
   fWeightMatrix1to2[1][7] = -1.55190153480921;
   fWeightMatrix1to2[2][7] = 0.753336926578787;
   fWeightMatrix1to2[3][7] = 1.66320691537796;
   fWeightMatrix1to2[0][8] = 1.24246947886536;
   fWeightMatrix1to2[1][8] = 3.91069917408295;
   fWeightMatrix1to2[2][8] = -0.592467626664027;
   fWeightMatrix1to2[3][8] = -0.570238872433566;
   // weight matrix from layer 2 to 3
   fWeightMatrix2to3[0][0] = 0.65428874321381;
   fWeightMatrix2to3[1][0] = 3.6144427142615;
   fWeightMatrix2to3[2][0] = -2.77460575101047;
   fWeightMatrix2to3[0][1] = 2.06063143820287;
   fWeightMatrix2to3[1][1] = 4.0223371725621;
   fWeightMatrix2to3[2][1] = -0.810998426289677;
   fWeightMatrix2to3[0][2] = -0.946306627983058;
   fWeightMatrix2to3[1][2] = 3.43084919063913;
   fWeightMatrix2to3[2][2] = 0.179952356815832;
   fWeightMatrix2to3[0][3] = -1.86790552786966;
   fWeightMatrix2to3[1][3] = -0.275566047881949;
   fWeightMatrix2to3[2][3] = -0.512729376996065;
   fWeightMatrix2to3[0][4] = -1.52206998450305;
   fWeightMatrix2to3[1][4] = -2.95376322471193;
   fWeightMatrix2to3[2][4] = -0.647648176373346;
   // weight matrix from layer 3 to 4
   fWeightMatrix3to4[0][0] = 0.24682430401031;
   fWeightMatrix3to4[0][1] = 1.30291820548067;
   fWeightMatrix3to4[0][2] = 0.7681656020541;
   fWeightMatrix3to4[0][3] = -0.413847900204214;
}

inline double ReadDistro15Increase::GetMvaValue__( const std::vector<double>& inputValues ) const
{
   if (inputValues.size() != (unsigned int)fLayerSize[0]-1) {
      std::cout << "Input vector needs to be of size " << fLayerSize[0]-1 << std::endl;
      return 0;
   }

   for (int l=0; l<fLayers; l++)
      for (int i=0; i<fLayerSize[l]; i++) fWeights[l][i]=0;

   for (int l=0; l<fLayers-1; l++)
      fWeights[l][fLayerSize[l]-1]=1;

   for (int i=0; i<fLayerSize[0]-1; i++)
      fWeights[0][i]=inputValues[i];

   // layer 0 to 1
   for (int o=0; o<fLayerSize[1]-1; o++) {
      for (int i=0; i<fLayerSize[0]; i++) {
         double inputVal = fWeightMatrix0to1[o][i] * fWeights[0][i];
         fWeights[1][o] += inputVal;
      }
      fWeights[1][o] = ActivationFnc(fWeights[1][o]);
   }
   // layer 1 to 2
   for (int o=0; o<fLayerSize[2]-1; o++) {
      for (int i=0; i<fLayerSize[1]; i++) {
         double inputVal = fWeightMatrix1to2[o][i] * fWeights[1][i];
         fWeights[2][o] += inputVal;
      }
      fWeights[2][o] = ActivationFnc(fWeights[2][o]);
   }
   // layer 2 to 3
   for (int o=0; o<fLayerSize[3]-1; o++) {
      for (int i=0; i<fLayerSize[2]; i++) {
         double inputVal = fWeightMatrix2to3[o][i] * fWeights[2][i];
         fWeights[3][o] += inputVal;
      }
      fWeights[3][o] = ActivationFnc(fWeights[3][o]);
   }
   // layer 3 to 4
   for (int o=0; o<fLayerSize[4]; o++) {
      for (int i=0; i<fLayerSize[3]; i++) {
         double inputVal = fWeightMatrix3to4[o][i] * fWeights[3][i];
         fWeights[4][o] += inputVal;
      }
      fWeights[4][o] = OutputActivationFnc(fWeights[4][o]);
   }

   return fWeights[4][0];
}

double ReadDistro15Increase::ActivationFnc(double x) const {
   // sigmoid
   return 1.0/(1.0+exp(-x));
}
double ReadDistro15Increase::OutputActivationFnc(double x) const {
   // identity
   return x;
}
   
// Clean up
inline void ReadDistro15Increase::Clear() 
{
   // clean up the arrays
   for (int lIdx = 0; lIdx < 5; lIdx++) {
      delete[] fWeights[lIdx];
   }
}
   inline double ReadDistro15Increase::GetMvaValue( const std::vector<double>& inputValues ) const
   {
      // classifier response value
      double retval = 0;

      // classifier response, sanity check first
      if (!IsStatusClean()) {
         std::cout << "Problem in class \"" << fClassName << "\": cannot return classifier response"
                   << " because status is dirty" << std::endl;
         retval = 0;
      }
      else {
         if (IsNormalised()) {
            // normalise variables
            std::vector<double> iV;
            iV.resize(inputValues.size());
            int ivar = 0;
            for (std::vector<double>::const_iterator varIt = inputValues.begin();
                 varIt != inputValues.end(); varIt++, ivar++) {
               iV.push_back(NormVariable( *varIt, fVmin[ivar], fVmax[ivar] ));
            }
            Transform( iV, -1 );
            retval = GetMvaValue__( iV );
         }
         else {
            std::vector<double> iV;
            int ivar = 0;
            for (std::vector<double>::const_iterator varIt = inputValues.begin();
                 varIt != inputValues.end(); varIt++, ivar++) {
               iV.push_back(*varIt);
            }
            Transform( iV, -1 );
            retval = GetMvaValue__( iV );
         }
      }

      return retval;
   }

//_______________________________________________________________________
inline void ReadDistro15Increase::InitTransform_1()
{
   // Normalization transformation, initialisation
   fMin_1[0][0] = 5;
   fMax_1[0][0] = 2543.40991211;
   fMin_1[1][0] = 4.73000001907;
   fMax_1[1][0] = 817.520019531;
   fMin_1[2][0] = 4.73000001907;
   fMax_1[2][0] = 2543.40991211;
   fMin_1[0][1] = -3.99099993706;
   fMax_1[0][1] = 3.99099993706;
   fMin_1[1][1] = -3.99300003052;
   fMax_1[1][1] = 3.99000000954;
   fMin_1[2][1] = -3.99300003052;
   fMax_1[2][1] = 3.99099993706;
   fMin_1[0][2] = 0;
   fMax_1[0][2] = 6.28299999237;
   fMin_1[1][2] = 0;
   fMax_1[1][2] = 6.28299999237;
   fMin_1[2][2] = 0;
   fMax_1[2][2] = 6.28299999237;
   fMin_1[0][3] = 0;
   fMax_1[0][3] = 258.730010986;
   fMin_1[1][3] = 0;
   fMax_1[1][3] = 159.369995117;
   fMin_1[2][3] = 0;
   fMax_1[2][3] = 258.730010986;
   fMin_1[0][4] = 0;
   fMax_1[0][4] = 61;
   fMin_1[1][4] = 0;
   fMax_1[1][4] = 59;
   fMin_1[2][4] = 0;
   fMax_1[2][4] = 61;
   fMin_1[0][5] = 0;
   fMax_1[0][5] = 999;
   fMin_1[1][5] = 0;
   fMax_1[1][5] = 999;
   fMin_1[2][5] = 0;
   fMax_1[2][5] = 999;
   fMin_1[0][6] = 0;
   fMax_1[0][6] = 6.28299999237;
   fMin_1[1][6] = 0.0010000000475;
   fMax_1[1][6] = 6.28200006485;
   fMin_1[2][6] = 0;
   fMax_1[2][6] = 6.28299999237;
   fMin_1[0][7] = 100.019996643;
   fMax_1[0][7] = 1585.47998047;
   fMin_1[1][7] = 100.010002136;
   fMax_1[1][7] = 662.650024414;
   fMin_1[2][7] = 100.010002136;
   fMax_1[2][7] = 1585.47998047;
}

//_______________________________________________________________________
inline void ReadDistro15Increase::Transform_1( std::vector<double>& iv, int cls) const
{
   // Normalization transformation
   if (cls < 0 || cls > 2) {
   if (2 > 1 ) cls = 2;
      else cls = 2;
   }
   const int nVar = 8;

   // get indices of used variables

   // define the indices of the variables which are transformed by this transformation
   static std::vector<int> indicesGet;
   static std::vector<int> indicesPut;

   if ( indicesGet.empty() ) { 
      indicesGet.reserve(nVar);
      indicesGet.push_back( 0);
      indicesGet.push_back( 1);
      indicesGet.push_back( 2);
      indicesGet.push_back( 3);
      indicesGet.push_back( 4);
      indicesGet.push_back( 5);
      indicesGet.push_back( 6);
      indicesGet.push_back( 7);
   } 
   if ( indicesPut.empty() ) { 
      indicesPut.reserve(nVar);
      indicesPut.push_back( 0);
      indicesPut.push_back( 1);
      indicesPut.push_back( 2);
      indicesPut.push_back( 3);
      indicesPut.push_back( 4);
      indicesPut.push_back( 5);
      indicesPut.push_back( 6);
      indicesPut.push_back( 7);
   } 

   static std::vector<double> dv;
   dv.resize(nVar);
   for (int ivar=0; ivar<nVar; ivar++) dv[ivar] = iv[indicesGet.at(ivar)];
   for (int ivar=0;ivar<8;ivar++) {
      double offset = fMin_1[cls][ivar];
      double scale  = 1.0/(fMax_1[cls][ivar]-fMin_1[cls][ivar]);
      iv[indicesPut.at(ivar)] = (dv[ivar]-offset)*scale * 2 - 1;
   }
}

//_______________________________________________________________________
inline void ReadDistro15Increase::InitTransform()
{
   InitTransform_1();
}

//_______________________________________________________________________
inline void ReadDistro15Increase::Transform( std::vector<double>& iv, int sigOrBgd ) const
{
   Transform_1( iv, sigOrBgd );
}
