// Class: ReadMLP
// Automatically generated by MethodBase::MakeClass
//

/* configuration options =====================================================

#GEN -*-*-*-*-*-*-*-*-*-*-*- general info -*-*-*-*-*-*-*-*-*-*-*-

Method         : MLP::MLP
TMVA Release   : 4.2.0         [262656]
ROOT Release   : 5.34/18       [336402]
Creator        : zxb0111
Date           : Mon Dec  1 16:28:02 2014
Host           : Linux localhost.localdomain 2.6.32-431.17.1.el6.x86_64 #1 SMP Wed May 7 14:14:17 CDT 2014 x86_64 x86_64 x86_64 GNU/Linux
Dir            : /home/zxb0111/seminar
Training events: 35264
Analysis type  : [Classification]


#OPT -*-*-*-*-*-*-*-*-*-*-*-*- options -*-*-*-*-*-*-*-*-*-*-*-*-

# Set by User:
NCycles: "600" [Number of training cycles]
HiddenLayers: "N+5" [Specification of hidden layer architecture]
NeuronType: "sigmoid" [Neuron activation function type]
V: "False" [Verbose output (short form of "VerbosityLevel" below - overrides the latter one)]
VarTransform: "N" [List of variable transformations performed before training, e.g., "D_Background,P_Signal,G,N_AllClasses" for: "Decorrelation, PCA-transformation, Gaussianisation, Normalisation, each for the given class of events ('AllClasses' denotes all events of all classes, if no class indication is given, 'All' is assumed)"]
H: "False" [Print method-specific help message]
TestRate: "5" [Test for overtraining performed at each #th epochs]
UseRegulator: "False" [Use regulator to avoid over-training]
# Default:
RandomSeed: "1" [Random seed for initial synapse weights (0 means unique seed for each run; default value '1')]
EstimatorType: "MSE" [MSE (Mean Square Estimator) for Gaussian Likelihood or CE(Cross-Entropy) for Bernoulli Likelihood]
NeuronInputType: "sum" [Neuron input function type]
VerbosityLevel: "Default" [Verbosity level]
CreateMVAPdfs: "False" [Create PDFs for classifier outputs (signal and background)]
IgnoreNegWeightsInTraining: "False" [Events with negative weights are ignored in the training (but are included for testing and performance evaluation)]
TrainingMethod: "BP" [Train with Back-Propagation (BP), BFGS Algorithm (BFGS), or Genetic Algorithm (GA - slower and worse)]
LearningRate: "2.000000e-02" [ANN learning rate parameter]
DecayRate: "1.000000e-02" [Decay rate for learning parameter]
EpochMonitoring: "False" [Provide epoch-wise monitoring plots according to TestRate (caution: causes big ROOT output file!)]
Sampling: "1.000000e+00" [Only 'Sampling' (randomly selected) events are trained each epoch]
SamplingEpoch: "1.000000e+00" [Sampling is used for the first 'SamplingEpoch' epochs, afterwards, all events are taken for training]
SamplingImportance: "1.000000e+00" [ The sampling weights of events in epochs which successful (worse estimator than before) are multiplied with SamplingImportance, else they are divided.]
SamplingTraining: "True" [The training sample is sampled]
SamplingTesting: "False" [The testing sample is sampled]
ResetStep: "50" [How often BFGS should reset history]
Tau: "3.000000e+00" [LineSearch "size step"]
BPMode: "sequential" [Back-propagation learning mode: sequential or batch]
BatchSize: "-1" [Batch size: number of events/batch, only set if in Batch Mode, -1 for BatchSize=number_of_events]
ConvergenceImprove: "1.000000e-30" [Minimum improvement which counts as improvement (<0 means automatic convergence check is turned off)]
ConvergenceTests: "-1" [Number of steps (without improvement) required for convergence (<0 means automatic convergence check is turned off)]
UpdateLimit: "10000" [Maximum times of regulator update]
CalculateErrors: "False" [Calculates inverse Hessian matrix at the end of the training to be able to calculate the uncertainties of an MVA value]
WeightRange: "1.000000e+00" [Take the events for the estimator calculations from small deviations from the desired value to large deviations only over the weight range]
##


#VAR -*-*-*-*-*-*-*-*-*-*-*-* variables *-*-*-*-*-*-*-*-*-*-*-*-

NVar 6
Jet.Eta                       Jet.Eta                       Jet.Eta                       Jet.Eta                                                         'F'    [-3.99399995804,3.99799990654]
Jet.Phi                       Jet.Phi                       Jet.Phi                       Jet.Phi                                                         'F'    [0,6.28299999237]
Jet.Mass                      Jet.Mass                      Jet.Mass                      Jet.Mass                                                        'F'    [0,251.460006714]
Jet.PT                        Jet.PT                        Jet.PT                        Jet.PT                                                          'F'    [4.73000001907,2147.32006836]
MissingET.Phi                 MissingET.Phi                 MissingET.Phi                 MissingET.Phi                                                   'F'    [0,6.28299999237]
MissingET.MET                 MissingET.MET                 MissingET.MET                 MissingET.MET                                                   'F'    [3.57999992371,1585.47998047]
NSpec 0


============================================================================ */

#include <vector>
#include <cmath>
#include <string>
#include <iostream>

#ifndef IClassifierReader__def
#define IClassifierReader__def

class IClassifierReader {

 public:

   // constructor
   IClassifierReader() : fStatusIsClean( true ) {}
   virtual ~IClassifierReader() {}

   // return classifier response
   virtual double GetMvaValue( const std::vector<double>& inputValues ) const = 0;

   // returns classifier status
   bool IsStatusClean() const { return fStatusIsClean; }

 protected:

   bool fStatusIsClean;
};

#endif

class ReadMLP : public IClassifierReader {

 public:

   // constructor
   ReadMLP( std::vector<std::string>& theInputVars ) 
      : IClassifierReader(),
        fClassName( "ReadMLP" ),
        fNvars( 6 ),
        fIsNormalised( false )
   {      
      // the training input variables
      const char* inputVars[] = { "Jet.Eta", "Jet.Phi", "Jet.Mass", "Jet.PT", "MissingET.Phi", "MissingET.MET" };

      // sanity checks
      if (theInputVars.size() <= 0) {
         std::cout << "Problem in class \"" << fClassName << "\": empty input vector" << std::endl;
         fStatusIsClean = false;
      }

      if (theInputVars.size() != fNvars) {
         std::cout << "Problem in class \"" << fClassName << "\": mismatch in number of input values: "
                   << theInputVars.size() << " != " << fNvars << std::endl;
         fStatusIsClean = false;
      }

      // validate input variables
      for (size_t ivar = 0; ivar < theInputVars.size(); ivar++) {
         if (theInputVars[ivar] != inputVars[ivar]) {
            std::cout << "Problem in class \"" << fClassName << "\": mismatch in input variable names" << std::endl
                      << " for variable [" << ivar << "]: " << theInputVars[ivar].c_str() << " != " << inputVars[ivar] << std::endl;
            fStatusIsClean = false;
         }
      }

      // initialize min and max vectors (for normalisation)
      fVmin[0] = -1;
      fVmax[0] = 0.99999988079071;
      fVmin[1] = -1;
      fVmax[1] = 0.99999988079071;
      fVmin[2] = -1;
      fVmax[2] = 0.99999988079071;
      fVmin[3] = -1;
      fVmax[3] = 1;
      fVmin[4] = -1;
      fVmax[4] = 0.99999988079071;
      fVmin[5] = -1;
      fVmax[5] = 1;

      // initialize input variable types
      fType[0] = 'F';
      fType[1] = 'F';
      fType[2] = 'F';
      fType[3] = 'F';
      fType[4] = 'F';
      fType[5] = 'F';

      // initialize constants
      Initialize();

      // initialize transformation
      InitTransform();
   }

   // destructor
   virtual ~ReadMLP() {
      Clear(); // method-specific
   }

   // the classifier response
   // "inputValues" is a vector of input values in the same order as the 
   // variables given to the constructor
   double GetMvaValue( const std::vector<double>& inputValues ) const;

 private:

   // method-specific destructor
   void Clear();

   // input variable transformation

   double fMin_1[3][6];
   double fMax_1[3][6];
   void InitTransform_1();
   void Transform_1( std::vector<double> & iv, int sigOrBgd ) const;
   void InitTransform();
   void Transform( std::vector<double> & iv, int sigOrBgd ) const;

   // common member variables
   const char* fClassName;

   const size_t fNvars;
   size_t GetNvar()           const { return fNvars; }
   char   GetType( int ivar ) const { return fType[ivar]; }

   // normalisation of input variables
   const bool fIsNormalised;
   bool IsNormalised() const { return fIsNormalised; }
   double fVmin[6];
   double fVmax[6];
   double NormVariable( double x, double xmin, double xmax ) const {
      // normalise to output range: [-1, 1]
      return 2*(x - xmin)/(xmax - xmin) - 1.0;
   }

   // type of input variable: 'F' or 'I'
   char   fType[6];

   // initialize internal variables
   void Initialize();
   double GetMvaValue__( const std::vector<double>& inputValues ) const;

   // private members (method specific)

   double ActivationFnc(double x) const;
   double OutputActivationFnc(double x) const;

   int fLayers;
   int fLayerSize[3];
   double fWeightMatrix0to1[12][7];   // weight matrix from layer 0 to 1
   double fWeightMatrix1to2[1][12];   // weight matrix from layer 1 to 2

   double * fWeights[3];
};

inline void ReadMLP::Initialize()
{
   // build network structure
   fLayers = 3;
   fLayerSize[0] = 7; fWeights[0] = new double[7]; 
   fLayerSize[1] = 12; fWeights[1] = new double[12]; 
   fLayerSize[2] = 1; fWeights[2] = new double[1]; 
   // weight matrix from layer 0 to 1
   fWeightMatrix0to1[0][0] = -0.00356355501002975;
   fWeightMatrix0to1[1][0] = 0.270690526614259;
   fWeightMatrix0to1[2][0] = -0.157066043879704;
   fWeightMatrix0to1[3][0] = 0.139031163899423;
   fWeightMatrix0to1[4][0] = -1.90409281651507;
   fWeightMatrix0to1[5][0] = 0.00378099145384049;
   fWeightMatrix0to1[6][0] = -0.344021807138358;
   fWeightMatrix0to1[7][0] = 1.47796524151977;
   fWeightMatrix0to1[8][0] = -0.253689443010289;
   fWeightMatrix0to1[9][0] = -1.05735929592039;
   fWeightMatrix0to1[10][0] = -0.285900168328297;
   fWeightMatrix0to1[0][1] = 0.0330169504597781;
   fWeightMatrix0to1[1][1] = -0.729957294922475;
   fWeightMatrix0to1[2][1] = 2.54097020571581;
   fWeightMatrix0to1[3][1] = -1.49611665672013;
   fWeightMatrix0to1[4][1] = 0.431427343589958;
   fWeightMatrix0to1[5][1] = -0.0781050227552112;
   fWeightMatrix0to1[6][1] = 0.823450734401349;
   fWeightMatrix0to1[7][1] = 0.575967558242521;
   fWeightMatrix0to1[8][1] = 1.48861667451798;
   fWeightMatrix0to1[9][1] = -0.366825189262519;
   fWeightMatrix0to1[10][1] = 3.77675877901734;
   fWeightMatrix0to1[0][2] = 0.509391899779531;
   fWeightMatrix0to1[1][2] = 1.33218838171995;
   fWeightMatrix0to1[2][2] = 0.202876013179604;
   fWeightMatrix0to1[3][2] = -0.664794305523112;
   fWeightMatrix0to1[4][2] = 1.49132607569851;
   fWeightMatrix0to1[5][2] = 0.564966853441008;
   fWeightMatrix0to1[6][2] = -0.817978111170387;
   fWeightMatrix0to1[7][2] = 1.01026265616659;
   fWeightMatrix0to1[8][2] = 1.98133459892088;
   fWeightMatrix0to1[9][2] = 1.94611165192962;
   fWeightMatrix0to1[10][2] = -0.27068077895395;
   fWeightMatrix0to1[0][3] = -0.967480056309198;
   fWeightMatrix0to1[1][3] = 2.03581018691234;
   fWeightMatrix0to1[2][3] = 0.0516410131801227;
   fWeightMatrix0to1[3][3] = -0.821651311492697;
   fWeightMatrix0to1[4][3] = 1.84032391805198;
   fWeightMatrix0to1[5][3] = 0.422666170778503;
   fWeightMatrix0to1[6][3] = 2.01102004995593;
   fWeightMatrix0to1[7][3] = 2.21535101212625;
   fWeightMatrix0to1[8][3] = 2.97632591516098;
   fWeightMatrix0to1[9][3] = 1.8329895468283;
   fWeightMatrix0to1[10][3] = 0.221196442507763;
   fWeightMatrix0to1[0][4] = -0.0911581342113748;
   fWeightMatrix0to1[1][4] = -0.52130213446215;
   fWeightMatrix0to1[2][4] = -2.66541776752518;
   fWeightMatrix0to1[3][4] = 1.63305654395946;
   fWeightMatrix0to1[4][4] = 0.909775976184689;
   fWeightMatrix0to1[5][4] = 0.0441346825212762;
   fWeightMatrix0to1[6][4] = 1.57642031044803;
   fWeightMatrix0to1[7][4] = 1.02414091862526;
   fWeightMatrix0to1[8][4] = -1.58301061615537;
   fWeightMatrix0to1[9][4] = 0.845502608513701;
   fWeightMatrix0to1[10][4] = -3.89543117783373;
   fWeightMatrix0to1[0][5] = -16.7192310429354;
   fWeightMatrix0to1[1][5] = -1.86789367939489;
   fWeightMatrix0to1[2][5] = -3.63302836269514;
   fWeightMatrix0to1[3][5] = 5.08486774874582;
   fWeightMatrix0to1[4][5] = -0.259886111631964;
   fWeightMatrix0to1[5][5] = -10.3055268805579;
   fWeightMatrix0to1[6][5] = 1.32714981085968;
   fWeightMatrix0to1[7][5] = -0.116279387085427;
   fWeightMatrix0to1[8][5] = -3.42307979183029;
   fWeightMatrix0to1[9][5] = 0.886797245325373;
   fWeightMatrix0to1[10][5] = -1.82441078897223;
   fWeightMatrix0to1[0][6] = -13.7351585008404;
   fWeightMatrix0to1[1][6] = -1.83398491563664;
   fWeightMatrix0to1[2][6] = -2.00009818447074;
   fWeightMatrix0to1[3][6] = 1.23176117725471;
   fWeightMatrix0to1[4][6] = -0.597326147496303;
   fWeightMatrix0to1[5][6] = -8.72141712388792;
   fWeightMatrix0to1[6][6] = -0.700693951116788;
   fWeightMatrix0to1[7][6] = 0.0342021387804436;
   fWeightMatrix0to1[8][6] = 2.0114228689539;
   fWeightMatrix0to1[9][6] = -0.417202386814984;
   fWeightMatrix0to1[10][6] = -2.39197479160151;
   // weight matrix from layer 1 to 2
   fWeightMatrix1to2[0][0] = -3.32974500618783;
   fWeightMatrix1to2[0][1] = -0.852558184600135;
   fWeightMatrix1to2[0][2] = 1.76543742128182;
   fWeightMatrix1to2[0][3] = 1.39492367175205;
   fWeightMatrix1to2[0][4] = -0.446111485737493;
   fWeightMatrix1to2[0][5] = 5.6885668529032;
   fWeightMatrix1to2[0][6] = 0.0543967126977781;
   fWeightMatrix1to2[0][7] = -0.208835267730364;
   fWeightMatrix1to2[0][8] = 0.593285280160843;
   fWeightMatrix1to2[0][9] = 0.32853839359062;
   fWeightMatrix1to2[0][10] = -1.05343183683697;
   fWeightMatrix1to2[0][11] = -0.354667446159005;
}

inline double ReadMLP::GetMvaValue__( const std::vector<double>& inputValues ) const
{
   if (inputValues.size() != (unsigned int)fLayerSize[0]-1) {
      std::cout << "Input vector needs to be of size " << fLayerSize[0]-1 << std::endl;
      return 0;
   }

   for (int l=0; l<fLayers; l++)
      for (int i=0; i<fLayerSize[l]; i++) fWeights[l][i]=0;

   for (int l=0; l<fLayers-1; l++)
      fWeights[l][fLayerSize[l]-1]=1;

   for (int i=0; i<fLayerSize[0]-1; i++)
      fWeights[0][i]=inputValues[i];

   // layer 0 to 1
   for (int o=0; o<fLayerSize[1]-1; o++) {
      for (int i=0; i<fLayerSize[0]; i++) {
         double inputVal = fWeightMatrix0to1[o][i] * fWeights[0][i];
         fWeights[1][o] += inputVal;
      }
      fWeights[1][o] = ActivationFnc(fWeights[1][o]);
   }
   // layer 1 to 2
   for (int o=0; o<fLayerSize[2]; o++) {
      for (int i=0; i<fLayerSize[1]; i++) {
         double inputVal = fWeightMatrix1to2[o][i] * fWeights[1][i];
         fWeights[2][o] += inputVal;
      }
      fWeights[2][o] = OutputActivationFnc(fWeights[2][o]);
   }

   return fWeights[2][0];
}

double ReadMLP::ActivationFnc(double x) const {
   // sigmoid
   return 1.0/(1.0+exp(-x));
}
double ReadMLP::OutputActivationFnc(double x) const {
   // identity
   return x;
}
   
// Clean up
inline void ReadMLP::Clear() 
{
   // clean up the arrays
   for (int lIdx = 0; lIdx < 3; lIdx++) {
      delete[] fWeights[lIdx];
   }
}
   inline double ReadMLP::GetMvaValue( const std::vector<double>& inputValues ) const
   {
      // classifier response value
      double retval = 0;

      // classifier response, sanity check first
      if (!IsStatusClean()) {
         std::cout << "Problem in class \"" << fClassName << "\": cannot return classifier response"
                   << " because status is dirty" << std::endl;
         retval = 0;
      }
      else {
         if (IsNormalised()) {
            // normalise variables
            std::vector<double> iV;
            iV.reserve(inputValues.size());
            int ivar = 0;
            for (std::vector<double>::const_iterator varIt = inputValues.begin();
                 varIt != inputValues.end(); varIt++, ivar++) {
               iV.push_back(NormVariable( *varIt, fVmin[ivar], fVmax[ivar] ));
            }
            Transform( iV, -1 );
            retval = GetMvaValue__( iV );
         }
         else {
            std::vector<double> iV;
            int ivar = 0;
            for (std::vector<double>::const_iterator varIt = inputValues.begin();
                 varIt != inputValues.end(); varIt++, ivar++) {
               iV.push_back(*varIt);
            }
            Transform( iV, -1 );
            retval = GetMvaValue__( iV );
         }
      }

      return retval;
   }

//_______________________________________________________________________
inline void ReadMLP::InitTransform_1()
{
   // Normalization transformation, initialisation
   fMin_1[0][0] = -3.98099994659;
   fMax_1[0][0] = 3.99799990654;
   fMin_1[1][0] = -3.99399995804;
   fMax_1[1][0] = 3.99699997902;
   fMin_1[2][0] = -3.99399995804;
   fMax_1[2][0] = 3.99799990654;
   fMin_1[0][1] = 0;
   fMax_1[0][1] = 6.28299999237;
   fMin_1[1][1] = 0;
   fMax_1[1][1] = 6.28299999237;
   fMin_1[2][1] = 0;
   fMax_1[2][1] = 6.28299999237;
   fMin_1[0][2] = 0;
   fMax_1[0][2] = 251.460006714;
   fMin_1[1][2] = 0;
   fMax_1[1][2] = 184.169998169;
   fMin_1[2][2] = 0;
   fMax_1[2][2] = 251.460006714;
   fMin_1[0][3] = 5;
   fMax_1[0][3] = 2147.32006836;
   fMin_1[1][3] = 4.73000001907;
   fMax_1[1][3] = 817.520019531;
   fMin_1[2][3] = 4.73000001907;
   fMax_1[2][3] = 2147.32006836;
   fMin_1[0][4] = 0;
   fMax_1[0][4] = 6.28299999237;
   fMin_1[1][4] = 0.0010000000475;
   fMax_1[1][4] = 6.28200006485;
   fMin_1[2][4] = 0;
   fMax_1[2][4] = 6.28299999237;
   fMin_1[0][5] = 3.57999992371;
   fMax_1[0][5] = 1585.47998047;
   fMin_1[1][5] = 100.010002136;
   fMax_1[1][5] = 662.650024414;
   fMin_1[2][5] = 3.57999992371;
   fMax_1[2][5] = 1585.47998047;
}

//_______________________________________________________________________
inline void ReadMLP::Transform_1( std::vector<double>& iv, int cls) const
{
   // Normalization transformation
   if (cls < 0 || cls > 2) {
   if (2 > 1 ) cls = 2;
      else cls = 2;
   }
   const int nVar = 6;

   // get indices of used variables

   // define the indices of the variables which are transformed by this transformation
   static std::vector<int> indicesGet;
   static std::vector<int> indicesPut;

   if ( indicesGet.empty() ) { 
      indicesGet.reserve(fNvars);
      indicesGet.push_back( 0);
      indicesGet.push_back( 1);
      indicesGet.push_back( 2);
      indicesGet.push_back( 3);
      indicesGet.push_back( 4);
      indicesGet.push_back( 5);
   } 
   if ( indicesPut.empty() ) { 
      indicesPut.reserve(fNvars);
      indicesPut.push_back( 0);
      indicesPut.push_back( 1);
      indicesPut.push_back( 2);
      indicesPut.push_back( 3);
      indicesPut.push_back( 4);
      indicesPut.push_back( 5);
   } 

   static std::vector<double> dv;
   dv.resize(nVar);
   for (int ivar=0; ivar<nVar; ivar++) dv[ivar] = iv[indicesGet.at(ivar)];
   for (int ivar=0;ivar<6;ivar++) {
      double offset = fMin_1[cls][ivar];
      double scale  = 1.0/(fMax_1[cls][ivar]-fMin_1[cls][ivar]);
      iv[indicesPut.at(ivar)] = (dv[ivar]-offset)*scale * 2 - 1;
   }
}

//_______________________________________________________________________
inline void ReadMLP::InitTransform()
{
   InitTransform_1();
}

//_______________________________________________________________________
inline void ReadMLP::Transform( std::vector<double>& iv, int sigOrBgd ) const
{
   Transform_1( iv, sigOrBgd );
}
