// Class: ReadMLP3-BP
// Automatically generated by MethodBase::MakeClass
//

/* configuration options =====================================================

#GEN -*-*-*-*-*-*-*-*-*-*-*- general info -*-*-*-*-*-*-*-*-*-*-*-

Method         : MLP::MLP3-BP
TMVA Release   : 4.2.0         [262656]
ROOT Release   : 5.34/18       [336402]
Creator        : zxb0111
Date           : Tue Dec  2 17:07:15 2014
Host           : Linux localhost.localdomain 2.6.32-431.17.1.el6.x86_64 #1 SMP Wed May 7 14:14:17 CDT 2014 x86_64 x86_64 x86_64 GNU/Linux
Dir            : /home/zxb0111/seminar
Training events: 35264
Analysis type  : [Classification]


#OPT -*-*-*-*-*-*-*-*-*-*-*-*- options -*-*-*-*-*-*-*-*-*-*-*-*-

# Set by User:
NCycles: "600" [Number of training cycles]
HiddenLayers: "N,N,N" [Specification of hidden layer architecture]
NeuronType: "sigmoid" [Neuron activation function type]
VarTransform: "N" [List of variable transformations performed before training, e.g., "D_Background,P_Signal,G,N_AllClasses" for: "Decorrelation, PCA-transformation, Gaussianisation, Normalisation, each for the given class of events ('AllClasses' denotes all events of all classes, if no class indication is given, 'All' is assumed)"]
TrainingMethod: "BP" [Train with Back-Propagation (BP), BFGS Algorithm (BFGS), or Genetic Algorithm (GA - slower and worse)]
TestRate: "5" [Test for overtraining performed at each #th epochs]
UseRegulator: "False" [Use regulator to avoid over-training]
# Default:
RandomSeed: "1" [Random seed for initial synapse weights (0 means unique seed for each run; default value '1')]
EstimatorType: "MSE" [MSE (Mean Square Estimator) for Gaussian Likelihood or CE(Cross-Entropy) for Bernoulli Likelihood]
NeuronInputType: "sum" [Neuron input function type]
V: "False" [Verbose output (short form of "VerbosityLevel" below - overrides the latter one)]
VerbosityLevel: "Default" [Verbosity level]
H: "False" [Print method-specific help message]
CreateMVAPdfs: "False" [Create PDFs for classifier outputs (signal and background)]
IgnoreNegWeightsInTraining: "False" [Events with negative weights are ignored in the training (but are included for testing and performance evaluation)]
LearningRate: "2.000000e-02" [ANN learning rate parameter]
DecayRate: "1.000000e-02" [Decay rate for learning parameter]
EpochMonitoring: "False" [Provide epoch-wise monitoring plots according to TestRate (caution: causes big ROOT output file!)]
Sampling: "1.000000e+00" [Only 'Sampling' (randomly selected) events are trained each epoch]
SamplingEpoch: "1.000000e+00" [Sampling is used for the first 'SamplingEpoch' epochs, afterwards, all events are taken for training]
SamplingImportance: "1.000000e+00" [ The sampling weights of events in epochs which successful (worse estimator than before) are multiplied with SamplingImportance, else they are divided.]
SamplingTraining: "True" [The training sample is sampled]
SamplingTesting: "False" [The testing sample is sampled]
ResetStep: "50" [How often BFGS should reset history]
Tau: "3.000000e+00" [LineSearch "size step"]
BPMode: "sequential" [Back-propagation learning mode: sequential or batch]
BatchSize: "-1" [Batch size: number of events/batch, only set if in Batch Mode, -1 for BatchSize=number_of_events]
ConvergenceImprove: "1.000000e-30" [Minimum improvement which counts as improvement (<0 means automatic convergence check is turned off)]
ConvergenceTests: "-1" [Number of steps (without improvement) required for convergence (<0 means automatic convergence check is turned off)]
UpdateLimit: "10000" [Maximum times of regulator update]
CalculateErrors: "False" [Calculates inverse Hessian matrix at the end of the training to be able to calculate the uncertainties of an MVA value]
WeightRange: "1.000000e+00" [Take the events for the estimator calculations from small deviations from the desired value to large deviations only over the weight range]
##


#VAR -*-*-*-*-*-*-*-*-*-*-*-* variables *-*-*-*-*-*-*-*-*-*-*-*-

NVar 8
Jet.PT                        Jet.PT                        Jet.PT                        Jet.PT                                                          'F'    [4.73000001907,2147.32006836]
Jet.Eta                       Jet.Eta                       Jet.Eta                       Jet.Eta                                                         'F'    [-3.99399995804,3.99799990654]
Jet.Phi                       Jet.Phi                       Jet.Phi                       Jet.Phi                                                         'F'    [0,6.28299999237]
Jet.Mass                      Jet.Mass                      Jet.Mass                      Jet.Mass                                                        'F'    [0,251.460006714]
Jet.Ntrk                      Jet.Ntrk                      Jet.Ntrk                      Jet.Ntrk                                                        'F'    [0,77]
Jet.EhadOverEem               Jet.EhadOverEem               Jet.EhadOverEem               Jet.EhadOverEem                                                 'F'    [0,999]
MissingET.Phi                 MissingET.Phi                 MissingET.Phi                 MissingET.Phi                                                   'F'    [0,6.28299999237]
MissingET.MET                 MissingET.MET                 MissingET.MET                 MissingET.MET                                                   'F'    [3.57999992371,1585.47998047]
NSpec 0


============================================================================ */

#include <vector>
#include <cmath>
#include <string>
#include <iostream>

#ifndef IClassifierReader__def
#define IClassifierReader__def

class IClassifierReader {

 public:

   // constructor
   IClassifierReader() : fStatusIsClean( true ) {}
   virtual ~IClassifierReader() {}

   // return classifier response
   virtual double GetMvaValue( const std::vector<double>& inputValues ) const = 0;

   // returns classifier status
   bool IsStatusClean() const { return fStatusIsClean; }

 protected:

   bool fStatusIsClean;
};

#endif

class ReadMLP3-BP : public IClassifierReader {

 public:

   // constructor
   ReadMLP3-BP( std::vector<std::string>& theInputVars ) 
      : IClassifierReader(),
        fClassName( "ReadMLP3-BP" ),
        fNvars( 8 ),
        fIsNormalised( false )
   {      
      // the training input variables
      const char* inputVars[] = { "Jet.PT", "Jet.Eta", "Jet.Phi", "Jet.Mass", "Jet.Ntrk", "Jet.EhadOverEem", "MissingET.Phi", "MissingET.MET" };

      // sanity checks
      if (theInputVars.size() <= 0) {
         std::cout << "Problem in class \"" << fClassName << "\": empty input vector" << std::endl;
         fStatusIsClean = false;
      }

      if (theInputVars.size() != fNvars) {
         std::cout << "Problem in class \"" << fClassName << "\": mismatch in number of input values: "
                   << theInputVars.size() << " != " << fNvars << std::endl;
         fStatusIsClean = false;
      }

      // validate input variables
      for (size_t ivar = 0; ivar < theInputVars.size(); ivar++) {
         if (theInputVars[ivar] != inputVars[ivar]) {
            std::cout << "Problem in class \"" << fClassName << "\": mismatch in input variable names" << std::endl
                      << " for variable [" << ivar << "]: " << theInputVars[ivar].c_str() << " != " << inputVars[ivar] << std::endl;
            fStatusIsClean = false;
         }
      }

      // initialize min and max vectors (for normalisation)
      fVmin[0] = -1;
      fVmax[0] = 1;
      fVmin[1] = -1;
      fVmax[1] = 0.99999988079071;
      fVmin[2] = -1;
      fVmax[2] = 0.99999988079071;
      fVmin[3] = -1;
      fVmax[3] = 0.99999988079071;
      fVmin[4] = -1;
      fVmax[4] = 1;
      fVmin[5] = -1;
      fVmax[5] = 1;
      fVmin[6] = -1;
      fVmax[6] = 0.99999988079071;
      fVmin[7] = -1;
      fVmax[7] = 1;

      // initialize input variable types
      fType[0] = 'F';
      fType[1] = 'F';
      fType[2] = 'F';
      fType[3] = 'F';
      fType[4] = 'F';
      fType[5] = 'F';
      fType[6] = 'F';
      fType[7] = 'F';

      // initialize constants
      Initialize();

      // initialize transformation
      InitTransform();
   }

   // destructor
   virtual ~ReadMLP3-BP() {
      Clear(); // method-specific
   }

   // the classifier response
   // "inputValues" is a vector of input values in the same order as the 
   // variables given to the constructor
   double GetMvaValue( const std::vector<double>& inputValues ) const;

 private:

   // method-specific destructor
   void Clear();

   // input variable transformation

   double fMin_1[3][8];
   double fMax_1[3][8];
   void InitTransform_1();
   void Transform_1( std::vector<double> & iv, int sigOrBgd ) const;
   void InitTransform();
   void Transform( std::vector<double> & iv, int sigOrBgd ) const;

   // common member variables
   const char* fClassName;

   const size_t fNvars;
   size_t GetNvar()           const { return fNvars; }
   char   GetType( int ivar ) const { return fType[ivar]; }

   // normalisation of input variables
   const bool fIsNormalised;
   bool IsNormalised() const { return fIsNormalised; }
   double fVmin[8];
   double fVmax[8];
   double NormVariable( double x, double xmin, double xmax ) const {
      // normalise to output range: [-1, 1]
      return 2*(x - xmin)/(xmax - xmin) - 1.0;
   }

   // type of input variable: 'F' or 'I'
   char   fType[8];

   // initialize internal variables
   void Initialize();
   double GetMvaValue__( const std::vector<double>& inputValues ) const;

   // private members (method specific)

   double ActivationFnc(double x) const;
   double OutputActivationFnc(double x) const;

   int fLayers;
   int fLayerSize[5];
   double fWeightMatrix0to1[9][9];   // weight matrix from layer 0 to 1
   double fWeightMatrix1to2[9][9];   // weight matrix from layer 1 to 2
   double fWeightMatrix2to3[9][9];   // weight matrix from layer 2 to 3
   double fWeightMatrix3to4[1][9];   // weight matrix from layer 3 to 4

   double * fWeights[5];
};

inline void ReadMLP3-BP::Initialize()
{
   // build network structure
   fLayers = 5;
   fLayerSize[0] = 9; fWeights[0] = new double[9]; 
   fLayerSize[1] = 9; fWeights[1] = new double[9]; 
   fLayerSize[2] = 9; fWeights[2] = new double[9]; 
   fLayerSize[3] = 9; fWeights[3] = new double[9]; 
   fLayerSize[4] = 1; fWeights[4] = new double[1]; 
   // weight matrix from layer 0 to 1
   fWeightMatrix0to1[0][0] = -2.73839240404995;
   fWeightMatrix0to1[1][0] = 3.42715915200417;
   fWeightMatrix0to1[2][0] = 0.793440919721347;
   fWeightMatrix0to1[3][0] = 2.76436219030389;
   fWeightMatrix0to1[4][0] = -1.96961142827317;
   fWeightMatrix0to1[5][0] = -3.86310461790833;
   fWeightMatrix0to1[6][0] = -1.53766839731291;
   fWeightMatrix0to1[7][0] = 1.3894609118091;
   fWeightMatrix0to1[0][1] = 0.015319361413066;
   fWeightMatrix0to1[1][1] = -0.0111988120439453;
   fWeightMatrix0to1[2][1] = 0.0178295719671993;
   fWeightMatrix0to1[3][1] = -0.0306895738360544;
   fWeightMatrix0to1[4][1] = -1.35720361180439;
   fWeightMatrix0to1[5][1] = -0.0173850871593495;
   fWeightMatrix0to1[6][1] = -0.124298778905002;
   fWeightMatrix0to1[7][1] = -0.0262359492905397;
   fWeightMatrix0to1[0][2] = 0.127609031112071;
   fWeightMatrix0to1[1][2] = 0.114959004291849;
   fWeightMatrix0to1[2][2] = -0.629012583644318;
   fWeightMatrix0to1[3][2] = 1.52287932623051;
   fWeightMatrix0to1[4][2] = -0.374435039392491;
   fWeightMatrix0to1[5][2] = -0.750716570783241;
   fWeightMatrix0to1[6][2] = 5.70445516262202;
   fWeightMatrix0to1[7][2] = 2.47983008913029;
   fWeightMatrix0to1[0][3] = -0.889205391392191;
   fWeightMatrix0to1[1][3] = 0.0550849638208889;
   fWeightMatrix0to1[2][3] = 0.0423382793751772;
   fWeightMatrix0to1[3][3] = -1.22084562767605;
   fWeightMatrix0to1[4][3] = -1.90188547139997;
   fWeightMatrix0to1[5][3] = -0.838914947960988;
   fWeightMatrix0to1[6][3] = 0.909843134029386;
   fWeightMatrix0to1[7][3] = 0.292657976779983;
   fWeightMatrix0to1[0][4] = -0.130082143539554;
   fWeightMatrix0to1[1][4] = 0.56435757357108;
   fWeightMatrix0to1[2][4] = 0.491212877439678;
   fWeightMatrix0to1[3][4] = 0.721363570296356;
   fWeightMatrix0to1[4][4] = -1.48021076778887;
   fWeightMatrix0to1[5][4] = 0.0502151692775435;
   fWeightMatrix0to1[6][4] = -0.345157721915248;
   fWeightMatrix0to1[7][4] = 0.586010036478289;
   fWeightMatrix0to1[0][5] = 4.77718213790171;
   fWeightMatrix0to1[1][5] = -0.419580581353341;
   fWeightMatrix0to1[2][5] = 1.62587721794365;
   fWeightMatrix0to1[3][5] = -0.157503456827754;
   fWeightMatrix0to1[4][5] = -0.755233293875928;
   fWeightMatrix0to1[5][5] = -0.0645813671009964;
   fWeightMatrix0to1[6][5] = 2.0352609574826;
   fWeightMatrix0to1[7][5] = -0.0707186995318077;
   fWeightMatrix0to1[0][6] = 0.0482542036971621;
   fWeightMatrix0to1[1][6] = -0.213991210521952;
   fWeightMatrix0to1[2][6] = 0.700366015518734;
   fWeightMatrix0to1[3][6] = -1.58640863285394;
   fWeightMatrix0to1[4][6] = -1.59353078645063;
   fWeightMatrix0to1[5][6] = 0.713939671003157;
   fWeightMatrix0to1[6][6] = -5.74065336230631;
   fWeightMatrix0to1[7][6] = -2.39597670451134;
   fWeightMatrix0to1[0][7] = -5.84758755827984;
   fWeightMatrix0to1[1][7] = -9.96728494188634;
   fWeightMatrix0to1[2][7] = 3.04078063926549;
   fWeightMatrix0to1[3][7] = 2.97598263102872;
   fWeightMatrix0to1[4][7] = -1.63503659472808;
   fWeightMatrix0to1[5][7] = 3.51217518868861;
   fWeightMatrix0to1[6][7] = 0.0862806629807008;
   fWeightMatrix0to1[7][7] = 0.147815656122895;
   fWeightMatrix0to1[0][8] = -3.80083665100596;
   fWeightMatrix0to1[1][8] = -5.05998264048913;
   fWeightMatrix0to1[2][8] = 4.07329779038695;
   fWeightMatrix0to1[3][8] = 3.9351273106377;
   fWeightMatrix0to1[4][8] = 0.801492843664287;
   fWeightMatrix0to1[5][8] = -0.924600430826009;
   fWeightMatrix0to1[6][8] = -2.31676728391362;
   fWeightMatrix0to1[7][8] = -1.24087693175973;
   // weight matrix from layer 1 to 2
   fWeightMatrix1to2[0][0] = 1.11283193718571;
   fWeightMatrix1to2[1][0] = 2.69034745759213;
   fWeightMatrix1to2[2][0] = 4.48052161797987;
   fWeightMatrix1to2[3][0] = -0.94288941475109;
   fWeightMatrix1to2[4][0] = -4.23903612799884;
   fWeightMatrix1to2[5][0] = -1.28323855453896;
   fWeightMatrix1to2[6][0] = 0.382006836002484;
   fWeightMatrix1to2[7][0] = -0.72623160281716;
   fWeightMatrix1to2[0][1] = 2.41597420280981;
   fWeightMatrix1to2[1][1] = 1.03473002423725;
   fWeightMatrix1to2[2][1] = 3.73614723547961;
   fWeightMatrix1to2[3][1] = -7.14613991942401;
   fWeightMatrix1to2[4][1] = -4.23018415124347;
   fWeightMatrix1to2[5][1] = 3.03031044450835;
   fWeightMatrix1to2[6][1] = 0.487566474375967;
   fWeightMatrix1to2[7][1] = -2.75793433589992;
   fWeightMatrix1to2[0][2] = -2.79167501043508;
   fWeightMatrix1to2[1][2] = -2.2487881269419;
   fWeightMatrix1to2[2][2] = -1.9769432937105;
   fWeightMatrix1to2[3][2] = 0.191516799787003;
   fWeightMatrix1to2[4][2] = 2.99098684430405;
   fWeightMatrix1to2[5][2] = -2.42064970556879;
   fWeightMatrix1to2[6][2] = -0.91298687867471;
   fWeightMatrix1to2[7][2] = 2.83944691334716;
   fWeightMatrix1to2[0][3] = -2.0065367053156;
   fWeightMatrix1to2[1][3] = -2.46467745233984;
   fWeightMatrix1to2[2][3] = -3.41547563977576;
   fWeightMatrix1to2[3][3] = -1.06729229367085;
   fWeightMatrix1to2[4][3] = 0.805475298732679;
   fWeightMatrix1to2[5][3] = -2.43916147850264;
   fWeightMatrix1to2[6][3] = 0.745187537783278;
   fWeightMatrix1to2[7][3] = 2.29899595695226;
   fWeightMatrix1to2[0][4] = -2.2386341912673;
   fWeightMatrix1to2[1][4] = 0.848804385278433;
   fWeightMatrix1to2[2][4] = -1.93035858859178;
   fWeightMatrix1to2[3][4] = -0.586461927950629;
   fWeightMatrix1to2[4][4] = 1.09844388595208;
   fWeightMatrix1to2[5][4] = 0.785395965339207;
   fWeightMatrix1to2[6][4] = -2.29041571962388;
   fWeightMatrix1to2[7][4] = 0.666168183330875;
   fWeightMatrix1to2[0][5] = 0.183954823283946;
   fWeightMatrix1to2[1][5] = 1.80398546400947;
   fWeightMatrix1to2[2][5] = -1.23179183369039;
   fWeightMatrix1to2[3][5] = 5.04284563762682;
   fWeightMatrix1to2[4][5] = 0.952095456481411;
   fWeightMatrix1to2[5][5] = -1.44685185415711;
   fWeightMatrix1to2[6][5] = 0.415052217905598;
   fWeightMatrix1to2[7][5] = -1.52025477932594;
   fWeightMatrix1to2[0][6] = -1.83356043601144;
   fWeightMatrix1to2[1][6] = 1.09535436520623;
   fWeightMatrix1to2[2][6] = 0.791745315682564;
   fWeightMatrix1to2[3][6] = 4.86678485847775;
   fWeightMatrix1to2[4][6] = -0.578394256718815;
   fWeightMatrix1to2[5][6] = 1.36701506178399;
   fWeightMatrix1to2[6][6] = -0.582781752895068;
   fWeightMatrix1to2[7][6] = -1.68050310209304;
   fWeightMatrix1to2[0][7] = -1.9361937151146;
   fWeightMatrix1to2[1][7] = 1.13690176878542;
   fWeightMatrix1to2[2][7] = 0.201385489140876;
   fWeightMatrix1to2[3][7] = -3.19133357465047;
   fWeightMatrix1to2[4][7] = 0.69587201857351;
   fWeightMatrix1to2[5][7] = -1.73041819345829;
   fWeightMatrix1to2[6][7] = 0.0757507443337076;
   fWeightMatrix1to2[7][7] = 1.34520181549796;
   fWeightMatrix1to2[0][8] = 0.671209614257703;
   fWeightMatrix1to2[1][8] = -2.73343309132663;
   fWeightMatrix1to2[2][8] = -0.698219174140098;
   fWeightMatrix1to2[3][8] = 1.75701321136032;
   fWeightMatrix1to2[4][8] = 2.80720482545496;
   fWeightMatrix1to2[5][8] = 0.59663265068011;
   fWeightMatrix1to2[6][8] = -1.95410289675473;
   fWeightMatrix1to2[7][8] = 0.252742221291332;
   // weight matrix from layer 2 to 3
   fWeightMatrix2to3[0][0] = -2.6519625009891;
   fWeightMatrix2to3[1][0] = 1.01419880404939;
   fWeightMatrix2to3[2][0] = 0.286227846339381;
   fWeightMatrix2to3[3][0] = 0.887337503154673;
   fWeightMatrix2to3[4][0] = -0.509576352847225;
   fWeightMatrix2to3[5][0] = -0.559223446600413;
   fWeightMatrix2to3[6][0] = -2.97018519548573;
   fWeightMatrix2to3[7][0] = 0.721466277244796;
   fWeightMatrix2to3[0][1] = 2.83916650696072;
   fWeightMatrix2to3[1][1] = -1.01583565243076;
   fWeightMatrix2to3[2][1] = -0.425549906772398;
   fWeightMatrix2to3[3][1] = 1.70247628555779;
   fWeightMatrix2to3[4][1] = 1.45572694400987;
   fWeightMatrix2to3[5][1] = -0.141069409786029;
   fWeightMatrix2to3[6][1] = -2.38967471796547;
   fWeightMatrix2to3[7][1] = -1.22311990874325;
   fWeightMatrix2to3[0][2] = -0.158615294386095;
   fWeightMatrix2to3[1][2] = 0.629530393030443;
   fWeightMatrix2to3[2][2] = -0.636226322060922;
   fWeightMatrix2to3[3][2] = 3.52061161590604;
   fWeightMatrix2to3[4][2] = 1.79583319005098;
   fWeightMatrix2to3[5][2] = -1.09590728686047;
   fWeightMatrix2to3[6][2] = -4.81417100516778;
   fWeightMatrix2to3[7][2] = 1.14976436994835;
   fWeightMatrix2to3[0][3] = -0.238493357169678;
   fWeightMatrix2to3[1][3] = -1.01731967227254;
   fWeightMatrix2to3[2][3] = 0.724116926818016;
   fWeightMatrix2to3[3][3] = 4.44758017918927;
   fWeightMatrix2to3[4][3] = -0.32744397309708;
   fWeightMatrix2to3[5][3] = 0.332435442637927;
   fWeightMatrix2to3[6][3] = 4.67973355975956;
   fWeightMatrix2to3[7][3] = -2.75743425220082;
   fWeightMatrix2to3[0][4] = 0.549132588325685;
   fWeightMatrix2to3[1][4] = -0.906949664831848;
   fWeightMatrix2to3[2][4] = -0.0482905506826959;
   fWeightMatrix2to3[3][4] = -3.19416114272234;
   fWeightMatrix2to3[4][4] = -1.9654992361274;
   fWeightMatrix2to3[5][4] = 0.483897889564021;
   fWeightMatrix2to3[6][4] = 5.18613841443008;
   fWeightMatrix2to3[7][4] = -2.42913748069566;
   fWeightMatrix2to3[0][5] = -1.47035135145181;
   fWeightMatrix2to3[1][5] = -1.10086577350898;
   fWeightMatrix2to3[2][5] = -0.39529172961993;
   fWeightMatrix2to3[3][5] = 3.0372171415362;
   fWeightMatrix2to3[4][5] = -0.26897635945712;
   fWeightMatrix2to3[5][5] = -0.920525891137636;
   fWeightMatrix2to3[6][5] = -2.86902620769197;
   fWeightMatrix2to3[7][5] = 1.16745963244168;
   fWeightMatrix2to3[0][6] = 1.54316537980541;
   fWeightMatrix2to3[1][6] = 1.02514458779786;
   fWeightMatrix2to3[2][6] = 0.208874374088588;
   fWeightMatrix2to3[3][6] = -0.497010535372565;
   fWeightMatrix2to3[4][6] = -1.841370505855;
   fWeightMatrix2to3[5][6] = 1.04761315686302;
   fWeightMatrix2to3[6][6] = 0.432447444660639;
   fWeightMatrix2to3[7][6] = -1.47818260136998;
   fWeightMatrix2to3[0][7] = -2.41632132725783;
   fWeightMatrix2to3[1][7] = -0.458782957379023;
   fWeightMatrix2to3[2][7] = -0.94356425962978;
   fWeightMatrix2to3[3][7] = -3.90541439759877;
   fWeightMatrix2to3[4][7] = 1.37387037751919;
   fWeightMatrix2to3[5][7] = 0.368555286087891;
   fWeightMatrix2to3[6][7] = 2.06375421732557;
   fWeightMatrix2to3[7][7] = -1.08168725249675;
   fWeightMatrix2to3[0][8] = 0.236635150950079;
   fWeightMatrix2to3[1][8] = -0.308933936525587;
   fWeightMatrix2to3[2][8] = -0.798787493926097;
   fWeightMatrix2to3[3][8] = -0.352361846558336;
   fWeightMatrix2to3[4][8] = -1.8907482031706;
   fWeightMatrix2to3[5][8] = -2.20482468155519;
   fWeightMatrix2to3[6][8] = 0.84069948119505;
   fWeightMatrix2to3[7][8] = 0.839755038464834;
   // weight matrix from layer 3 to 4
   fWeightMatrix3to4[0][0] = 1.37330797731452;
   fWeightMatrix3to4[0][1] = -0.357133905452706;
   fWeightMatrix3to4[0][2] = 0.557426783980027;
   fWeightMatrix3to4[0][3] = -1.57602965140594;
   fWeightMatrix3to4[0][4] = -1.56128489761788;
   fWeightMatrix3to4[0][5] = -0.255115210306354;
   fWeightMatrix3to4[0][6] = -1.6311271635351;
   fWeightMatrix3to4[0][7] = 0.135412197057106;
   fWeightMatrix3to4[0][8] = 2.5443804225116;
}

inline double ReadMLP3-BP::GetMvaValue__( const std::vector<double>& inputValues ) const
{
   if (inputValues.size() != (unsigned int)fLayerSize[0]-1) {
      std::cout << "Input vector needs to be of size " << fLayerSize[0]-1 << std::endl;
      return 0;
   }

   for (int l=0; l<fLayers; l++)
      for (int i=0; i<fLayerSize[l]; i++) fWeights[l][i]=0;

   for (int l=0; l<fLayers-1; l++)
      fWeights[l][fLayerSize[l]-1]=1;

   for (int i=0; i<fLayerSize[0]-1; i++)
      fWeights[0][i]=inputValues[i];

   // layer 0 to 1
   for (int o=0; o<fLayerSize[1]-1; o++) {
      for (int i=0; i<fLayerSize[0]; i++) {
         double inputVal = fWeightMatrix0to1[o][i] * fWeights[0][i];
         fWeights[1][o] += inputVal;
      }
      fWeights[1][o] = ActivationFnc(fWeights[1][o]);
   }
   // layer 1 to 2
   for (int o=0; o<fLayerSize[2]-1; o++) {
      for (int i=0; i<fLayerSize[1]; i++) {
         double inputVal = fWeightMatrix1to2[o][i] * fWeights[1][i];
         fWeights[2][o] += inputVal;
      }
      fWeights[2][o] = ActivationFnc(fWeights[2][o]);
   }
   // layer 2 to 3
   for (int o=0; o<fLayerSize[3]-1; o++) {
      for (int i=0; i<fLayerSize[2]; i++) {
         double inputVal = fWeightMatrix2to3[o][i] * fWeights[2][i];
         fWeights[3][o] += inputVal;
      }
      fWeights[3][o] = ActivationFnc(fWeights[3][o]);
   }
   // layer 3 to 4
   for (int o=0; o<fLayerSize[4]; o++) {
      for (int i=0; i<fLayerSize[3]; i++) {
         double inputVal = fWeightMatrix3to4[o][i] * fWeights[3][i];
         fWeights[4][o] += inputVal;
      }
      fWeights[4][o] = OutputActivationFnc(fWeights[4][o]);
   }

   return fWeights[4][0];
}

double ReadMLP3-BP::ActivationFnc(double x) const {
   // sigmoid
   return 1.0/(1.0+exp(-x));
}
double ReadMLP3-BP::OutputActivationFnc(double x) const {
   // identity
   return x;
}
   
// Clean up
inline void ReadMLP3-BP::Clear() 
{
   // clean up the arrays
   for (int lIdx = 0; lIdx < 5; lIdx++) {
      delete[] fWeights[lIdx];
   }
}
   inline double ReadMLP3-BP::GetMvaValue( const std::vector<double>& inputValues ) const
   {
      // classifier response value
      double retval = 0;

      // classifier response, sanity check first
      if (!IsStatusClean()) {
         std::cout << "Problem in class \"" << fClassName << "\": cannot return classifier response"
                   << " because status is dirty" << std::endl;
         retval = 0;
      }
      else {
         if (IsNormalised()) {
            // normalise variables
            std::vector<double> iV;
            iV.reserve(inputValues.size());
            int ivar = 0;
            for (std::vector<double>::const_iterator varIt = inputValues.begin();
                 varIt != inputValues.end(); varIt++, ivar++) {
               iV.push_back(NormVariable( *varIt, fVmin[ivar], fVmax[ivar] ));
            }
            Transform( iV, -1 );
            retval = GetMvaValue__( iV );
         }
         else {
            std::vector<double> iV;
            int ivar = 0;
            for (std::vector<double>::const_iterator varIt = inputValues.begin();
                 varIt != inputValues.end(); varIt++, ivar++) {
               iV.push_back(*varIt);
            }
            Transform( iV, -1 );
            retval = GetMvaValue__( iV );
         }
      }

      return retval;
   }

//_______________________________________________________________________
inline void ReadMLP3-BP::InitTransform_1()
{
   // Normalization transformation, initialisation
   fMin_1[0][0] = 5;
   fMax_1[0][0] = 2147.32006836;
   fMin_1[1][0] = 4.73000001907;
   fMax_1[1][0] = 817.520019531;
   fMin_1[2][0] = 4.73000001907;
   fMax_1[2][0] = 2147.32006836;
   fMin_1[0][1] = -3.98099994659;
   fMax_1[0][1] = 3.99799990654;
   fMin_1[1][1] = -3.99399995804;
   fMax_1[1][1] = 3.99699997902;
   fMin_1[2][1] = -3.99399995804;
   fMax_1[2][1] = 3.99799990654;
   fMin_1[0][2] = 0;
   fMax_1[0][2] = 6.28299999237;
   fMin_1[1][2] = 0;
   fMax_1[1][2] = 6.28299999237;
   fMin_1[2][2] = 0;
   fMax_1[2][2] = 6.28299999237;
   fMin_1[0][3] = 0;
   fMax_1[0][3] = 251.460006714;
   fMin_1[1][3] = 0;
   fMax_1[1][3] = 184.169998169;
   fMin_1[2][3] = 0;
   fMax_1[2][3] = 251.460006714;
   fMin_1[0][4] = 0;
   fMax_1[0][4] = 60;
   fMin_1[1][4] = 0;
   fMax_1[1][4] = 77;
   fMin_1[2][4] = 0;
   fMax_1[2][4] = 77;
   fMin_1[0][5] = 0;
   fMax_1[0][5] = 999;
   fMin_1[1][5] = 0;
   fMax_1[1][5] = 999;
   fMin_1[2][5] = 0;
   fMax_1[2][5] = 999;
   fMin_1[0][6] = 0;
   fMax_1[0][6] = 6.28299999237;
   fMin_1[1][6] = 0.0010000000475;
   fMax_1[1][6] = 6.28200006485;
   fMin_1[2][6] = 0;
   fMax_1[2][6] = 6.28299999237;
   fMin_1[0][7] = 3.57999992371;
   fMax_1[0][7] = 1585.47998047;
   fMin_1[1][7] = 100.010002136;
   fMax_1[1][7] = 662.650024414;
   fMin_1[2][7] = 3.57999992371;
   fMax_1[2][7] = 1585.47998047;
}

//_______________________________________________________________________
inline void ReadMLP3-BP::Transform_1( std::vector<double>& iv, int cls) const
{
   // Normalization transformation
   if (cls < 0 || cls > 2) {
   if (2 > 1 ) cls = 2;
      else cls = 2;
   }
   const int nVar = 8;

   // get indices of used variables

   // define the indices of the variables which are transformed by this transformation
   static std::vector<int> indicesGet;
   static std::vector<int> indicesPut;

   if ( indicesGet.empty() ) { 
      indicesGet.reserve(fNvars);
      indicesGet.push_back( 0);
      indicesGet.push_back( 1);
      indicesGet.push_back( 2);
      indicesGet.push_back( 3);
      indicesGet.push_back( 4);
      indicesGet.push_back( 5);
      indicesGet.push_back( 6);
      indicesGet.push_back( 7);
   } 
   if ( indicesPut.empty() ) { 
      indicesPut.reserve(fNvars);
      indicesPut.push_back( 0);
      indicesPut.push_back( 1);
      indicesPut.push_back( 2);
      indicesPut.push_back( 3);
      indicesPut.push_back( 4);
      indicesPut.push_back( 5);
      indicesPut.push_back( 6);
      indicesPut.push_back( 7);
   } 

   static std::vector<double> dv;
   dv.resize(nVar);
   for (int ivar=0; ivar<nVar; ivar++) dv[ivar] = iv[indicesGet.at(ivar)];
   for (int ivar=0;ivar<8;ivar++) {
      double offset = fMin_1[cls][ivar];
      double scale  = 1.0/(fMax_1[cls][ivar]-fMin_1[cls][ivar]);
      iv[indicesPut.at(ivar)] = (dv[ivar]-offset)*scale * 2 - 1;
   }
}

//_______________________________________________________________________
inline void ReadMLP3-BP::InitTransform()
{
   InitTransform_1();
}

//_______________________________________________________________________
inline void ReadMLP3-BP::Transform( std::vector<double>& iv, int sigOrBgd ) const
{
   Transform_1( iv, sigOrBgd );
}
