// Class: ReadMultiLayer2
// Automatically generated by MethodBase::MakeClass
//

/* configuration options =====================================================

#GEN -*-*-*-*-*-*-*-*-*-*-*- general info -*-*-*-*-*-*-*-*-*-*-*-

Method         : MLP::MultiLayer2
TMVA Release   : 4.2.0         [262656]
ROOT Release   : 5.34/18       [336402]
Creator        : zxb0111
Date           : Thu Dec  4 11:31:50 2014
Host           : Linux localhost.localdomain 2.6.32-431.17.1.el6.x86_64 #1 SMP Wed May 7 14:14:17 CDT 2014 x86_64 x86_64 x86_64 GNU/Linux
Dir            : /home/zxb0111/seminar
Training events: 34086
Analysis type  : [Classification]


#OPT -*-*-*-*-*-*-*-*-*-*-*-*- options -*-*-*-*-*-*-*-*-*-*-*-*-

# Set by User:
NCycles: "600" [Number of training cycles]
HiddenLayers: "N,N" [Specification of hidden layer architecture]
NeuronType: "sigmoid" [Neuron activation function type]
VarTransform: "N" [List of variable transformations performed before training, e.g., "D_Background,P_Signal,G,N_AllClasses" for: "Decorrelation, PCA-transformation, Gaussianisation, Normalisation, each for the given class of events ('AllClasses' denotes all events of all classes, if no class indication is given, 'All' is assumed)"]
TestRate: "5" [Test for overtraining performed at each #th epochs]
UseRegulator: "False" [Use regulator to avoid over-training]
# Default:
RandomSeed: "1" [Random seed for initial synapse weights (0 means unique seed for each run; default value '1')]
EstimatorType: "MSE" [MSE (Mean Square Estimator) for Gaussian Likelihood or CE(Cross-Entropy) for Bernoulli Likelihood]
NeuronInputType: "sum" [Neuron input function type]
V: "False" [Verbose output (short form of "VerbosityLevel" below - overrides the latter one)]
VerbosityLevel: "Default" [Verbosity level]
H: "False" [Print method-specific help message]
CreateMVAPdfs: "False" [Create PDFs for classifier outputs (signal and background)]
IgnoreNegWeightsInTraining: "False" [Events with negative weights are ignored in the training (but are included for testing and performance evaluation)]
TrainingMethod: "BP" [Train with Back-Propagation (BP), BFGS Algorithm (BFGS), or Genetic Algorithm (GA - slower and worse)]
LearningRate: "2.000000e-02" [ANN learning rate parameter]
DecayRate: "1.000000e-02" [Decay rate for learning parameter]
EpochMonitoring: "False" [Provide epoch-wise monitoring plots according to TestRate (caution: causes big ROOT output file!)]
Sampling: "1.000000e+00" [Only 'Sampling' (randomly selected) events are trained each epoch]
SamplingEpoch: "1.000000e+00" [Sampling is used for the first 'SamplingEpoch' epochs, afterwards, all events are taken for training]
SamplingImportance: "1.000000e+00" [ The sampling weights of events in epochs which successful (worse estimator than before) are multiplied with SamplingImportance, else they are divided.]
SamplingTraining: "True" [The training sample is sampled]
SamplingTesting: "False" [The testing sample is sampled]
ResetStep: "50" [How often BFGS should reset history]
Tau: "3.000000e+00" [LineSearch "size step"]
BPMode: "sequential" [Back-propagation learning mode: sequential or batch]
BatchSize: "-1" [Batch size: number of events/batch, only set if in Batch Mode, -1 for BatchSize=number_of_events]
ConvergenceImprove: "1.000000e-30" [Minimum improvement which counts as improvement (<0 means automatic convergence check is turned off)]
ConvergenceTests: "-1" [Number of steps (without improvement) required for convergence (<0 means automatic convergence check is turned off)]
UpdateLimit: "10000" [Maximum times of regulator update]
CalculateErrors: "False" [Calculates inverse Hessian matrix at the end of the training to be able to calculate the uncertainties of an MVA value]
WeightRange: "1.000000e+00" [Take the events for the estimator calculations from small deviations from the desired value to large deviations only over the weight range]
##


#VAR -*-*-*-*-*-*-*-*-*-*-*-* variables *-*-*-*-*-*-*-*-*-*-*-*-

NVar 8
Jet.PT                        Jet.PT                        Jet.PT                        Jet.PT                                                          'F'    [4.73000001907,2543.40991211]
Jet.Eta                       Jet.Eta                       Jet.Eta                       Jet.Eta                                                         'F'    [-3.99300003052,3.99099993706]
Jet.Phi                       Jet.Phi                       Jet.Phi                       Jet.Phi                                                         'F'    [0,6.28299999237]
Jet.Mass                      Jet.Mass                      Jet.Mass                      Jet.Mass                                                        'F'    [0,258.730010986]
Jet.Ntrk                      Jet.Ntrk                      Jet.Ntrk                      Jet.Ntrk                                                        'F'    [0,61]
Jet.EhadOverEem               Jet.EhadOverEem               Jet.EhadOverEem               Jet.EhadOverEem                                                 'F'    [0,999]
MissingET.Phi                 MissingET.Phi                 MissingET.Phi                 MissingET.Phi                                                   'F'    [0,6.28299999237]
MissingET.MET                 MissingET.MET                 MissingET.MET                 MissingET.MET                                                   'F'    [100.010002136,1585.47998047]
NSpec 0


============================================================================ */

#include <vector>
#include <cmath>
#include <string>
#include <iostream>

#ifndef IClassifierReader__def
#define IClassifierReader__def

class IClassifierReader {

 public:

   // constructor
   IClassifierReader() : fStatusIsClean( true ) {}
   virtual ~IClassifierReader() {}

   // return classifier response
   virtual double GetMvaValue( const std::vector<double>& inputValues ) const = 0;

   // returns classifier status
   bool IsStatusClean() const { return fStatusIsClean; }

 protected:

   bool fStatusIsClean;
};

#endif

class ReadMultiLayer2 : public IClassifierReader {

 public:

   // constructor
   ReadMultiLayer2( std::vector<std::string>& theInputVars ) 
      : IClassifierReader(),
        fClassName( "ReadMultiLayer2" ),
        fNvars( 8 ),
        fIsNormalised( false )
   {      
      // the training input variables
      const char* inputVars[] = { "Jet.PT", "Jet.Eta", "Jet.Phi", "Jet.Mass", "Jet.Ntrk", "Jet.EhadOverEem", "MissingET.Phi", "MissingET.MET" };

      // sanity checks
      if (theInputVars.size() <= 0) {
         std::cout << "Problem in class \"" << fClassName << "\": empty input vector" << std::endl;
         fStatusIsClean = false;
      }

      if (theInputVars.size() != fNvars) {
         std::cout << "Problem in class \"" << fClassName << "\": mismatch in number of input values: "
                   << theInputVars.size() << " != " << fNvars << std::endl;
         fStatusIsClean = false;
      }

      // validate input variables
      for (size_t ivar = 0; ivar < theInputVars.size(); ivar++) {
         if (theInputVars[ivar] != inputVars[ivar]) {
            std::cout << "Problem in class \"" << fClassName << "\": mismatch in input variable names" << std::endl
                      << " for variable [" << ivar << "]: " << theInputVars[ivar].c_str() << " != " << inputVars[ivar] << std::endl;
            fStatusIsClean = false;
         }
      }

      // initialize min and max vectors (for normalisation)
      fVmin[0] = -1;
      fVmax[0] = 1;
      fVmin[1] = -1;
      fVmax[1] = 1;
      fVmin[2] = -1;
      fVmax[2] = 0.99999988079071;
      fVmin[3] = -1;
      fVmax[3] = 1;
      fVmin[4] = -1;
      fVmax[4] = 0.99999988079071;
      fVmin[5] = -1;
      fVmax[5] = 1;
      fVmin[6] = -1;
      fVmax[6] = 0.99999988079071;
      fVmin[7] = -1;
      fVmax[7] = 1;

      // initialize input variable types
      fType[0] = 'F';
      fType[1] = 'F';
      fType[2] = 'F';
      fType[3] = 'F';
      fType[4] = 'F';
      fType[5] = 'F';
      fType[6] = 'F';
      fType[7] = 'F';

      // initialize constants
      Initialize();

      // initialize transformation
      InitTransform();
   }

   // destructor
   virtual ~ReadMultiLayer2() {
      Clear(); // method-specific
   }

   // the classifier response
   // "inputValues" is a vector of input values in the same order as the 
   // variables given to the constructor
   double GetMvaValue( const std::vector<double>& inputValues ) const;

 private:

   // method-specific destructor
   void Clear();

   // input variable transformation

   double fMin_1[3][8];
   double fMax_1[3][8];
   void InitTransform_1();
   void Transform_1( std::vector<double> & iv, int sigOrBgd ) const;
   void InitTransform();
   void Transform( std::vector<double> & iv, int sigOrBgd ) const;

   // common member variables
   const char* fClassName;

   const size_t fNvars;
   size_t GetNvar()           const { return fNvars; }
   char   GetType( int ivar ) const { return fType[ivar]; }

   // normalisation of input variables
   const bool fIsNormalised;
   bool IsNormalised() const { return fIsNormalised; }
   double fVmin[8];
   double fVmax[8];
   double NormVariable( double x, double xmin, double xmax ) const {
      // normalise to output range: [-1, 1]
      return 2*(x - xmin)/(xmax - xmin) - 1.0;
   }

   // type of input variable: 'F' or 'I'
   char   fType[8];

   // initialize internal variables
   void Initialize();
   double GetMvaValue__( const std::vector<double>& inputValues ) const;

   // private members (method specific)

   double ActivationFnc(double x) const;
   double OutputActivationFnc(double x) const;

   int fLayers;
   int fLayerSize[4];
   double fWeightMatrix0to1[9][9];   // weight matrix from layer 0 to 1
   double fWeightMatrix1to2[9][9];   // weight matrix from layer 1 to 2
   double fWeightMatrix2to3[1][9];   // weight matrix from layer 2 to 3

   double * fWeights[4];
};

inline void ReadMultiLayer2::Initialize()
{
   // build network structure
   fLayers = 4;
   fLayerSize[0] = 9; fWeights[0] = new double[9]; 
   fLayerSize[1] = 9; fWeights[1] = new double[9]; 
   fLayerSize[2] = 9; fWeights[2] = new double[9]; 
   fLayerSize[3] = 1; fWeights[3] = new double[1]; 
   // weight matrix from layer 0 to 1
   fWeightMatrix0to1[0][0] = 0.216689850138647;
   fWeightMatrix0to1[1][0] = 2.60856894378748;
   fWeightMatrix0to1[2][0] = 0.743934974254436;
   fWeightMatrix0to1[3][0] = 2.03172248170859;
   fWeightMatrix0to1[4][0] = -2.13005135820878;
   fWeightMatrix0to1[5][0] = -3.90322758882114;
   fWeightMatrix0to1[6][0] = -7.10799483975501;
   fWeightMatrix0to1[7][0] = 1.66627024448931;
   fWeightMatrix0to1[0][1] = 0.068619751139282;
   fWeightMatrix0to1[1][1] = -0.0202254068093911;
   fWeightMatrix0to1[2][1] = -0.951817902679003;
   fWeightMatrix0to1[3][1] = 0.0293312494029385;
   fWeightMatrix0to1[4][1] = -1.34061852740486;
   fWeightMatrix0to1[5][1] = 0.0574679330576706;
   fWeightMatrix0to1[6][1] = -0.0287187648073628;
   fWeightMatrix0to1[7][1] = 0.631934830665836;
   fWeightMatrix0to1[0][2] = -5.62575033597496;
   fWeightMatrix0to1[1][2] = 0.0612277758191188;
   fWeightMatrix0to1[2][2] = 0.332445276861014;
   fWeightMatrix0to1[3][2] = 1.34947936909116;
   fWeightMatrix0to1[4][2] = -0.27711304376706;
   fWeightMatrix0to1[5][2] = -2.05058226121698;
   fWeightMatrix0to1[6][2] = 0.290557110238041;
   fWeightMatrix0to1[7][2] = 0.147316844048802;
   fWeightMatrix0to1[0][3] = -0.738980985494707;
   fWeightMatrix0to1[1][3] = 1.89166134140774;
   fWeightMatrix0to1[2][3] = 1.25916417855812;
   fWeightMatrix0to1[3][3] = -1.13424719111357;
   fWeightMatrix0to1[4][3] = -1.9065407210092;
   fWeightMatrix0to1[5][3] = -0.298925863115118;
   fWeightMatrix0to1[6][3] = -1.16610704883974;
   fWeightMatrix0to1[7][3] = 1.50485994969648;
   fWeightMatrix0to1[0][4] = 0.199211092076794;
   fWeightMatrix0to1[1][4] = -0.076860541825373;
   fWeightMatrix0to1[2][4] = 0.220314466973324;
   fWeightMatrix0to1[3][4] = 0.218315827950379;
   fWeightMatrix0to1[4][4] = -1.3934164371248;
   fWeightMatrix0to1[5][4] = -0.61381940810321;
   fWeightMatrix0to1[6][4] = -0.92509262016234;
   fWeightMatrix0to1[7][4] = 1.01807423575902;
   fWeightMatrix0to1[0][5] = 0.643273465255258;
   fWeightMatrix0to1[1][5] = 0.898618736179539;
   fWeightMatrix0to1[2][5] = 1.67859104137195;
   fWeightMatrix0to1[3][5] = 1.39358421941424;
   fWeightMatrix0to1[4][5] = -0.820931120642117;
   fWeightMatrix0to1[5][5] = -0.0850660625954066;
   fWeightMatrix0to1[6][5] = 2.80738491866597;
   fWeightMatrix0to1[7][5] = 0.200006926897164;
   fWeightMatrix0to1[0][6] = 5.73396767616312;
   fWeightMatrix0to1[1][6] = -0.269677405593622;
   fWeightMatrix0to1[2][6] = 1.65632630040697;
   fWeightMatrix0to1[3][6] = 0.732522964623644;
   fWeightMatrix0to1[4][6] = -1.30800804570781;
   fWeightMatrix0to1[5][6] = 2.17048364342838;
   fWeightMatrix0to1[6][6] = -0.0806104740728076;
   fWeightMatrix0to1[7][6] = -0.68438116139631;
   fWeightMatrix0to1[0][7] = -1.29313751045382;
   fWeightMatrix0to1[1][7] = -11.4659137367775;
   fWeightMatrix0to1[2][7] = 1.20723106680252;
   fWeightMatrix0to1[3][7] = 1.09754489089852;
   fWeightMatrix0to1[4][7] = -1.79751970164631;
   fWeightMatrix0to1[5][7] = -1.07664723916574;
   fWeightMatrix0to1[6][7] = -0.0865538578144886;
   fWeightMatrix0to1[7][7] = 0.477357039318927;
   fWeightMatrix0to1[0][8] = 2.13916623351041;
   fWeightMatrix0to1[1][8] = -4.34090880669034;
   fWeightMatrix0to1[2][8] = 0.797422033452343;
   fWeightMatrix0to1[3][8] = -0.589114992008346;
   fWeightMatrix0to1[4][8] = 0.923798357391208;
   fWeightMatrix0to1[5][8] = -4.60103142108292;
   fWeightMatrix0to1[6][8] = -3.65400882677559;
   fWeightMatrix0to1[7][8] = -1.50576063637551;
   // weight matrix from layer 1 to 2
   fWeightMatrix1to2[0][0] = 0.502139036277;
   fWeightMatrix1to2[1][0] = -0.629315691568594;
   fWeightMatrix1to2[2][0] = 1.4377106275591;
   fWeightMatrix1to2[3][0] = -1.45354781522146;
   fWeightMatrix1to2[4][0] = -2.23518989180507;
   fWeightMatrix1to2[5][0] = -2.21215248486068;
   fWeightMatrix1to2[6][0] = -4.25906676168301;
   fWeightMatrix1to2[7][0] = 0.867289225857521;
   fWeightMatrix1to2[0][1] = 1.00207523713459;
   fWeightMatrix1to2[1][1] = 2.52106667461843;
   fWeightMatrix1to2[2][1] = 1.78959340912243;
   fWeightMatrix1to2[3][1] = -2.04999429964068;
   fWeightMatrix1to2[4][1] = -1.13907339706843;
   fWeightMatrix1to2[5][1] = -0.458640623121449;
   fWeightMatrix1to2[6][1] = 6.70636923481235;
   fWeightMatrix1to2[7][1] = -3.08618192717614;
   fWeightMatrix1to2[0][2] = -1.6016979050056;
   fWeightMatrix1to2[1][2] = -1.52529420231259;
   fWeightMatrix1to2[2][2] = -0.0976775891152442;
   fWeightMatrix1to2[3][2] = -0.10504400619928;
   fWeightMatrix1to2[4][2] = 1.62045144348112;
   fWeightMatrix1to2[5][2] = -1.62459221710602;
   fWeightMatrix1to2[6][2] = -1.75735785282896;
   fWeightMatrix1to2[7][2] = 1.64849879691035;
   fWeightMatrix1to2[0][3] = -1.12937643862382;
   fWeightMatrix1to2[1][3] = -1.28806289769405;
   fWeightMatrix1to2[2][3] = -1.11328371903624;
   fWeightMatrix1to2[3][3] = -0.435151818663411;
   fWeightMatrix1to2[4][3] = -2.11417989481628;
   fWeightMatrix1to2[5][3] = -1.66406889499111;
   fWeightMatrix1to2[6][3] = -1.62978138814996;
   fWeightMatrix1to2[7][3] = 2.1509221310303;
   fWeightMatrix1to2[0][4] = -1.50590392082851;
   fWeightMatrix1to2[1][4] = 0.0218435846540229;
   fWeightMatrix1to2[2][4] = -1.34390549011859;
   fWeightMatrix1to2[3][4] = -1.63734720234339;
   fWeightMatrix1to2[4][4] = -0.670011720827574;
   fWeightMatrix1to2[5][4] = -0.210780653143153;
   fWeightMatrix1to2[6][4] = -4.85536770778294;
   fWeightMatrix1to2[7][4] = 0.590119760053986;
   fWeightMatrix1to2[0][5] = -0.83424993741341;
   fWeightMatrix1to2[1][5] = 0.651878496237269;
   fWeightMatrix1to2[2][5] = -1.60164198240008;
   fWeightMatrix1to2[3][5] = 1.26291279969109;
   fWeightMatrix1to2[4][5] = -0.230807470020703;
   fWeightMatrix1to2[5][5] = -1.22904580314725;
   fWeightMatrix1to2[6][5] = 5.61322055271141;
   fWeightMatrix1to2[7][5] = -1.45538762996757;
   fWeightMatrix1to2[0][6] = -2.5027087861962;
   fWeightMatrix1to2[1][6] = 1.46725706228961;
   fWeightMatrix1to2[2][6] = -1.13652264661132;
   fWeightMatrix1to2[3][6] = 1.38891936822722;
   fWeightMatrix1to2[4][6] = 0.0162402327965463;
   fWeightMatrix1to2[5][6] = -0.0690324018375505;
   fWeightMatrix1to2[6][6] = 5.11348460278635;
   fWeightMatrix1to2[7][6] = -1.6616307408339;
   fWeightMatrix1to2[0][7] = -1.71971912070941;
   fWeightMatrix1to2[1][7] = 0.83130007390291;
   fWeightMatrix1to2[2][7] = 0.0270417291929218;
   fWeightMatrix1to2[3][7] = -1.76550833975662;
   fWeightMatrix1to2[4][7] = 0.652095642639486;
   fWeightMatrix1to2[5][7] = -1.44652600675385;
   fWeightMatrix1to2[6][7] = -0.177172256840407;
   fWeightMatrix1to2[7][7] = 1.22702453256319;
   fWeightMatrix1to2[0][8] = 1.35543945788311;
   fWeightMatrix1to2[1][8] = -3.49740820007917;
   fWeightMatrix1to2[2][8] = -0.125904237675685;
   fWeightMatrix1to2[3][8] = 0.614525280776674;
   fWeightMatrix1to2[4][8] = 0.972115830989828;
   fWeightMatrix1to2[5][8] = -0.381871047006884;
   fWeightMatrix1to2[6][8] = -4.61950022228921;
   fWeightMatrix1to2[7][8] = 0.142492466682253;
   // weight matrix from layer 2 to 3
   fWeightMatrix2to3[0][0] = 0.146765702542807;
   fWeightMatrix2to3[0][1] = 1.17025608480686;
   fWeightMatrix2to3[0][2] = 0.0243721958755412;
   fWeightMatrix2to3[0][3] = 0.344215916068244;
   fWeightMatrix2to3[0][4] = -0.22169381621165;
   fWeightMatrix2to3[0][5] = 0.104436956286818;
   fWeightMatrix2to3[0][6] = -1.52668802395444;
   fWeightMatrix2to3[0][7] = 0.312743258663612;
   fWeightMatrix2to3[0][8] = 0.681965478208951;
}

inline double ReadMultiLayer2::GetMvaValue__( const std::vector<double>& inputValues ) const
{
   if (inputValues.size() != (unsigned int)fLayerSize[0]-1) {
      std::cout << "Input vector needs to be of size " << fLayerSize[0]-1 << std::endl;
      return 0;
   }

   for (int l=0; l<fLayers; l++)
      for (int i=0; i<fLayerSize[l]; i++) fWeights[l][i]=0;

   for (int l=0; l<fLayers-1; l++)
      fWeights[l][fLayerSize[l]-1]=1;

   for (int i=0; i<fLayerSize[0]-1; i++)
      fWeights[0][i]=inputValues[i];

   // layer 0 to 1
   for (int o=0; o<fLayerSize[1]-1; o++) {
      for (int i=0; i<fLayerSize[0]; i++) {
         double inputVal = fWeightMatrix0to1[o][i] * fWeights[0][i];
         fWeights[1][o] += inputVal;
      }
      fWeights[1][o] = ActivationFnc(fWeights[1][o]);
   }
   // layer 1 to 2
   for (int o=0; o<fLayerSize[2]-1; o++) {
      for (int i=0; i<fLayerSize[1]; i++) {
         double inputVal = fWeightMatrix1to2[o][i] * fWeights[1][i];
         fWeights[2][o] += inputVal;
      }
      fWeights[2][o] = ActivationFnc(fWeights[2][o]);
   }
   // layer 2 to 3
   for (int o=0; o<fLayerSize[3]; o++) {
      for (int i=0; i<fLayerSize[2]; i++) {
         double inputVal = fWeightMatrix2to3[o][i] * fWeights[2][i];
         fWeights[3][o] += inputVal;
      }
      fWeights[3][o] = OutputActivationFnc(fWeights[3][o]);
   }

   return fWeights[3][0];
}

double ReadMultiLayer2::ActivationFnc(double x) const {
   // sigmoid
   return 1.0/(1.0+exp(-x));
}
double ReadMultiLayer2::OutputActivationFnc(double x) const {
   // identity
   return x;
}
   
// Clean up
inline void ReadMultiLayer2::Clear() 
{
   // clean up the arrays
   for (int lIdx = 0; lIdx < 4; lIdx++) {
      delete[] fWeights[lIdx];
   }
}
   inline double ReadMultiLayer2::GetMvaValue( const std::vector<double>& inputValues ) const
   {
      // classifier response value
      double retval = 0;

      // classifier response, sanity check first
      if (!IsStatusClean()) {
         std::cout << "Problem in class \"" << fClassName << "\": cannot return classifier response"
                   << " because status is dirty" << std::endl;
         retval = 0;
      }
      else {
         if (IsNormalised()) {
            // normalise variables
            std::vector<double> iV;
            iV.resize(inputValues.size());
            int ivar = 0;
            for (std::vector<double>::const_iterator varIt = inputValues.begin();
                 varIt != inputValues.end(); varIt++, ivar++) {
               iV.push_back(NormVariable( *varIt, fVmin[ivar], fVmax[ivar] ));
            }
            Transform( iV, -1 );
            retval = GetMvaValue__( iV );
         }
         else {
            std::vector<double> iV;
            int ivar = 0;
            for (std::vector<double>::const_iterator varIt = inputValues.begin();
                 varIt != inputValues.end(); varIt++, ivar++) {
               iV.push_back(*varIt);
            }
            Transform( iV, -1 );
            retval = GetMvaValue__( iV );
         }
      }

      return retval;
   }

//_______________________________________________________________________
inline void ReadMultiLayer2::InitTransform_1()
{
   // Normalization transformation, initialisation
   fMin_1[0][0] = 5;
   fMax_1[0][0] = 2543.40991211;
   fMin_1[1][0] = 4.73000001907;
   fMax_1[1][0] = 817.520019531;
   fMin_1[2][0] = 4.73000001907;
   fMax_1[2][0] = 2543.40991211;
   fMin_1[0][1] = -3.99099993706;
   fMax_1[0][1] = 3.99099993706;
   fMin_1[1][1] = -3.99300003052;
   fMax_1[1][1] = 3.99000000954;
   fMin_1[2][1] = -3.99300003052;
   fMax_1[2][1] = 3.99099993706;
   fMin_1[0][2] = 0;
   fMax_1[0][2] = 6.28299999237;
   fMin_1[1][2] = 0;
   fMax_1[1][2] = 6.28299999237;
   fMin_1[2][2] = 0;
   fMax_1[2][2] = 6.28299999237;
   fMin_1[0][3] = 0;
   fMax_1[0][3] = 258.730010986;
   fMin_1[1][3] = 0;
   fMax_1[1][3] = 159.369995117;
   fMin_1[2][3] = 0;
   fMax_1[2][3] = 258.730010986;
   fMin_1[0][4] = 0;
   fMax_1[0][4] = 61;
   fMin_1[1][4] = 0;
   fMax_1[1][4] = 59;
   fMin_1[2][4] = 0;
   fMax_1[2][4] = 61;
   fMin_1[0][5] = 0;
   fMax_1[0][5] = 999;
   fMin_1[1][5] = 0;
   fMax_1[1][5] = 999;
   fMin_1[2][5] = 0;
   fMax_1[2][5] = 999;
   fMin_1[0][6] = 0;
   fMax_1[0][6] = 6.28299999237;
   fMin_1[1][6] = 0.0010000000475;
   fMax_1[1][6] = 6.28200006485;
   fMin_1[2][6] = 0;
   fMax_1[2][6] = 6.28299999237;
   fMin_1[0][7] = 100.019996643;
   fMax_1[0][7] = 1585.47998047;
   fMin_1[1][7] = 100.010002136;
   fMax_1[1][7] = 662.650024414;
   fMin_1[2][7] = 100.010002136;
   fMax_1[2][7] = 1585.47998047;
}

//_______________________________________________________________________
inline void ReadMultiLayer2::Transform_1( std::vector<double>& iv, int cls) const
{
   // Normalization transformation
   if (cls < 0 || cls > 2) {
   if (2 > 1 ) cls = 2;
      else cls = 2;
   }
   const int nVar = 8;

   // get indices of used variables

   // define the indices of the variables which are transformed by this transformation
   static std::vector<int> indicesGet;
   static std::vector<int> indicesPut;

   if ( indicesGet.empty() ) { 
      indicesGet.reserve(nVar);
      indicesGet.push_back( 0);
      indicesGet.push_back( 1);
      indicesGet.push_back( 2);
      indicesGet.push_back( 3);
      indicesGet.push_back( 4);
      indicesGet.push_back( 5);
      indicesGet.push_back( 6);
      indicesGet.push_back( 7);
   } 
   if ( indicesPut.empty() ) { 
      indicesPut.reserve(nVar);
      indicesPut.push_back( 0);
      indicesPut.push_back( 1);
      indicesPut.push_back( 2);
      indicesPut.push_back( 3);
      indicesPut.push_back( 4);
      indicesPut.push_back( 5);
      indicesPut.push_back( 6);
      indicesPut.push_back( 7);
   } 

   static std::vector<double> dv;
   dv.resize(nVar);
   for (int ivar=0; ivar<nVar; ivar++) dv[ivar] = iv[indicesGet.at(ivar)];
   for (int ivar=0;ivar<8;ivar++) {
      double offset = fMin_1[cls][ivar];
      double scale  = 1.0/(fMax_1[cls][ivar]-fMin_1[cls][ivar]);
      iv[indicesPut.at(ivar)] = (dv[ivar]-offset)*scale * 2 - 1;
   }
}

//_______________________________________________________________________
inline void ReadMultiLayer2::InitTransform()
{
   InitTransform_1();
}

//_______________________________________________________________________
inline void ReadMultiLayer2::Transform( std::vector<double>& iv, int sigOrBgd ) const
{
   Transform_1( iv, sigOrBgd );
}
